package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Act generated by hbm2java
 */
@Entity
@Table( name = "act", catalog = "etatcivildb" )
public class Act implements java.io.Serializable {

    private int             idact;
    private Declaration     declaration;
    private Edition         edition;
    private Person          person;
    private Register        register;
    private Integer         number;
    private Integer         status;
    private Integer         dayActGregorian;
    private Integer         monthActGregorian;
    private Integer         yearActGregorian;
    private Integer         dayActHijri;
    private Integer         monthActHijri;
    private Integer         yearActHijri;
    private Integer         hourAct;
    private Integer         minuteAct;
    private String          localActAr;
    private String          localActFr;
    private String          cityActAr;
    private String          cityActFr;
    private String          firstNameMarginAr;
    private String          lastNameMarginAr;
    private String          firstNameMarginFr;
    private String          lastNameMarginFr;
    private Integer         isProblem;
    private String          comment;
    private Integer         transcriptionDayGregorian;
    private Integer         transcriptionMonthGregorian;
    private Integer         transcriptionYearGregorian;
    private Integer         transcriptionDayHijri;
    private Integer         transcriptionMonthHijri;
    private Integer         transcriptionYearHijri;
    private String          transcriptionOrigineAr;
    private Integer         isTranscripted;
    private String          transcriptionOrigineFr;
    private String          flag;
    private Set<Attachment> attachments = new HashSet<Attachment>( 0 );
    private Set<Mention>    mentions    = new HashSet<Mention>( 0 );

    public Act() {
    }

    public Act( int idact ) {
        this.idact = idact;
    }

    public Act( int idact, Declaration declaration, Edition edition, Person person, Register register, Integer number,
            Integer status, Integer dayActGregorian, Integer monthActGregorian, Integer yearActGregorian,
            Integer dayActHijri, Integer monthActHijri, Integer yearActHijri, Integer hourAct, Integer minuteAct,
            String localActAr, String localActFr, String cityActAr, String cityActFr, String firstNameMarginAr,
            String lastNameMarginAr, String firstNameMarginFr, String lastNameMarginFr, Integer isProblem,
            String comment, Integer transcriptionDayGregorian, Integer transcriptionMonthGregorian,
            Integer transcriptionYearGregorian, Integer transcriptionDayHijri, Integer transcriptionMonthHijri,
            Integer transcriptionYearHijri, String transcriptionOrigineAr, Integer isTranscripted,
            String transcriptionOrigineFr, String flag, Set<Attachment> attachments, Set<Mention> mentions ) {
        this.idact = idact;
        this.declaration = declaration;
        this.edition = edition;
        this.person = person;
        this.register = register;
        this.number = number;
        this.status = status;
        this.dayActGregorian = dayActGregorian;
        this.monthActGregorian = monthActGregorian;
        this.yearActGregorian = yearActGregorian;
        this.dayActHijri = dayActHijri;
        this.monthActHijri = monthActHijri;
        this.yearActHijri = yearActHijri;
        this.hourAct = hourAct;
        this.minuteAct = minuteAct;
        this.localActAr = localActAr;
        this.localActFr = localActFr;
        this.cityActAr = cityActAr;
        this.cityActFr = cityActFr;
        this.firstNameMarginAr = firstNameMarginAr;
        this.lastNameMarginAr = lastNameMarginAr;
        this.firstNameMarginFr = firstNameMarginFr;
        this.lastNameMarginFr = lastNameMarginFr;
        this.isProblem = isProblem;
        this.comment = comment;
        this.transcriptionDayGregorian = transcriptionDayGregorian;
        this.transcriptionMonthGregorian = transcriptionMonthGregorian;
        this.transcriptionYearGregorian = transcriptionYearGregorian;
        this.transcriptionDayHijri = transcriptionDayHijri;
        this.transcriptionMonthHijri = transcriptionMonthHijri;
        this.transcriptionYearHijri = transcriptionYearHijri;
        this.transcriptionOrigineAr = transcriptionOrigineAr;
        this.isTranscripted = isTranscripted;
        this.transcriptionOrigineFr = transcriptionOrigineFr;
        this.flag = flag;
        this.attachments = attachments;
        this.mentions = mentions;
    }

    @Id

    @Column( name = "IDAct", unique = true, nullable = false )
    public int getIdact() {
        return this.idact;
    }

    public void setIdact( int idact ) {
        this.idact = idact;
    }

    @ManyToOne( fetch = FetchType.EAGER )
    @JoinColumn( name = "IDDeclaration" )
    public Declaration getDeclaration() {
        return this.declaration;
    }

    public void setDeclaration( Declaration declaration ) {
        this.declaration = declaration;
    }

    @ManyToOne( fetch = FetchType.EAGER )
    @JoinColumn( name = "IDEdition" )
    public Edition getEdition() {
        return this.edition;
    }

    public void setEdition( Edition edition ) {
        this.edition = edition;
    }

    @ManyToOne( fetch = FetchType.EAGER )
    @JoinColumn( name = "IDPerson" )
    public Person getPerson() {
        return this.person;
    }

    public void setPerson( Person person ) {
        this.person = person;
    }

    @ManyToOne( fetch = FetchType.EAGER )
    @JoinColumn( name = "IDRegister" )
    public Register getRegister() {
        return this.register;
    }

    public void setRegister( Register register ) {
        this.register = register;
    }

    @Column( name = "Number" )
    public Integer getNumber() {
        return this.number;
    }

    public void setNumber( Integer number ) {
        this.number = number;
    }

    @Column( name = "Status" )
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus( Integer status ) {
        this.status = status;
    }

    @Column( name = "DayActGregorian" )
    public Integer getDayActGregorian() {
        return this.dayActGregorian;
    }

    public void setDayActGregorian( Integer dayActGregorian ) {
        this.dayActGregorian = dayActGregorian;
    }

    @Column( name = "MonthActGregorian" )
    public Integer getMonthActGregorian() {
        return this.monthActGregorian;
    }

    public void setMonthActGregorian( Integer monthActGregorian ) {
        this.monthActGregorian = monthActGregorian;
    }

    @Column( name = "YearActGregorian" )
    public Integer getYearActGregorian() {
        return this.yearActGregorian;
    }

    public void setYearActGregorian( Integer yearActGregorian ) {
        this.yearActGregorian = yearActGregorian;
    }

    @Column( name = "DayActHijri" )
    public Integer getDayActHijri() {
        return this.dayActHijri;
    }

    public void setDayActHijri( Integer dayActHijri ) {
        this.dayActHijri = dayActHijri;
    }

    @Column( name = "MonthActHijri" )
    public Integer getMonthActHijri() {
        return this.monthActHijri;
    }

    public void setMonthActHijri( Integer monthActHijri ) {
        this.monthActHijri = monthActHijri;
    }

    @Column( name = "YearActHijri" )
    public Integer getYearActHijri() {
        return this.yearActHijri;
    }

    public void setYearActHijri( Integer yearActHijri ) {
        this.yearActHijri = yearActHijri;
    }

    @Column( name = "HourAct" )
    public Integer getHourAct() {
        return this.hourAct;
    }

    public void setHourAct( Integer hourAct ) {
        this.hourAct = hourAct;
    }

    @Column( name = "MinuteAct" )
    public Integer getMinuteAct() {
        return this.minuteAct;
    }

    public void setMinuteAct( Integer minuteAct ) {
        this.minuteAct = minuteAct;
    }

    @Column( name = "LocalActAr" )
    public String getLocalActAr() {
        return this.localActAr;
    }

    public void setLocalActAr( String localActAr ) {
        this.localActAr = localActAr;
    }

    @Column( name = "LocalActFr" )
    public String getLocalActFr() {
        return this.localActFr;
    }

    public void setLocalActFr( String localActFr ) {
        this.localActFr = localActFr;
    }

    @Column( name = "CityActAr" )
    public String getCityActAr() {
        return this.cityActAr;
    }

    public void setCityActAr( String cityActAr ) {
        this.cityActAr = cityActAr;
    }

    @Column( name = "CityActFr" )
    public String getCityActFr() {
        return this.cityActFr;
    }

    public void setCityActFr( String cityActFr ) {
        this.cityActFr = cityActFr;
    }

    @Column( name = "FirstNameMarginAr" )
    public String getFirstNameMarginAr() {
        return this.firstNameMarginAr;
    }

    public void setFirstNameMarginAr( String firstNameMarginAr ) {
        this.firstNameMarginAr = firstNameMarginAr;
    }

    @Column( name = "LastNameMarginAr" )
    public String getLastNameMarginAr() {
        return this.lastNameMarginAr;
    }

    public void setLastNameMarginAr( String lastNameMarginAr ) {
        this.lastNameMarginAr = lastNameMarginAr;
    }

    @Column( name = "FirstNameMarginFr" )
    public String getFirstNameMarginFr() {
        return this.firstNameMarginFr;
    }

    public void setFirstNameMarginFr( String firstNameMarginFr ) {
        this.firstNameMarginFr = firstNameMarginFr;
    }

    @Column( name = "LastNameMarginFr" )
    public String getLastNameMarginFr() {
        return this.lastNameMarginFr;
    }

    public void setLastNameMarginFr( String lastNameMarginFr ) {
        this.lastNameMarginFr = lastNameMarginFr;
    }

    @Column( name = "IsProblem" )
    public Integer getIsProblem() {
        return this.isProblem;
    }

    public void setIsProblem( Integer isProblem ) {
        this.isProblem = isProblem;
    }

    @Column( name = "Comment", length = 65535 )
    public String getComment() {
        return this.comment;
    }

    public void setComment( String comment ) {
        this.comment = comment;
    }

    @Column( name = "TranscriptionDayGregorian" )
    public Integer getTranscriptionDayGregorian() {
        return this.transcriptionDayGregorian;
    }

    public void setTranscriptionDayGregorian( Integer transcriptionDayGregorian ) {
        this.transcriptionDayGregorian = transcriptionDayGregorian;
    }

    @Column( name = "TranscriptionMonthGregorian" )
    public Integer getTranscriptionMonthGregorian() {
        return this.transcriptionMonthGregorian;
    }

    public void setTranscriptionMonthGregorian( Integer transcriptionMonthGregorian ) {
        this.transcriptionMonthGregorian = transcriptionMonthGregorian;
    }

    @Column( name = "TranscriptionYearGregorian" )
    public Integer getTranscriptionYearGregorian() {
        return this.transcriptionYearGregorian;
    }

    public void setTranscriptionYearGregorian( Integer transcriptionYearGregorian ) {
        this.transcriptionYearGregorian = transcriptionYearGregorian;
    }

    @Column( name = "TranscriptionDayHijri" )
    public Integer getTranscriptionDayHijri() {
        return this.transcriptionDayHijri;
    }

    public void setTranscriptionDayHijri( Integer transcriptionDayHijri ) {
        this.transcriptionDayHijri = transcriptionDayHijri;
    }

    @Column( name = "TranscriptionMonthHijri" )
    public Integer getTranscriptionMonthHijri() {
        return this.transcriptionMonthHijri;
    }

    public void setTranscriptionMonthHijri( Integer transcriptionMonthHijri ) {
        this.transcriptionMonthHijri = transcriptionMonthHijri;
    }

    @Column( name = "TranscriptionYearHijri" )
    public Integer getTranscriptionYearHijri() {
        return this.transcriptionYearHijri;
    }

    public void setTranscriptionYearHijri( Integer transcriptionYearHijri ) {
        this.transcriptionYearHijri = transcriptionYearHijri;
    }

    @Column( name = "TranscriptionOrigineAr" )
    public String getTranscriptionOrigineAr() {
        return this.transcriptionOrigineAr;
    }

    public void setTranscriptionOrigineAr( String transcriptionOrigineAr ) {
        this.transcriptionOrigineAr = transcriptionOrigineAr;
    }

    @Column( name = "IsTranscripted" )
    public Integer getIsTranscripted() {
        return this.isTranscripted;
    }

    public void setIsTranscripted( Integer isTranscripted ) {
        this.isTranscripted = isTranscripted;
    }

    @Column( name = "TranscriptionOrigineFr" )
    public String getTranscriptionOrigineFr() {
        return this.transcriptionOrigineFr;
    }

    public void setTranscriptionOrigineFr( String transcriptionOrigineFr ) {
        this.transcriptionOrigineFr = transcriptionOrigineFr;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "act" )
    public Set<Attachment> getAttachments() {
        return this.attachments;
    }

    public void setAttachments( Set<Attachment> attachments ) {
        this.attachments = attachments;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "act" )
    public Set<Mention> getMentions() {
        return this.mentions;
    }

    public void setMentions( Set<Mention> mentions ) {
        this.mentions = mentions;
    }

}
