package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Annex generated by hbm2java
 */
@Entity
@Table( name = "annex", catalog = "etatcivildb" )
public class Annex implements java.io.Serializable {

    private int           idannex;
    private District      district;
    private String        codeAr;
    private String        codeFr;
    private Integer       defaultBirth;
    private Integer       defaultDeath;
    private String        flag;
    private Set<Register> registers = new HashSet<Register>( 0 );

    public Annex() {
    }

    public Annex( int idannex ) {
        this.idannex = idannex;
    }

    public Annex( int idannex, District district, String codeAr, String codeFr, Integer defaultBirth,
            Integer defaultDeath, String flag, Set<Register> registers ) {
        this.idannex = idannex;
        this.district = district;
        this.codeAr = codeAr;
        this.codeFr = codeFr;
        this.defaultBirth = defaultBirth;
        this.defaultDeath = defaultDeath;
        this.flag = flag;
        this.registers = registers;
    }

    @Id

    @Column( name = "IDAnnex", unique = true, nullable = false )
    public int getIdannex() {
        return this.idannex;
    }

    public void setIdannex( int idannex ) {
        this.idannex = idannex;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDDistrict" )
    public District getDistrict() {
        return this.district;
    }

    public void setDistrict( District district ) {
        this.district = district;
    }

    @Column( name = "CodeAr", length = 45 )
    public String getCodeAr() {
        return this.codeAr;
    }

    public void setCodeAr( String codeAr ) {
        this.codeAr = codeAr;
    }

    @Column( name = "CodeFr", length = 45 )
    public String getCodeFr() {
        return this.codeFr;
    }

    public void setCodeFr( String codeFr ) {
        this.codeFr = codeFr;
    }

    @Column( name = "DefaultBirth" )
    public Integer getDefaultBirth() {
        return this.defaultBirth;
    }

    public void setDefaultBirth( Integer defaultBirth ) {
        this.defaultBirth = defaultBirth;
    }

    @Column( name = "DefaultDeath" )
    public Integer getDefaultDeath() {
        return this.defaultDeath;
    }

    public void setDefaultDeath( Integer defaultDeath ) {
        this.defaultDeath = defaultDeath;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "annex" )
    public Set<Register> getRegisters() {
        return this.registers;
    }

    public void setRegisters( Set<Register> registers ) {
        this.registers = registers;
    }

}
