package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Attachment generated by hbm2java
 */
@Entity
@Table( name = "attachment", catalog = "etatcivildb" )
public class Attachment implements java.io.Serializable {

    private int    idattachment;
    private Act    act;
    private String path;
    private String comment;
    private String flag;

    public Attachment() {
    }

    public Attachment( int idattachment ) {
        this.idattachment = idattachment;
    }

    public Attachment( int idattachment, Act act, String path, String comment, String flag ) {
        this.idattachment = idattachment;
        this.act = act;
        this.path = path;
        this.comment = comment;
        this.flag = flag;
    }

    @Id

    @Column( name = "IDAttachment", unique = true, nullable = false )
    public int getIdattachment() {
        return this.idattachment;
    }

    public void setIdattachment( int idattachment ) {
        this.idattachment = idattachment;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDAct" )
    public Act getAct() {
        return this.act;
    }

    public void setAct( Act act ) {
        this.act = act;
    }

    @Column( name = "Path" )
    public String getPath() {
        return this.path;
    }

    public void setPath( String path ) {
        this.path = path;
    }

    @Column( name = "Comment", length = 65535 )
    public String getComment() {
        return this.comment;
    }

    public void setComment( String comment ) {
        this.comment = comment;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

}
