package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attestationdiverses generated by hbm2java
 */
@Entity
@Table( name = "attestationdiverses", catalog = "etatcivildb" )
public class Attestationdiverses implements java.io.Serializable {

    private Integer idattestation;
    private String  name;
    private String  cin;
    private Date    date;
    private String  numero;
    private String  typeAttestation;
    private String  langue;
    private int     idannex;

    public Attestationdiverses() {
    }

    public Attestationdiverses( String name, String cin, Date date, String numero, String typeAttestation,
            String langue, int idannex ) {
        this.name = name;
        this.cin = cin;
        this.date = date;
        this.numero = numero;
        this.typeAttestation = typeAttestation;
        this.langue = langue;
        this.idannex = idannex;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "idattestation", unique = true, nullable = false )
    public Integer getIdattestation() {
        return this.idattestation;
    }

    public void setIdattestation( Integer idattestation ) {
        this.idattestation = idattestation;
    }

    @Column( name = "name", nullable = false, length = 45 )
    public String getName() {
        return this.name;
    }

    public void setName( String name ) {
        this.name = name;
    }

    @Column( name = "cin", nullable = false, length = 45 )
    public String getCin() {
        return this.cin;
    }

    public void setCin( String cin ) {
        this.cin = cin;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "date", nullable = false, length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "numero", nullable = false, length = 45 )
    public String getNumero() {
        return this.numero;
    }

    public void setNumero( String numero ) {
        this.numero = numero;
    }

    @Column( name = "TypeAttestation", nullable = false, length = 128 )
    public String getTypeAttestation() {
        return this.typeAttestation;
    }

    public void setTypeAttestation( String typeAttestation ) {
        this.typeAttestation = typeAttestation;
    }

    @Column( name = "langue", nullable = false, length = 45 )
    public String getLangue() {
        return this.langue;
    }

    public void setLangue( String langue ) {
        this.langue = langue;
    }

    @Column( name = "IDAnnex", nullable = false )
    public int getIdannex() {
        return this.idannex;
    }

    public void setIdannex( int idannex ) {
        this.idannex = idannex;
    }

}
