package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Birth generated by hbm2java
 */
@Entity
@Table( name = "birth", catalog = "etatcivildb" )
public class Birth implements java.io.Serializable {

    private int           idbirth;
    private Transcription transcription;
    private Integer       abandoned;
    private Integer       twin;
    private String        flag;

    public Birth() {
    }

    public Birth( int idbirth ) {
        this.idbirth = idbirth;
    }

    public Birth( int idbirth, Transcription transcription, Integer abandoned, Integer twin, String flag ) {
        this.idbirth = idbirth;
        this.transcription = transcription;
        this.abandoned = abandoned;
        this.twin = twin;
        this.flag = flag;
    }

    @Id

    @Column( name = "IDBirth", unique = true, nullable = false )
    public int getIdbirth() {
        return this.idbirth;
    }

    public void setIdbirth( int idbirth ) {
        this.idbirth = idbirth;
    }

    @ManyToOne( fetch = FetchType.EAGER)
    @JoinColumn( name = "IDTranscription" )
    public Transcription getTranscription() {
        return this.transcription;
    }

    public void setTranscription( Transcription transcription ) {
        this.transcription = transcription;
    }

    @Column( name = "Abandoned" )
    public Integer getAbandoned() {
        return this.abandoned;
    }

    public void setAbandoned( Integer abandoned ) {
        this.abandoned = abandoned;
    }

    @Column( name = "Twin" )
    public Integer getTwin() {
        return this.twin;
    }

    public void setTwin( Integer twin ) {
        this.twin = twin;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

}
