package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table( name = "city", catalog = "etatcivildb" )
public class City implements java.io.Serializable {

    private int           idcity;
    private String        flag;
    private Set<District> districts = new HashSet<District>( 0 );

    public City() {
    }

    public City( int idcity ) {
        this.idcity = idcity;
    }

    public City( int idcity, String flag, Set<District> districts ) {
        this.idcity = idcity;
        this.flag = flag;
        this.districts = districts;
    }

    @Id

    @Column( name = "IDCity", unique = true, nullable = false )
    public int getIdcity() {
        return this.idcity;
    }

    public void setIdcity( int idcity ) {
        this.idcity = idcity;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "city" )
    public Set<District> getDistricts() {
        return this.districts;
    }

    public void setDistricts( Set<District> districts ) {
        this.districts = districts;
    }

}
