package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Controleact generated by hbm2java
 */
@Entity
@Table( name = "controleact", catalog = "etatcivildb" )
public class Controleact implements java.io.Serializable {

    private Integer idControleAct;
    private int     idUser;
    private int     idControleur;
    private Date    date;
    private int     status;
    private String  act;
    private int     idobjectDb;

    public Controleact() {
    }

    public Controleact( int idUser, int idControleur, Date date, int status, String act, int idobjectDb ) {
        this.idUser = idUser;
        this.idControleur = idControleur;
        this.date = date;
        this.status = status;
        this.act = act;
        this.idobjectDb = idobjectDb;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "idControleAct", unique = true, nullable = false )
    public Integer getIdControleAct() {
        return this.idControleAct;
    }

    public void setIdControleAct( Integer idControleAct ) {
        this.idControleAct = idControleAct;
    }

    @Column( name = "idUser", nullable = false )
    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser( int idUser ) {
        this.idUser = idUser;
    }

    @Column( name = "idControleur", nullable = false )
    public int getIdControleur() {
        return this.idControleur;
    }

    public void setIdControleur( int idControleur ) {
        this.idControleur = idControleur;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "date", nullable = false, length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "status", nullable = false )
    public int getStatus() {
        return this.status;
    }

    public void setStatus( int status ) {
        this.status = status;
    }

    @Column( name = "Act", nullable = false, length = 45 )
    public String getAct() {
        return this.act;
    }

    public void setAct( String act ) {
        this.act = act;
    }

    @Column( name = "IDObjectDB", nullable = false )
    public int getIdobjectDb() {
        return this.idobjectDb;
    }

    public void setIdobjectDb( int idobjectDb ) {
        this.idobjectDb = idobjectDb;
    }

}
