package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Death generated by hbm2java
 */
@Entity
@Table( name = "death", catalog = "etatcivildb" )
public class Death implements java.io.Serializable {

    private int     iddeath;
    private String  spouseAr;
    private String  spouseFr;
    private Integer married;
    private String  flag;

    public Death() {
    }

    public Death( int iddeath ) {
        this.iddeath = iddeath;
    }

    public Death( int iddeath, String spouseAr, String spouseFr, Integer married, String flag ) {
        this.iddeath = iddeath;
        this.spouseAr = spouseAr;
        this.spouseFr = spouseFr;
        this.married = married;
        this.flag = flag;
    }

    @Id

    @Column( name = "IDDeath", unique = true, nullable = false )
    public int getIddeath() {
        return this.iddeath;
    }

    public void setIddeath( int iddeath ) {
        this.iddeath = iddeath;
    }

    @Column( name = "SpouseAr" )
    public String getSpouseAr() {
        return this.spouseAr;
    }

    public void setSpouseAr( String spouseAr ) {
        this.spouseAr = spouseAr;
    }

    @Column( name = "SpouseFr" )
    public String getSpouseFr() {
        return this.spouseFr;
    }

    public void setSpouseFr( String spouseFr ) {
        this.spouseFr = spouseFr;
    }

    @Column( name = "Married" )
    public Integer getMarried() {
        return this.married;
    }

    public void setMarried( Integer married ) {
        this.married = married;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

}
