package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Declaration generated by hbm2java
 */
@Entity
@Table( name = "declaration", catalog = "etatcivildb" )
public class Declaration implements java.io.Serializable {

    private Integer  iddeclaration;
    private Integer  statementType;
    private Integer  dayGregorian;
    private Integer  monthGregorian;
    private Integer  yearGregorian;
    private Integer  dayHijri;
    private Integer  monthHijri;
    private Integer  yearHijri;
    private String   flag;
    private Set<Act> acts = new HashSet<Act>( 0 );

    public Declaration() {
    }

    public Declaration( Integer statementType, Integer dayGregorian, Integer monthGregorian, Integer yearGregorian,
            Integer dayHijri, Integer monthHijri, Integer yearHijri, String flag, Set<Act> acts ) {
        this.statementType = statementType;
        this.dayGregorian = dayGregorian;
        this.monthGregorian = monthGregorian;
        this.yearGregorian = yearGregorian;
        this.dayHijri = dayHijri;
        this.monthHijri = monthHijri;
        this.yearHijri = yearHijri;
        this.flag = flag;
        this.acts = acts;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDDeclaration", unique = true, nullable = false )
    public Integer getIddeclaration() {
        return this.iddeclaration;
    }

    public void setIddeclaration( Integer iddeclaration ) {
        this.iddeclaration = iddeclaration;
    }

    @Column( name = "StatementType" )
    public Integer getStatementType() {
        return this.statementType;
    }

    public void setStatementType( Integer statementType ) {
        this.statementType = statementType;
    }

    @Column( name = "DayGregorian" )
    public Integer getDayGregorian() {
        return this.dayGregorian;
    }

    public void setDayGregorian( Integer dayGregorian ) {
        this.dayGregorian = dayGregorian;
    }

    @Column( name = "MonthGregorian" )
    public Integer getMonthGregorian() {
        return this.monthGregorian;
    }

    public void setMonthGregorian( Integer monthGregorian ) {
        this.monthGregorian = monthGregorian;
    }

    @Column( name = "YearGregorian" )
    public Integer getYearGregorian() {
        return this.yearGregorian;
    }

    public void setYearGregorian( Integer yearGregorian ) {
        this.yearGregorian = yearGregorian;
    }

    @Column( name = "DayHijri" )
    public Integer getDayHijri() {
        return this.dayHijri;
    }

    public void setDayHijri( Integer dayHijri ) {
        this.dayHijri = dayHijri;
    }

    @Column( name = "MonthHijri" )
    public Integer getMonthHijri() {
        return this.monthHijri;
    }

    public void setMonthHijri( Integer monthHijri ) {
        this.monthHijri = monthHijri;
    }

    @Column( name = "YearHijri" )
    public Integer getYearHijri() {
        return this.yearHijri;
    }

    public void setYearHijri( Integer yearHijri ) {
        this.yearHijri = yearHijri;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "declaration" )
    public Set<Act> getActs() {
        return this.acts;
    }

    public void setActs( Set<Act> acts ) {
        this.acts = acts;
    }

}
