package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table( name = "district", catalog = "etatcivildb" )
public class District implements java.io.Serializable {

    private int        iddistrict;
    private City       city;
    private String     flag;
    private Set<Annex> annexes = new HashSet<Annex>( 0 );

    public District() {
    }

    public District( int iddistrict ) {
        this.iddistrict = iddistrict;
    }

    public District( int iddistrict, City city, String flag, Set<Annex> annexes ) {
        this.iddistrict = iddistrict;
        this.city = city;
        this.flag = flag;
        this.annexes = annexes;
    }

    @Id

    @Column( name = "IDDistrict", unique = true, nullable = false )
    public int getIddistrict() {
        return this.iddistrict;
    }

    public void setIddistrict( int iddistrict ) {
        this.iddistrict = iddistrict;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDCity" )
    public City getCity() {
        return this.city;
    }

    public void setCity( City city ) {
        this.city = city;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "district" )
    public Set<Annex> getAnnexes() {
        return this.annexes;
    }

    public void setAnnexes( Set<Annex> annexes ) {
        this.annexes = annexes;
    }

}
