package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Document generated by hbm2java
 */
@Entity
@Table( name = "document", catalog = "etatcivildb" )
public class Document implements java.io.Serializable {

    private Integer      iddocument;
    private Registertype registertype;
    private String       labelAr;
    private String       labelFr;
    private Integer      type;
    private String       flag;
    private Set<Print>   prints = new HashSet<Print>( 0 );

    public Document() {
    }

    public Document( Registertype registertype, String labelAr, String labelFr, Integer type, String flag,
            Set<Print> prints ) {
        this.registertype = registertype;
        this.labelAr = labelAr;
        this.labelFr = labelFr;
        this.type = type;
        this.flag = flag;
        this.prints = prints;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDDocument", unique = true, nullable = false )
    public Integer getIddocument() {
        return this.iddocument;
    }

    public void setIddocument( Integer iddocument ) {
        this.iddocument = iddocument;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDRegisterType" )
    public Registertype getRegistertype() {
        return this.registertype;
    }

    public void setRegistertype( Registertype registertype ) {
        this.registertype = registertype;
    }

    @Column( name = "LabelAr" )
    public String getLabelAr() {
        return this.labelAr;
    }

    public void setLabelAr( String labelAr ) {
        this.labelAr = labelAr;
    }

    @Column( name = "LabelFr" )
    public String getLabelFr() {
        return this.labelFr;
    }

    public void setLabelFr( String labelFr ) {
        this.labelFr = labelFr;
    }

    @Column( name = "Type" )
    public Integer getType() {
        return this.type;
    }

    public void setType( Integer type ) {
        this.type = type;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "document" )
    public Set<Print> getPrints() {
        return this.prints;
    }

    public void setPrints( Set<Print> prints ) {
        this.prints = prints;
    }

}
