package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Edition generated by hbm2java
 */
@Entity
@Table( name = "edition", catalog = "etatcivildb" )
public class Edition implements java.io.Serializable {

    private Integer            idedition;
    private String             executiveAr;
    private String             executiveFr;
    private Integer            dayGregorian;
    private Integer            monthGregorian;
    private Integer            yearGregorian;
    private Integer            dayHijri;
    private Integer            monthHijri;
    private Integer            yearHijri;
    private Integer            hour;
    private Integer            minute;
    private String             signedAr;
    private String             signedFr;
    private String             flag;
    private Set<Act>           acts           = new HashSet<Act>( 0 );
    private Set<Transcription> transcriptions = new HashSet<Transcription>( 0 );

    public Edition() {
    }

    public Edition( String executiveAr, String executiveFr, Integer dayGregorian, Integer monthGregorian,
            Integer yearGregorian, Integer dayHijri, Integer monthHijri, Integer yearHijri, Integer hour,
            Integer minute, String signedAr, String signedFr, String flag, Set<Act> acts,
            Set<Transcription> transcriptions ) {
        this.executiveAr = executiveAr;
        this.executiveFr = executiveFr;
        this.dayGregorian = dayGregorian;
        this.monthGregorian = monthGregorian;
        this.yearGregorian = yearGregorian;
        this.dayHijri = dayHijri;
        this.monthHijri = monthHijri;
        this.yearHijri = yearHijri;
        this.hour = hour;
        this.minute = minute;
        this.signedAr = signedAr;
        this.signedFr = signedFr;
        this.flag = flag;
        this.acts = acts;
        this.transcriptions = transcriptions;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDEdition", unique = true, nullable = false )
    public Integer getIdedition() {
        return this.idedition;
    }

    public void setIdedition( Integer idedition ) {
        this.idedition = idedition;
    }

    @Column( name = "ExecutiveAr" )
    public String getExecutiveAr() {
        return this.executiveAr;
    }

    public void setExecutiveAr( String executiveAr ) {
        this.executiveAr = executiveAr;
    }

    @Column( name = "ExecutiveFr" )
    public String getExecutiveFr() {
        return this.executiveFr;
    }

    public void setExecutiveFr( String executiveFr ) {
        this.executiveFr = executiveFr;
    }

    @Column( name = "DayGregorian" )
    public Integer getDayGregorian() {
        return this.dayGregorian;
    }

    public void setDayGregorian( Integer dayGregorian ) {
        this.dayGregorian = dayGregorian;
    }

    @Column( name = "MonthGregorian" )
    public Integer getMonthGregorian() {
        return this.monthGregorian;
    }

    public void setMonthGregorian( Integer monthGregorian ) {
        this.monthGregorian = monthGregorian;
    }

    @Column( name = "YearGregorian" )
    public Integer getYearGregorian() {
        return this.yearGregorian;
    }

    public void setYearGregorian( Integer yearGregorian ) {
        this.yearGregorian = yearGregorian;
    }

    @Column( name = "DayHijri" )
    public Integer getDayHijri() {
        return this.dayHijri;
    }

    public void setDayHijri( Integer dayHijri ) {
        this.dayHijri = dayHijri;
    }

    @Column( name = "MonthHijri" )
    public Integer getMonthHijri() {
        return this.monthHijri;
    }

    public void setMonthHijri( Integer monthHijri ) {
        this.monthHijri = monthHijri;
    }

    @Column( name = "YearHijri" )
    public Integer getYearHijri() {
        return this.yearHijri;
    }

    public void setYearHijri( Integer yearHijri ) {
        this.yearHijri = yearHijri;
    }

    @Column( name = "Hour" )
    public Integer getHour() {
        return this.hour;
    }

    public void setHour( Integer hour ) {
        this.hour = hour;
    }

    @Column( name = "Minute" )
    public Integer getMinute() {
        return this.minute;
    }

    public void setMinute( Integer minute ) {
        this.minute = minute;
    }

    @Column( name = "SignedAr" )
    public String getSignedAr() {
        return this.signedAr;
    }

    public void setSignedAr( String signedAr ) {
        this.signedAr = signedAr;
    }

    @Column( name = "SignedFr" )
    public String getSignedFr() {
        return this.signedFr;
    }

    public void setSignedFr( String signedFr ) {
        this.signedFr = signedFr;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "edition" )
    public Set<Act> getActs() {
        return this.acts;
    }

    public void setActs( Set<Act> acts ) {
        this.acts = acts;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "edition" )
    public Set<Transcription> getTranscriptions() {
        return this.transcriptions;
    }

    public void setTranscriptions( Set<Transcription> transcriptions ) {
        this.transcriptions = transcriptions;
    }

}
