package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jobcategory generated by hbm2java
 */
@Entity
@Table( name = "jobcategory", catalog = "etatcivildb" )
public class Jobcategory implements java.io.Serializable {

    private Integer     idjobCategory;
    private String      label;
    private String      flag;
    private Set<Person> persons = new HashSet<Person>( 0 );

    public Jobcategory() {
    }

    public Jobcategory( String label, String flag, Set<Person> persons ) {
        this.label = label;
        this.flag = flag;
        this.persons = persons;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDJobCategory", unique = true, nullable = false )
    public Integer getIdjobCategory() {
        return this.idjobCategory;
    }

    public void setIdjobCategory( Integer idjobCategory ) {
        this.idjobCategory = idjobCategory;
    }

    @Column( name = "Label" )
    public String getLabel() {
        return this.label;
    }

    public void setLabel( String label ) {
        this.label = label;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "jobcategory" )
    public Set<Person> getPersons() {
        return this.persons;
    }

    public void setPersons( Set<Person> persons ) {
        this.persons = persons;
    }

}
