package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mention generated by hbm2java
 */
@Entity
@Table( name = "mention", catalog = "etatcivildb" )
public class Mention implements java.io.Serializable {

    private int                   idmention;
    private Act                   act;
    private Mentiontype           mentiontype;
    private Integer               statusMention;
    private String                displayText;
    private String                officerAr;
    private String                officerFr;
    private Integer               dayGregorianEdition;
    private Integer               monthGregorianEdition;
    private Integer               yearGregorianEdition;
    private Integer               dayHijriEdition;
    private Integer               monthHijriEdition;
    private Integer               yearHijriEdition;
    private String                displaySummary;
    private String                flag;
    private Set<Modifiedproperty> modifiedproperties = new HashSet<Modifiedproperty>( 0 );

    public Mention() {
    }

    public Mention( int idmention ) {
        this.idmention = idmention;
    }

    public Mention( int idmention, Act act, Mentiontype mentiontype, Integer statusMention, String displayText,
            String officerAr, String officerFr, Integer dayGregorianEdition, Integer monthGregorianEdition,
            Integer yearGregorianEdition, Integer dayHijriEdition, Integer monthHijriEdition, Integer yearHijriEdition,
            String displaySummary, String flag, Set<Modifiedproperty> modifiedproperties ) {
        this.idmention = idmention;
        this.act = act;
        this.mentiontype = mentiontype;
        this.statusMention = statusMention;
        this.displayText = displayText;
        this.officerAr = officerAr;
        this.officerFr = officerFr;
        this.dayGregorianEdition = dayGregorianEdition;
        this.monthGregorianEdition = monthGregorianEdition;
        this.yearGregorianEdition = yearGregorianEdition;
        this.dayHijriEdition = dayHijriEdition;
        this.monthHijriEdition = monthHijriEdition;
        this.yearHijriEdition = yearHijriEdition;
        this.displaySummary = displaySummary;
        this.flag = flag;
        this.modifiedproperties = modifiedproperties;
    }

    @Id

    @Column( name = "IDMention", unique = true, nullable = false )
    public int getIdmention() {
        return this.idmention;
    }

    public void setIdmention( int idmention ) {
        this.idmention = idmention;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDAct" )
    public Act getAct() {
        return this.act;
    }

    public void setAct( Act act ) {
        this.act = act;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDMentionType" )
    public Mentiontype getMentiontype() {
        return this.mentiontype;
    }

    public void setMentiontype( Mentiontype mentiontype ) {
        this.mentiontype = mentiontype;
    }

    @Column( name = "StatusMention" )
    public Integer getStatusMention() {
        return this.statusMention;
    }

    public void setStatusMention( Integer statusMention ) {
        this.statusMention = statusMention;
    }

    @Column( name = "DisplayText", length = 65535 )
    public String getDisplayText() {
        return this.displayText;
    }

    public void setDisplayText( String displayText ) {
        this.displayText = displayText;
    }

    @Column( name = "OfficerAr" )
    public String getOfficerAr() {
        return this.officerAr;
    }

    public void setOfficerAr( String officerAr ) {
        this.officerAr = officerAr;
    }

    @Column( name = "OfficerFr" )
    public String getOfficerFr() {
        return this.officerFr;
    }

    public void setOfficerFr( String officerFr ) {
        this.officerFr = officerFr;
    }

    @Column( name = "DayGregorianEdition" )
    public Integer getDayGregorianEdition() {
        return this.dayGregorianEdition;
    }

    public void setDayGregorianEdition( Integer dayGregorianEdition ) {
        this.dayGregorianEdition = dayGregorianEdition;
    }

    @Column( name = "MonthGregorianEdition" )
    public Integer getMonthGregorianEdition() {
        return this.monthGregorianEdition;
    }

    public void setMonthGregorianEdition( Integer monthGregorianEdition ) {
        this.monthGregorianEdition = monthGregorianEdition;
    }

    @Column( name = "YearGregorianEdition" )
    public Integer getYearGregorianEdition() {
        return this.yearGregorianEdition;
    }

    public void setYearGregorianEdition( Integer yearGregorianEdition ) {
        this.yearGregorianEdition = yearGregorianEdition;
    }

    @Column( name = "DayHijriEdition" )
    public Integer getDayHijriEdition() {
        return this.dayHijriEdition;
    }

    public void setDayHijriEdition( Integer dayHijriEdition ) {
        this.dayHijriEdition = dayHijriEdition;
    }

    @Column( name = "MonthHijriEdition" )
    public Integer getMonthHijriEdition() {
        return this.monthHijriEdition;
    }

    public void setMonthHijriEdition( Integer monthHijriEdition ) {
        this.monthHijriEdition = monthHijriEdition;
    }

    @Column( name = "YearHijriEdition" )
    public Integer getYearHijriEdition() {
        return this.yearHijriEdition;
    }

    public void setYearHijriEdition( Integer yearHijriEdition ) {
        this.yearHijriEdition = yearHijriEdition;
    }

    @Column( name = "DisplaySummary", length = 65535 )
    public String getDisplaySummary() {
        return this.displaySummary;
    }

    public void setDisplaySummary( String displaySummary ) {
        this.displaySummary = displaySummary;
    }

    @Column( name = "Flag", length = 45 )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "mention" )
    public Set<Modifiedproperty> getModifiedproperties() {
        return this.modifiedproperties;
    }

    public void setModifiedproperties( Set<Modifiedproperty> modifiedproperties ) {
        this.modifiedproperties = modifiedproperties;
    }

}
