package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mentiontype generated by hbm2java
 */
@Entity
@Table( name = "mentiontype", catalog = "etatcivildb" )
public class Mentiontype implements java.io.Serializable {

    private Integer      idmentionType;
    private String       type;
    private Integer      mentionEffect;
    private String       flag;
    private Set<Mention> mentions = new HashSet<Mention>( 0 );

    public Mentiontype() {
    }

    public Mentiontype( String type, Integer mentionEffect, String flag, Set<Mention> mentions ) {
        this.type = type;
        this.mentionEffect = mentionEffect;
        this.flag = flag;
        this.mentions = mentions;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDMentionType", unique = true, nullable = false )
    public Integer getIdmentionType() {
        return this.idmentionType;
    }

    public void setIdmentionType( Integer idmentionType ) {
        this.idmentionType = idmentionType;
    }

    @Column( name = "Type" )
    public String getType() {
        return this.type;
    }

    public void setType( String type ) {
        this.type = type;
    }

    @Column( name = "MentionEffect" )
    public Integer getMentionEffect() {
        return this.mentionEffect;
    }

    public void setMentionEffect( Integer mentionEffect ) {
        this.mentionEffect = mentionEffect;
    }

    @Column( name = "Flag", length = 45 )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "mentiontype" )
    public Set<Mention> getMentions() {
        return this.mentions;
    }

    public void setMentions( Set<Mention> mentions ) {
        this.mentions = mentions;
    }

}
