package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Objectdb generated by hbm2java
 */
@Entity
@Table( name = "objectdb", catalog = "etatcivildb" )
public class Objectdb implements java.io.Serializable {

    private Integer           idobjectDb;
    private String            flag;
    private Set<Objectdbuser> objectdbusers = new HashSet<Objectdbuser>( 0 );

    public Objectdb() {
    }

    public Objectdb( String flag, Set<Objectdbuser> objectdbusers ) {
        this.flag = flag;
        this.objectdbusers = objectdbusers;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDObjectDB", unique = true, nullable = false )
    public Integer getIdobjectDb() {
        return this.idobjectDb;
    }

    public void setIdobjectDb( Integer idobjectDb ) {
        this.idobjectDb = idobjectDb;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "objectdb" )
    public Set<Objectdbuser> getObjectdbusers() {
        return this.objectdbusers;
    }

    public void setObjectdbusers( Set<Objectdbuser> objectdbusers ) {
        this.objectdbusers = objectdbusers;
    }

}
