package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjectdbuserId generated by hbm2java
 */
@Embeddable
public class ObjectdbuserId implements java.io.Serializable {

    private int  idobjectDb;
    private int  iduser;
    private Date dateAction;

    public ObjectdbuserId() {
    }

    public ObjectdbuserId( int idobjectDb, int iduser, Date dateAction ) {
        this.idobjectDb = idobjectDb;
        this.iduser = iduser;
        this.dateAction = dateAction;
    }

    @Column( name = "IDObjectDB", nullable = false )
    public int getIdobjectDb() {
        return this.idobjectDb;
    }

    public void setIdobjectDb( int idobjectDb ) {
        this.idobjectDb = idobjectDb;
    }

    @Column( name = "IDUser", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "DateAction", nullable = false, length = 19 )
    public Date getDateAction() {
        return this.dateAction;
    }

    public void setDateAction( Date dateAction ) {
        this.dateAction = dateAction;
    }

    public boolean equals( Object other ) {
        if ( ( this == other ) )
            return true;
        if ( ( other == null ) )
            return false;
        if ( !( other instanceof ObjectdbuserId ) )
            return false;
        ObjectdbuserId castOther = (ObjectdbuserId) other;

        return ( this.getIdobjectDb() == castOther.getIdobjectDb() )
                && ( this.getIduser() == castOther.getIduser() )
                && ( ( this.getDateAction() == castOther.getDateAction() )
                        || ( this.getDateAction() != null && castOther.getDateAction() != null
                                && this.getDateAction().equals( castOther.getDateAction() ) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdobjectDb();
        result = 37 * result + this.getIduser();
        result = 37 * result + ( getDateAction() == null ? 0 : this.getDateAction().hashCode() );
        return result;
    }

}
