package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Objectdbuser generated by hbm2java
 */
@Entity
@Table( name = "objectdbuser", catalog = "etatcivildb" )
public class Objectdbuser implements java.io.Serializable {

    private ObjectdbuserId id;
    private Objectdb       objectdb;
    private User           user;
    private Integer        action;
    private String         flag;

    public Objectdbuser() {
    }

    public Objectdbuser( ObjectdbuserId id, Objectdb objectdb, User user ) {
        this.id = id;
        this.objectdb = objectdb;
        this.user = user;
    }

    public Objectdbuser( ObjectdbuserId id, Objectdb objectdb, User user, Integer action, String flag ) {
        this.id = id;
        this.objectdb = objectdb;
        this.user = user;
        this.action = action;
        this.flag = flag;
    }

    @EmbeddedId

    @AttributeOverrides( {
            @AttributeOverride( name = "idobjectDb", column = @Column( name = "IDObjectDB", nullable = false ) ),
            @AttributeOverride( name = "iduser", column = @Column( name = "IDUser", nullable = false ) ),
            @AttributeOverride( name = "dateAction", column = @Column( name = "DateAction", nullable = false, length = 19 ) ) } )
    public ObjectdbuserId getId() {
        return this.id;
    }

    public void setId( ObjectdbuserId id ) {
        this.id = id;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDObjectDB", nullable = false, insertable = false, updatable = false )
    public Objectdb getObjectdb() {
        return this.objectdb;
    }

    public void setObjectdb( Objectdb objectdb ) {
        this.objectdb = objectdb;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDUser", nullable = false, insertable = false, updatable = false )
    public User getUser() {
        return this.user;
    }

    public void setUser( User user ) {
        this.user = user;
    }

    @Column( name = "Action" )
    public Integer getAction() {
        return this.action;
    }

    public void setAction( Integer action ) {
        this.action = action;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

}
