package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Persondeclaration generated by hbm2java
 */
@Entity
@Table( name = "persondeclaration", catalog = "etatcivildb" )
public class Persondeclaration implements java.io.Serializable {

    private int     idpersonDeclaration;
    private String  firstNameAr;
    private String  firstNameFr;
    private String  lastNameAr;
    private String  lastNameFr;
    private String  number;
    private String  folderNumber;
    private String  adressAr;
    private String  adressFr;
    private Integer age;
    private String  nationalityAr;
    private String  nationalityFr;
    private String  jobAr;
    private String  jobFr;
    private String  relationShipAr;
    private String  relationShipFr;
    private String  flag;

    public Persondeclaration() {
    }

    public Persondeclaration( int idpersonDeclaration, String folderNumber ) {
        this.idpersonDeclaration = idpersonDeclaration;
        this.folderNumber = folderNumber;
    }

    public Persondeclaration( int idpersonDeclaration, String firstNameAr, String firstNameFr, String lastNameAr,
            String lastNameFr, String number, String folderNumber, String adressAr, String adressFr, Integer age,
            String nationalityAr, String nationalityFr, String jobAr, String jobFr, String relationShipAr,
            String relationShipFr, String flag ) {
        this.idpersonDeclaration = idpersonDeclaration;
        this.firstNameAr = firstNameAr;
        this.firstNameFr = firstNameFr;
        this.lastNameAr = lastNameAr;
        this.lastNameFr = lastNameFr;
        this.number = number;
        this.folderNumber = folderNumber;
        this.adressAr = adressAr;
        this.adressFr = adressFr;
        this.age = age;
        this.nationalityAr = nationalityAr;
        this.nationalityFr = nationalityFr;
        this.jobAr = jobAr;
        this.jobFr = jobFr;
        this.relationShipAr = relationShipAr;
        this.relationShipFr = relationShipFr;
        this.flag = flag;
    }

    @Id

    @Column( name = "IDPersonDeclaration", unique = true, nullable = false )
    public int getIdpersonDeclaration() {
        return this.idpersonDeclaration;
    }

    public void setIdpersonDeclaration( int idpersonDeclaration ) {
        this.idpersonDeclaration = idpersonDeclaration;
    }

    @Column( name = "FirstNameAr" )
    public String getFirstNameAr() {
        return this.firstNameAr;
    }

    public void setFirstNameAr( String firstNameAr ) {
        this.firstNameAr = firstNameAr;
    }

    @Column( name = "FirstNameFr" )
    public String getFirstNameFr() {
        return this.firstNameFr;
    }

    public void setFirstNameFr( String firstNameFr ) {
        this.firstNameFr = firstNameFr;
    }

    @Column( name = "LastNameAr" )
    public String getLastNameAr() {
        return this.lastNameAr;
    }

    public void setLastNameAr( String lastNameAr ) {
        this.lastNameAr = lastNameAr;
    }

    @Column( name = "LastNameFr" )
    public String getLastNameFr() {
        return this.lastNameFr;
    }

    public void setLastNameFr( String lastNameFr ) {
        this.lastNameFr = lastNameFr;
    }

    @Column( name = "Number" )
    public String getNumber() {
        return this.number;
    }

    public void setNumber( String number ) {
        this.number = number;
    }

    @Column( name = "FolderNumber", nullable = false, length = 45 )
    public String getFolderNumber() {
        return this.folderNumber;
    }

    public void setFolderNumber( String folderNumber ) {
        this.folderNumber = folderNumber;
    }

    @Column( name = "AdressAr" )
    public String getAdressAr() {
        return this.adressAr;
    }

    public void setAdressAr( String adressAr ) {
        this.adressAr = adressAr;
    }

    @Column( name = "AdressFr" )
    public String getAdressFr() {
        return this.adressFr;
    }

    public void setAdressFr( String adressFr ) {
        this.adressFr = adressFr;
    }

    @Column( name = "Age" )
    public Integer getAge() {
        return this.age;
    }

    public void setAge( Integer age ) {
        this.age = age;
    }

    @Column( name = "NationalityAr" )
    public String getNationalityAr() {
        return this.nationalityAr;
    }

    public void setNationalityAr( String nationalityAr ) {
        this.nationalityAr = nationalityAr;
    }

    @Column( name = "NationalityFr" )
    public String getNationalityFr() {
        return this.nationalityFr;
    }

    public void setNationalityFr( String nationalityFr ) {
        this.nationalityFr = nationalityFr;
    }

    @Column( name = "JobAr" )
    public String getJobAr() {
        return this.jobAr;
    }

    public void setJobAr( String jobAr ) {
        this.jobAr = jobAr;
    }

    @Column( name = "JobFr" )
    public String getJobFr() {
        return this.jobFr;
    }

    public void setJobFr( String jobFr ) {
        this.jobFr = jobFr;
    }

    @Column( name = "RelationShipAr" )
    public String getRelationShipAr() {
        return this.relationShipAr;
    }

    public void setRelationShipAr( String relationShipAr ) {
        this.relationShipAr = relationShipAr;
    }

    @Column( name = "RelationShipFr" )
    public String getRelationShipFr() {
        return this.relationShipFr;
    }

    public void setRelationShipFr( String relationShipFr ) {
        this.relationShipFr = relationShipFr;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

}
