package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Register generated by hbm2java
 */
@Entity
@Table( name = "register", catalog = "etatcivildb" )
public class Register implements java.io.Serializable {

    private int               idregister;
    private Annex             annex;
    private Registerclass     registerclass;
    private Registernumbering registernumbering;
    private Registertype      registertype;
    private Integer           year;
    private Integer           number;
    private Integer           pagesCount;
    private String            editorAr;
    private String            editorFr;
    private Integer           dayGregorian;
    private Integer           monthGregorian;
    private Integer           yearGregorian;
    private Integer           dayHijri;
    private Integer           monthHijri;
    private Integer           yearHijri;
    private Integer           status;
    private String            flag;
    private Set<Act>          acts = new HashSet<Act>( 0 );

    public Register() {
    }

    public Register( int idregister ) {
        this.idregister = idregister;
    }

    public Register( int idregister, Annex annex, Registerclass registerclass, Registernumbering registernumbering,
            Registertype registertype, Integer year, Integer number, Integer pagesCount, String editorAr,
            String editorFr, Integer dayGregorian, Integer monthGregorian, Integer yearGregorian, Integer dayHijri,
            Integer monthHijri, Integer yearHijri, Integer status, String flag, Set<Act> acts ) {
        this.idregister = idregister;
        this.annex = annex;
        this.registerclass = registerclass;
        this.registernumbering = registernumbering;
        this.registertype = registertype;
        this.year = year;
        this.number = number;
        this.pagesCount = pagesCount;
        this.editorAr = editorAr;
        this.editorFr = editorFr;
        this.dayGregorian = dayGregorian;
        this.monthGregorian = monthGregorian;
        this.yearGregorian = yearGregorian;
        this.dayHijri = dayHijri;
        this.monthHijri = monthHijri;
        this.yearHijri = yearHijri;
        this.status = status;
        this.flag = flag;
        this.acts = acts;
    }

    @Id

    @Column( name = "IDRegister", unique = true, nullable = false )
    public int getIdregister() {
        return this.idregister;
    }

    public void setIdregister( int idregister ) {
        this.idregister = idregister;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDAnnex" )
    public Annex getAnnex() {
        return this.annex;
    }

    public void setAnnex( Annex annex ) {
        this.annex = annex;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDRegisterClass" )
    public Registerclass getRegisterclass() {
        return this.registerclass;
    }

    public void setRegisterclass( Registerclass registerclass ) {
        this.registerclass = registerclass;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDRegisterNumbering" )
    public Registernumbering getRegisternumbering() {
        return this.registernumbering;
    }

    public void setRegisternumbering( Registernumbering registernumbering ) {
        this.registernumbering = registernumbering;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDRegisterType" )
    public Registertype getRegistertype() {
        return this.registertype;
    }

    public void setRegistertype( Registertype registertype ) {
        this.registertype = registertype;
    }

    @Column( name = "Year" )
    public Integer getYear() {
        return this.year;
    }

    public void setYear( Integer year ) {
        this.year = year;
    }

    @Column( name = "Number" )
    public Integer getNumber() {
        return this.number;
    }

    public void setNumber( Integer number ) {
        this.number = number;
    }

    @Column( name = "PagesCount" )
    public Integer getPagesCount() {
        return this.pagesCount;
    }

    public void setPagesCount( Integer pagesCount ) {
        this.pagesCount = pagesCount;
    }

    @Column( name = "EditorAr" )
    public String getEditorAr() {
        return this.editorAr;
    }

    public void setEditorAr( String editorAr ) {
        this.editorAr = editorAr;
    }

    @Column( name = "EditorFr" )
    public String getEditorFr() {
        return this.editorFr;
    }

    public void setEditorFr( String editorFr ) {
        this.editorFr = editorFr;
    }

    @Column( name = "DayGregorian" )
    public Integer getDayGregorian() {
        return this.dayGregorian;
    }

    public void setDayGregorian( Integer dayGregorian ) {
        this.dayGregorian = dayGregorian;
    }

    @Column( name = "MonthGregorian" )
    public Integer getMonthGregorian() {
        return this.monthGregorian;
    }

    public void setMonthGregorian( Integer monthGregorian ) {
        this.monthGregorian = monthGregorian;
    }

    @Column( name = "YearGregorian" )
    public Integer getYearGregorian() {
        return this.yearGregorian;
    }

    public void setYearGregorian( Integer yearGregorian ) {
        this.yearGregorian = yearGregorian;
    }

    @Column( name = "DayHijri" )
    public Integer getDayHijri() {
        return this.dayHijri;
    }

    public void setDayHijri( Integer dayHijri ) {
        this.dayHijri = dayHijri;
    }

    @Column( name = "MonthHijri" )
    public Integer getMonthHijri() {
        return this.monthHijri;
    }

    public void setMonthHijri( Integer monthHijri ) {
        this.monthHijri = monthHijri;
    }

    @Column( name = "YearHijri" )
    public Integer getYearHijri() {
        return this.yearHijri;
    }

    public void setYearHijri( Integer yearHijri ) {
        this.yearHijri = yearHijri;
    }

    @Column( name = "Status" )
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus( Integer status ) {
        this.status = status;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "register" )
    public Set<Act> getActs() {
        return this.acts;
    }

    public void setActs( Set<Act> acts ) {
        this.acts = acts;
    }

    @Override
    public String toString() {
        return "Register [idregister=" + idregister + ", annex=" + annex.getIdannex() + ", registerclass="
                + registerclass.getClassFr()
                + ", registernumbering=" + registernumbering.getEnumeration() + ", registertype="
                + registertype.getLabelFr() + ", year=" + year
                + ", number=" + number + ", pagesCount=" + pagesCount + ", editorAr=" + editorAr + ", editorFr="
                + editorFr + ", dayGregorian=" + dayGregorian + ", monthGregorian=" + monthGregorian
                + ", yearGregorian=" + yearGregorian + ", dayHijri=" + dayHijri + ", monthHijri=" + monthHijri
                + ", yearHijri=" + yearHijri + ", status=" + status + ", flag=" + flag + ", acts=" + acts + "]";
    }

}
