package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Registernumbering generated by hbm2java
 */
@Entity
@Table( name = "registernumbering", catalog = "etatcivildb" )
public class Registernumbering implements java.io.Serializable {

    private Integer       idregisterNumbering;
    private String        enumeration;
    private String        flag;
    private Set<Register> registers = new HashSet<Register>( 0 );

    public Registernumbering() {
    }

    public Registernumbering( String enumeration, String flag, Set<Register> registers ) {
        this.enumeration = enumeration;
        this.flag = flag;
        this.registers = registers;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDRegisterNumbering", unique = true, nullable = false )
    public Integer getIdregisterNumbering() {
        return this.idregisterNumbering;
    }

    public void setIdregisterNumbering( Integer idregisterNumbering ) {
        this.idregisterNumbering = idregisterNumbering;
    }

    @Column( name = "Enumeration" )
    public String getEnumeration() {
        return this.enumeration;
    }

    public void setEnumeration( String enumeration ) {
        this.enumeration = enumeration;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "registernumbering" )
    public Set<Register> getRegisters() {
        return this.registers;
    }

    public void setRegisters( Set<Register> registers ) {
        this.registers = registers;
    }

}
