package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Registertype generated by hbm2java
 */
@Entity
@Table( name = "registertype", catalog = "etatcivildb" )
public class Registertype implements java.io.Serializable {

    private Integer       idregisterType;
    private String        labelAr;
    private String        labelFr;
    private String        flag;
    private Set<Document> documents = new HashSet<Document>( 0 );
    private Set<Register> registers = new HashSet<Register>( 0 );

    public Registertype() {
    }

    public Registertype( String labelAr, String labelFr, String flag, Set<Document> documents,
            Set<Register> registers ) {
        this.labelAr = labelAr;
        this.labelFr = labelFr;
        this.flag = flag;
        this.documents = documents;
        this.registers = registers;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDRegisterType", unique = true, nullable = false )
    public Integer getIdregisterType() {
        return this.idregisterType;
    }

    public void setIdregisterType( Integer idregisterType ) {
        this.idregisterType = idregisterType;
    }

    @Column( name = "LabelAr" )
    public String getLabelAr() {
        return this.labelAr;
    }

    public void setLabelAr( String labelAr ) {
        this.labelAr = labelAr;
    }

    @Column( name = "LabelFr" )
    public String getLabelFr() {
        return this.labelFr;
    }

    public void setLabelFr( String labelFr ) {
        this.labelFr = labelFr;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "registertype" )
    public Set<Document> getDocuments() {
        return this.documents;
    }

    public void setDocuments( Set<Document> documents ) {
        this.documents = documents;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "registertype" )
    public Set<Register> getRegisters() {
        return this.registers;
    }

    public void setRegisters( Set<Register> registers ) {
        this.registers = registers;
    }

}
