package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Registerclass generated by hbm2java
 */
@Entity
@Table( name = "registerclass", catalog = "etatcivildb" )
public class Registerclass implements java.io.Serializable {

    private Integer       idregisterClass;
    private String        classAr;
    private String        classFr;
    private String        flag;
    private Set<Register> registers = new HashSet<Register>( 0 );

    public Registerclass() {
    }

    public Registerclass( String classAr, String classFr, String flag, Set<Register> registers ) {
        this.classAr = classAr;
        this.classFr = classFr;
        this.flag = flag;
        this.registers = registers;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDRegisterClass", unique = true, nullable = false )
    public Integer getIdregisterClass() {
        return this.idregisterClass;
    }

    public void setIdregisterClass( Integer idregisterClass ) {
        this.idregisterClass = idregisterClass;
    }

    @Column( name = "ClassAr" )
    public String getClassAr() {
        return this.classAr;
    }

    public void setClassAr( String classAr ) {
        this.classAr = classAr;
    }

    @Column( name = "ClassFr" )
    public String getClassFr() {
        return this.classFr;
    }

    public void setClassFr( String classFr ) {
        this.classFr = classFr;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "registerclass" )
    public Set<Register> getRegisters() {
        return this.registers;
    }

    public void setRegisters( Set<Register> registers ) {
        this.registers = registers;
    }

}
