package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Resident generated by hbm2java
 */
@Entity
@Table( name = "resident", catalog = "etatcivildb" )
public class Resident implements java.io.Serializable {

    private int     idresident;
    private Integer birthAct;
    private String  communBirthAr;
    private String  communBirthFr;
    private Integer year;
    private Integer civilStatusNumber;
    private Integer actDelivredDayGregorian;
    private Integer actDelivredMonthGregorian;
    private Integer actDelivredYearGregorian;
    private Integer actDelivredDayHijri;
    private Integer actDelivredMonthHijri;
    private Integer actDelivredYearHijri;
    private String  flag;

    public Resident() {
    }

    public Resident( int idresident ) {
        this.idresident = idresident;
    }

    public Resident( int idresident, Integer birthAct, String communBirthAr, String communBirthFr, Integer year,
            Integer civilStatusNumber, Integer actDelivredDayGregorian, Integer actDelivredMonthGregorian,
            Integer actDelivredYearGregorian, Integer actDelivredDayHijri, Integer actDelivredMonthHijri,
            Integer actDelivredYearHijri, String flag ) {
        this.idresident = idresident;
        this.birthAct = birthAct;
        this.communBirthAr = communBirthAr;
        this.communBirthFr = communBirthFr;
        this.year = year;
        this.civilStatusNumber = civilStatusNumber;
        this.actDelivredDayGregorian = actDelivredDayGregorian;
        this.actDelivredMonthGregorian = actDelivredMonthGregorian;
        this.actDelivredYearGregorian = actDelivredYearGregorian;
        this.actDelivredDayHijri = actDelivredDayHijri;
        this.actDelivredMonthHijri = actDelivredMonthHijri;
        this.actDelivredYearHijri = actDelivredYearHijri;
        this.flag = flag;
    }

    @Id

    @Column( name = "IDResident", unique = true, nullable = false )
    public int getIdresident() {
        return this.idresident;
    }

    public void setIdresident( int idresident ) {
        this.idresident = idresident;
    }

    @Column( name = "BirthAct" )
    public Integer getBirthAct() {
        return this.birthAct;
    }

    public void setBirthAct( Integer birthAct ) {
        this.birthAct = birthAct;
    }

    @Column( name = "CommunBirthAr" )
    public String getCommunBirthAr() {
        return this.communBirthAr;
    }

    public void setCommunBirthAr( String communBirthAr ) {
        this.communBirthAr = communBirthAr;
    }

    @Column( name = "CommunBirthFr" )
    public String getCommunBirthFr() {
        return this.communBirthFr;
    }

    public void setCommunBirthFr( String communBirthFr ) {
        this.communBirthFr = communBirthFr;
    }

    @Column( name = "Year" )
    public Integer getYear() {
        return this.year;
    }

    public void setYear( Integer year ) {
        this.year = year;
    }

    @Column( name = "CivilStatusNumber" )
    public Integer getCivilStatusNumber() {
        return this.civilStatusNumber;
    }

    public void setCivilStatusNumber( Integer civilStatusNumber ) {
        this.civilStatusNumber = civilStatusNumber;
    }

    @Column( name = "ActDelivredDayGregorian" )
    public Integer getActDelivredDayGregorian() {
        return this.actDelivredDayGregorian;
    }

    public void setActDelivredDayGregorian( Integer actDelivredDayGregorian ) {
        this.actDelivredDayGregorian = actDelivredDayGregorian;
    }

    @Column( name = "ActDelivredMonthGregorian" )
    public Integer getActDelivredMonthGregorian() {
        return this.actDelivredMonthGregorian;
    }

    public void setActDelivredMonthGregorian( Integer actDelivredMonthGregorian ) {
        this.actDelivredMonthGregorian = actDelivredMonthGregorian;
    }

    @Column( name = "ActDelivredYearGregorian" )
    public Integer getActDelivredYearGregorian() {
        return this.actDelivredYearGregorian;
    }

    public void setActDelivredYearGregorian( Integer actDelivredYearGregorian ) {
        this.actDelivredYearGregorian = actDelivredYearGregorian;
    }

    @Column( name = "ActDelivredDayHijri" )
    public Integer getActDelivredDayHijri() {
        return this.actDelivredDayHijri;
    }

    public void setActDelivredDayHijri( Integer actDelivredDayHijri ) {
        this.actDelivredDayHijri = actDelivredDayHijri;
    }

    @Column( name = "ActDelivredMonthHijri" )
    public Integer getActDelivredMonthHijri() {
        return this.actDelivredMonthHijri;
    }

    public void setActDelivredMonthHijri( Integer actDelivredMonthHijri ) {
        this.actDelivredMonthHijri = actDelivredMonthHijri;
    }

    @Column( name = "ActDelivredYearHijri" )
    public Integer getActDelivredYearHijri() {
        return this.actDelivredYearHijri;
    }

    public void setActDelivredYearHijri( Integer actDelivredYearHijri ) {
        this.actDelivredYearHijri = actDelivredYearHijri;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

}
