package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Translateexecutive generated by hbm2java
 */
@Entity
@Table( name = "translateexecutive", catalog = "etatcivildb" )
public class Translateexecutive implements java.io.Serializable {

    private String executiveAr;
    private String executiveFr;

    public Translateexecutive() {
    }

    public Translateexecutive( String executiveAr ) {
        this.executiveAr = executiveAr;
    }

    public Translateexecutive( String executiveAr, String executiveFr ) {
        this.executiveAr = executiveAr;
        this.executiveFr = executiveFr;
    }

    @Id

    @Column( name = "ExecutiveAr", unique = true, nullable = false, length = 145 )
    public String getExecutiveAr() {
        return this.executiveAr;
    }

    public void setExecutiveAr( String executiveAr ) {
        this.executiveAr = executiveAr;
    }

    @Column( name = "ExecutiveFr", length = 145 )
    public String getExecutiveFr() {
        return this.executiveFr;
    }

    public void setExecutiveFr( String executiveFr ) {
        this.executiveFr = executiveFr;
    }

}
