package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Transcription generated by hbm2java
 */
@Entity
@Table( name = "transcription", catalog = "etatcivildb" )
public class Transcription implements java.io.Serializable {

    private Integer    idtranscription;
    private Edition    edition;
    private Integer    originNumber;
    private String     envoyAr;
    private String     envoyFr;
    private String     originAr;
    private String     originFr;
    private Integer    dayDemandGregorian;
    private Integer    monthDemandGregorian;
    private Integer    yearDemandGregorian;
    private Integer    dayDemandHijri;
    private Integer    monthDemandHijri;
    private Integer    yearDemandHijri;
    private String     flag;
    private Set<Birth> births = new HashSet<Birth>( 0 );

    public Transcription() {
    }

    public Transcription( Edition edition, Integer originNumber, String envoyAr, String envoyFr, String originAr,
            String originFr, Integer dayDemandGregorian, Integer monthDemandGregorian, Integer yearDemandGregorian,
            Integer dayDemandHijri, Integer monthDemandHijri, Integer yearDemandHijri, String flag,
            Set<Birth> births ) {
        this.edition = edition;
        this.originNumber = originNumber;
        this.envoyAr = envoyAr;
        this.envoyFr = envoyFr;
        this.originAr = originAr;
        this.originFr = originFr;
        this.dayDemandGregorian = dayDemandGregorian;
        this.monthDemandGregorian = monthDemandGregorian;
        this.yearDemandGregorian = yearDemandGregorian;
        this.dayDemandHijri = dayDemandHijri;
        this.monthDemandHijri = monthDemandHijri;
        this.yearDemandHijri = yearDemandHijri;
        this.flag = flag;
        this.births = births;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDTranscription", unique = true, nullable = false )
    public Integer getIdtranscription() {
        return this.idtranscription;
    }

    public void setIdtranscription( Integer idtranscription ) {
        this.idtranscription = idtranscription;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDEdition" )
    public Edition getEdition() {
        return this.edition;
    }

    public void setEdition( Edition edition ) {
        this.edition = edition;
    }

    @Column( name = "OriginNumber" )
    public Integer getOriginNumber() {
        return this.originNumber;
    }

    public void setOriginNumber( Integer originNumber ) {
        this.originNumber = originNumber;
    }

    @Column( name = "EnvoyAr" )
    public String getEnvoyAr() {
        return this.envoyAr;
    }

    public void setEnvoyAr( String envoyAr ) {
        this.envoyAr = envoyAr;
    }

    @Column( name = "EnvoyFr" )
    public String getEnvoyFr() {
        return this.envoyFr;
    }

    public void setEnvoyFr( String envoyFr ) {
        this.envoyFr = envoyFr;
    }

    @Column( name = "OriginAr" )
    public String getOriginAr() {
        return this.originAr;
    }

    public void setOriginAr( String originAr ) {
        this.originAr = originAr;
    }

    @Column( name = "OriginFr" )
    public String getOriginFr() {
        return this.originFr;
    }

    public void setOriginFr( String originFr ) {
        this.originFr = originFr;
    }

    @Column( name = "DayDemandGregorian" )
    public Integer getDayDemandGregorian() {
        return this.dayDemandGregorian;
    }

    public void setDayDemandGregorian( Integer dayDemandGregorian ) {
        this.dayDemandGregorian = dayDemandGregorian;
    }

    @Column( name = "MonthDemandGregorian" )
    public Integer getMonthDemandGregorian() {
        return this.monthDemandGregorian;
    }

    public void setMonthDemandGregorian( Integer monthDemandGregorian ) {
        this.monthDemandGregorian = monthDemandGregorian;
    }

    @Column( name = "YearDemandGregorian" )
    public Integer getYearDemandGregorian() {
        return this.yearDemandGregorian;
    }

    public void setYearDemandGregorian( Integer yearDemandGregorian ) {
        this.yearDemandGregorian = yearDemandGregorian;
    }

    @Column( name = "DayDemandHijri" )
    public Integer getDayDemandHijri() {
        return this.dayDemandHijri;
    }

    public void setDayDemandHijri( Integer dayDemandHijri ) {
        this.dayDemandHijri = dayDemandHijri;
    }

    @Column( name = "MonthDemandHijri" )
    public Integer getMonthDemandHijri() {
        return this.monthDemandHijri;
    }

    public void setMonthDemandHijri( Integer monthDemandHijri ) {
        this.monthDemandHijri = monthDemandHijri;
    }

    @Column( name = "YearDemandHijri" )
    public Integer getYearDemandHijri() {
        return this.yearDemandHijri;
    }

    public void setYearDemandHijri( Integer yearDemandHijri ) {
        this.yearDemandHijri = yearDemandHijri;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "transcription" )
    public Set<Birth> getBirths() {
        return this.births;
    }

    public void setBirths( Set<Birth> births ) {
        this.births = births;
    }



}
