package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Translatesigned generated by hbm2java
 */
@Entity
@Table( name = "translatesigned", catalog = "etatcivildb" )
public class Translatesigned implements java.io.Serializable {

    private String signedAr;
    private String signedFr;

    public Translatesigned() {
    }

    public Translatesigned( String signedAr ) {
        this.signedAr = signedAr;
    }

    public Translatesigned( String signedAr, String signedFr ) {
        this.signedAr = signedAr;
        this.signedFr = signedFr;
    }

    @Id

    @Column( name = "SignedAr", unique = true, nullable = false, length = 145 )
    public String getSignedAr() {
        return this.signedAr;
    }

    public void setSignedAr( String signedAr ) {
        this.signedAr = signedAr;
    }

    @Column( name = "SignedFr", length = 145 )
    public String getSignedFr() {
        return this.signedFr;
    }

    public void setSignedFr( String signedFr ) {
        this.signedFr = signedFr;
    }

}
