package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table( name = "user", catalog = "etatcivildb" )
public class User implements java.io.Serializable {

    private Integer           iduser;
    private Local             local;
    private Profile           profile;
    private String            login;
    private String            password;
    private String            firstNameAr;
    private String            lastNameAr;
    private String            firstNameFr;
    private String            lastNameFr;
    private String            address;
    private String            phone;
    private String            email;
    private Date              date;
    private Integer           option;
    private String            flag;
    private Set<Print>        prints        = new HashSet<Print>( 0 );
    private Set<Objectdbuser> objectdbusers = new HashSet<Objectdbuser>( 0 );

    public User() {
    }

    public User( Local local, Profile profile, String login, String password, String firstNameAr, String lastNameAr,
            String firstNameFr, String lastNameFr, String address, String phone, String email, Date date,
            Integer option, String flag, Set<Print> prints, Set<Objectdbuser> objectdbusers ) {
        this.local = local;
        this.profile = profile;
        this.login = login;
        this.password = password;
        this.firstNameAr = firstNameAr;
        this.lastNameAr = lastNameAr;
        this.firstNameFr = firstNameFr;
        this.lastNameFr = lastNameFr;
        this.address = address;
        this.phone = phone;
        this.email = email;
        this.date = date;
        this.option = option;
        this.flag = flag;
        this.prints = prints;
        this.objectdbusers = objectdbusers;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "IDUser", unique = true, nullable = false )
    public Integer getIduser() {
        return this.iduser;
    }

    public void setIduser( Integer iduser ) {
        this.iduser = iduser;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDLocal" )
    public Local getLocal() {
        return this.local;
    }

    public void setLocal( Local local ) {
        this.local = local;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDProfile" )
    public Profile getProfile() {
        return this.profile;
    }

    public void setProfile( Profile profile ) {
        this.profile = profile;
    }

    @Column( name = "Login" )
    public String getLogin() {
        return this.login;
    }

    public void setLogin( String login ) {
        this.login = login;
    }

    @Column( name = "Password" )
    public String getPassword() {
        return this.password;
    }

    public void setPassword( String password ) {
        this.password = password;
    }

    @Column( name = "FirstNameAr" )
    public String getFirstNameAr() {
        return this.firstNameAr;
    }

    public void setFirstNameAr( String firstNameAr ) {
        this.firstNameAr = firstNameAr;
    }

    @Column( name = "LastNameAr" )
    public String getLastNameAr() {
        return this.lastNameAr;
    }

    public void setLastNameAr( String lastNameAr ) {
        this.lastNameAr = lastNameAr;
    }

    @Column( name = "FirstNameFr" )
    public String getFirstNameFr() {
        return this.firstNameFr;
    }

    public void setFirstNameFr( String firstNameFr ) {
        this.firstNameFr = firstNameFr;
    }

    @Column( name = "LastNameFr" )
    public String getLastNameFr() {
        return this.lastNameFr;
    }

    public void setLastNameFr( String lastNameFr ) {
        this.lastNameFr = lastNameFr;
    }

    @Column( name = "Address" )
    public String getAddress() {
        return this.address;
    }

    public void setAddress( String address ) {
        this.address = address;
    }

    @Column( name = "Phone" )
    public String getPhone() {
        return this.phone;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }

    @Column( name = "Email" )
    public String getEmail() {
        return this.email;
    }

    public void setEmail( String email ) {
        this.email = email;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "Date", length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "Option" )
    public Integer getOption() {
        return this.option;
    }

    public void setOption( Integer option ) {
        this.option = option;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "user" )
    public Set<Print> getPrints() {
        return this.prints;
    }

    public void setPrints( Set<Print> prints ) {
        this.prints = prints;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "user" )
    public Set<Objectdbuser> getObjectdbusers() {
        return this.objectdbusers;
    }

    public void setObjectdbusers( Set<Objectdbuser> objectdbusers ) {
        this.objectdbusers = objectdbusers;
    }

    @Override
    public String toString() {
        return "User [iduser=" + iduser + ", local=" + local + ", profile=" + profile + ", login=" + login
                + ", password=" + password + ", firstNameAr=" + firstNameAr + ", lastNameAr=" + lastNameAr
                + ", firstNameFr=" + firstNameFr + ", lastNameFr=" + lastNameFr + ", address=" + address + ", phone="
                + phone + ", email=" + email + ", date=" + date + ", option=" + option + ", flag=" + flag + ", prints="
                + prints + ", objectdbusers=" + objectdbusers + "]";
    }

}
