package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VdivorcessId generated by hbm2java
 */
@Embeddable
public class VdivorcessId implements java.io.Serializable {

    private Integer idbirth;
    private Integer gender;
    private Integer idmention;
    private Integer idact;
    private Integer idmentionType;
    private Integer statusMention;
    private String  valuesMention;
    private String  officerAr;
    private String  officerFr;
    private Integer dayGregorianEdition;
    private Integer monthGregorianEdition;
    private Integer yearGregorianEdition;
    private Integer dayHijriEdition;
    private Integer monthHijriEdition;
    private Integer yearHijriEdition;
    private String  flag;

    public VdivorcessId() {
    }

    public VdivorcessId( Integer idbirth, Integer gender, Integer idmention, Integer idact, Integer idmentionType,
            Integer statusMention, String valuesMention, String officerAr, String officerFr,
            Integer dayGregorianEdition, Integer monthGregorianEdition, Integer yearGregorianEdition,
            Integer dayHijriEdition, Integer monthHijriEdition, Integer yearHijriEdition, String flag ) {
        this.idbirth = idbirth;
        this.gender = gender;
        this.idmention = idmention;
        this.idact = idact;
        this.idmentionType = idmentionType;
        this.statusMention = statusMention;
        this.valuesMention = valuesMention;
        this.officerAr = officerAr;
        this.officerFr = officerFr;
        this.dayGregorianEdition = dayGregorianEdition;
        this.monthGregorianEdition = monthGregorianEdition;
        this.yearGregorianEdition = yearGregorianEdition;
        this.dayHijriEdition = dayHijriEdition;
        this.monthHijriEdition = monthHijriEdition;
        this.yearHijriEdition = yearHijriEdition;
        this.flag = flag;
    }

    @Column( name = "idbirth" )
    public Integer getIdbirth() {
        return this.idbirth;
    }

    public void setIdbirth( Integer idbirth ) {
        this.idbirth = idbirth;
    }

    @Column( name = "gender" )
    public Integer getGender() {
        return this.gender;
    }

    public void setGender( Integer gender ) {
        this.gender = gender;
    }

    @Column( name = "IDMention" )
    public Integer getIdmention() {
        return this.idmention;
    }

    public void setIdmention( Integer idmention ) {
        this.idmention = idmention;
    }

    @Column( name = "IDAct" )
    public Integer getIdact() {
        return this.idact;
    }

    public void setIdact( Integer idact ) {
        this.idact = idact;
    }

    @Column( name = "IDMentionType" )
    public Integer getIdmentionType() {
        return this.idmentionType;
    }

    public void setIdmentionType( Integer idmentionType ) {
        this.idmentionType = idmentionType;
    }

    @Column( name = "StatusMention" )
    public Integer getStatusMention() {
        return this.statusMention;
    }

    public void setStatusMention( Integer statusMention ) {
        this.statusMention = statusMention;
    }

    @Column( name = "ValuesMention", length = 65535 )
    public String getValuesMention() {
        return this.valuesMention;
    }

    public void setValuesMention( String valuesMention ) {
        this.valuesMention = valuesMention;
    }

    @Column( name = "OfficerAr" )
    public String getOfficerAr() {
        return this.officerAr;
    }

    public void setOfficerAr( String officerAr ) {
        this.officerAr = officerAr;
    }

    @Column( name = "OfficerFr" )
    public String getOfficerFr() {
        return this.officerFr;
    }

    public void setOfficerFr( String officerFr ) {
        this.officerFr = officerFr;
    }

    @Column( name = "DayGregorianEdition" )
    public Integer getDayGregorianEdition() {
        return this.dayGregorianEdition;
    }

    public void setDayGregorianEdition( Integer dayGregorianEdition ) {
        this.dayGregorianEdition = dayGregorianEdition;
    }

    @Column( name = "MonthGregorianEdition" )
    public Integer getMonthGregorianEdition() {
        return this.monthGregorianEdition;
    }

    public void setMonthGregorianEdition( Integer monthGregorianEdition ) {
        this.monthGregorianEdition = monthGregorianEdition;
    }

    @Column( name = "YearGregorianEdition" )
    public Integer getYearGregorianEdition() {
        return this.yearGregorianEdition;
    }

    public void setYearGregorianEdition( Integer yearGregorianEdition ) {
        this.yearGregorianEdition = yearGregorianEdition;
    }

    @Column( name = "DayHijriEdition" )
    public Integer getDayHijriEdition() {
        return this.dayHijriEdition;
    }

    public void setDayHijriEdition( Integer dayHijriEdition ) {
        this.dayHijriEdition = dayHijriEdition;
    }

    @Column( name = "MonthHijriEdition" )
    public Integer getMonthHijriEdition() {
        return this.monthHijriEdition;
    }

    public void setMonthHijriEdition( Integer monthHijriEdition ) {
        this.monthHijriEdition = monthHijriEdition;
    }

    @Column( name = "YearHijriEdition" )
    public Integer getYearHijriEdition() {
        return this.yearHijriEdition;
    }

    public void setYearHijriEdition( Integer yearHijriEdition ) {
        this.yearHijriEdition = yearHijriEdition;
    }

    @Column( name = "Flag" )
    public String getFlag() {
        return this.flag;
    }

    public void setFlag( String flag ) {
        this.flag = flag;
    }

    public boolean equals( Object other ) {
        if ( ( this == other ) )
            return true;
        if ( ( other == null ) )
            return false;
        if ( !( other instanceof VdivorcessId ) )
            return false;
        VdivorcessId castOther = (VdivorcessId) other;

        return ( ( this.getIdbirth() == castOther.getIdbirth() ) || ( this.getIdbirth() != null
                && castOther.getIdbirth() != null && this.getIdbirth().equals( castOther.getIdbirth() ) ) )
                && ( ( this.getGender() == castOther.getGender() ) || ( this.getGender() != null
                        && castOther.getGender() != null && this.getGender().equals( castOther.getGender() ) ) )
                && ( ( this.getIdmention() == castOther.getIdmention() )
                        || ( this.getIdmention() != null && castOther.getIdmention() != null
                                && this.getIdmention().equals( castOther.getIdmention() ) ) )
                && ( ( this.getIdact() == castOther.getIdact() ) || ( this.getIdact() != null
                        && castOther.getIdact() != null && this.getIdact().equals( castOther.getIdact() ) ) )
                && ( ( this.getIdmentionType() == castOther.getIdmentionType() )
                        || ( this.getIdmentionType() != null && castOther.getIdmentionType() != null
                                && this.getIdmentionType().equals( castOther.getIdmentionType() ) ) )
                && ( ( this.getStatusMention() == castOther.getStatusMention() )
                        || ( this.getStatusMention() != null && castOther.getStatusMention() != null
                                && this.getStatusMention().equals( castOther.getStatusMention() ) ) )
                && ( ( this.getValuesMention() == castOther.getValuesMention() )
                        || ( this.getValuesMention() != null && castOther.getValuesMention() != null
                                && this.getValuesMention().equals( castOther.getValuesMention() ) ) )
                && ( ( this.getOfficerAr() == castOther.getOfficerAr() )
                        || ( this.getOfficerAr() != null && castOther.getOfficerAr() != null
                                && this.getOfficerAr().equals( castOther.getOfficerAr() ) ) )
                && ( ( this.getOfficerFr() == castOther.getOfficerFr() )
                        || ( this.getOfficerFr() != null && castOther.getOfficerFr() != null
                                && this.getOfficerFr().equals( castOther.getOfficerFr() ) ) )
                && ( ( this.getDayGregorianEdition() == castOther.getDayGregorianEdition() )
                        || ( this.getDayGregorianEdition() != null && castOther.getDayGregorianEdition() != null
                                && this.getDayGregorianEdition().equals( castOther.getDayGregorianEdition() ) ) )
                && ( ( this.getMonthGregorianEdition() == castOther.getMonthGregorianEdition() )
                        || ( this.getMonthGregorianEdition() != null && castOther.getMonthGregorianEdition() != null
                                && this.getMonthGregorianEdition().equals( castOther.getMonthGregorianEdition() ) ) )
                && ( ( this.getYearGregorianEdition() == castOther.getYearGregorianEdition() )
                        || ( this.getYearGregorianEdition() != null && castOther.getYearGregorianEdition() != null
                                && this.getYearGregorianEdition().equals( castOther.getYearGregorianEdition() ) ) )
                && ( ( this.getDayHijriEdition() == castOther.getDayHijriEdition() )
                        || ( this.getDayHijriEdition() != null && castOther.getDayHijriEdition() != null
                                && this.getDayHijriEdition().equals( castOther.getDayHijriEdition() ) ) )
                && ( ( this.getMonthHijriEdition() == castOther.getMonthHijriEdition() )
                        || ( this.getMonthHijriEdition() != null && castOther.getMonthHijriEdition() != null
                                && this.getMonthHijriEdition().equals( castOther.getMonthHijriEdition() ) ) )
                && ( ( this.getYearHijriEdition() == castOther.getYearHijriEdition() )
                        || ( this.getYearHijriEdition() != null && castOther.getYearHijriEdition() != null
                                && this.getYearHijriEdition().equals( castOther.getYearHijriEdition() ) ) )
                && ( ( this.getFlag() == castOther.getFlag() ) || ( this.getFlag() != null
                        && castOther.getFlag() != null && this.getFlag().equals( castOther.getFlag() ) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getIdbirth() == null ? 0 : this.getIdbirth().hashCode() );
        result = 37 * result + ( getGender() == null ? 0 : this.getGender().hashCode() );
        result = 37 * result + ( getIdmention() == null ? 0 : this.getIdmention().hashCode() );
        result = 37 * result + ( getIdact() == null ? 0 : this.getIdact().hashCode() );
        result = 37 * result + ( getIdmentionType() == null ? 0 : this.getIdmentionType().hashCode() );
        result = 37 * result + ( getStatusMention() == null ? 0 : this.getStatusMention().hashCode() );
        result = 37 * result + ( getValuesMention() == null ? 0 : this.getValuesMention().hashCode() );
        result = 37 * result + ( getOfficerAr() == null ? 0 : this.getOfficerAr().hashCode() );
        result = 37 * result + ( getOfficerFr() == null ? 0 : this.getOfficerFr().hashCode() );
        result = 37 * result + ( getDayGregorianEdition() == null ? 0 : this.getDayGregorianEdition().hashCode() );
        result = 37 * result + ( getMonthGregorianEdition() == null ? 0 : this.getMonthGregorianEdition().hashCode() );
        result = 37 * result + ( getYearGregorianEdition() == null ? 0 : this.getYearGregorianEdition().hashCode() );
        result = 37 * result + ( getDayHijriEdition() == null ? 0 : this.getDayHijriEdition().hashCode() );
        result = 37 * result + ( getMonthHijriEdition() == null ? 0 : this.getMonthHijriEdition().hashCode() );
        result = 37 * result + ( getYearHijriEdition() == null ? 0 : this.getYearHijriEdition().hashCode() );
        result = 37 * result + ( getFlag() == null ? 0 : this.getFlag().hashCode() );
        return result;
    }

}
