package cg.ncn.entities.etatcivil;
// Generated 9 juil. 2019 12:51:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Vdivorcess generated by hbm2java
 */
@Entity
@Table( name = "vdivorcess", catalog = "etatcivildb" )
public class Vdivorcess implements java.io.Serializable {

    private VdivorcessId id;

    public Vdivorcess() {
    }

    public Vdivorcess( VdivorcessId id ) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides( {
            @AttributeOverride( name = "idbirth", column = @Column( name = "idbirth" ) ),
            @AttributeOverride( name = "gender", column = @Column( name = "gender" ) ),
            @AttributeOverride( name = "idmention", column = @Column( name = "IDMention" ) ),
            @AttributeOverride( name = "idact", column = @Column( name = "IDAct" ) ),
            @AttributeOverride( name = "idmentionType", column = @Column( name = "IDMentionType" ) ),
            @AttributeOverride( name = "statusMention", column = @Column( name = "StatusMention" ) ),
            @AttributeOverride( name = "valuesMention", column = @Column( name = "ValuesMention", length = 65535 ) ),
            @AttributeOverride( name = "officerAr", column = @Column( name = "OfficerAr" ) ),
            @AttributeOverride( name = "officerFr", column = @Column( name = "OfficerFr" ) ),
            @AttributeOverride( name = "dayGregorianEdition", column = @Column( name = "DayGregorianEdition" ) ),
            @AttributeOverride( name = "monthGregorianEdition", column = @Column( name = "MonthGregorianEdition" ) ),
            @AttributeOverride( name = "yearGregorianEdition", column = @Column( name = "YearGregorianEdition" ) ),
            @AttributeOverride( name = "dayHijriEdition", column = @Column( name = "DayHijriEdition" ) ),
            @AttributeOverride( name = "monthHijriEdition", column = @Column( name = "MonthHijriEdition" ) ),
            @AttributeOverride( name = "yearHijriEdition", column = @Column( name = "YearHijriEdition" ) ),
            @AttributeOverride( name = "flag", column = @Column( name = "Flag" ) ) } )
    public VdivorcessId getId() {
        return this.id;
    }

    public void setId( VdivorcessId id ) {
        this.id = id;
    }

}
