package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChthibiIirreversibility generated by hbm2java
 */
@Entity
@Table( name = "chthibi_iirreversibility", catalog = "vitalstatistics" )
public class ChthibiIirreversibility implements java.io.Serializable {

    private Integer id;
    private int     idbirth;
    private int     idtype;
    private String  who;
    private String  with;
    private String  act;
    private String  court;
    private Date    date;
    private int     daygeorgian;
    private int     monthgeorgian;
    private int     yeargeorgian;
    private int     dayhijri;
    private int     monthhijri;
    private int     yearhijri;
    private int     daygeorgianedition;
    private int     monthgeorgianedition;
    private int     yeargeorgianedition;
    private int     dayhijriedition;
    private int     monthhijriedition;
    private int     yearhijriedition;
    private int     iduser;
    private int     valid;
    private String  whofr;
    private String  withfr;
    private String  courtfr;
    private String  mentionofficerar;
    private String  mentionofficerfr;

    public ChthibiIirreversibility() {
    }

    public ChthibiIirreversibility( int idbirth, int idtype, String who, String with, String act, String court,
            int daygeorgian, int monthgeorgian, int yeargeorgian, int dayhijri, int monthhijri, int yearhijri,
            int daygeorgianedition, int monthgeorgianedition, int yeargeorgianedition, int dayhijriedition,
            int monthhijriedition, int yearhijriedition, int iduser, int valid ) {
        this.idbirth = idbirth;
        this.idtype = idtype;
        this.who = who;
        this.with = with;
        this.act = act;
        this.court = court;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.daygeorgianedition = daygeorgianedition;
        this.monthgeorgianedition = monthgeorgianedition;
        this.yeargeorgianedition = yeargeorgianedition;
        this.dayhijriedition = dayhijriedition;
        this.monthhijriedition = monthhijriedition;
        this.yearhijriedition = yearhijriedition;
        this.iduser = iduser;
        this.valid = valid;
    }

    public ChthibiIirreversibility( int idbirth, int idtype, String who, String with, String act, String court,
            Date date, int daygeorgian, int monthgeorgian, int yeargeorgian, int dayhijri, int monthhijri,
            int yearhijri, int daygeorgianedition, int monthgeorgianedition, int yeargeorgianedition,
            int dayhijriedition, int monthhijriedition, int yearhijriedition, int iduser, int valid, String whofr,
            String withfr, String courtfr, String mentionofficerar, String mentionofficerfr ) {
        this.idbirth = idbirth;
        this.idtype = idtype;
        this.who = who;
        this.with = with;
        this.act = act;
        this.court = court;
        this.date = date;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.daygeorgianedition = daygeorgianedition;
        this.monthgeorgianedition = monthgeorgianedition;
        this.yeargeorgianedition = yeargeorgianedition;
        this.dayhijriedition = dayhijriedition;
        this.monthhijriedition = monthhijriedition;
        this.yearhijriedition = yearhijriedition;
        this.iduser = iduser;
        this.valid = valid;
        this.whofr = whofr;
        this.withfr = withfr;
        this.courtfr = courtfr;
        this.mentionofficerar = mentionofficerar;
        this.mentionofficerfr = mentionofficerfr;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "IDBIRTH", nullable = false )
    public int getIdbirth() {
        return this.idbirth;
    }

    public void setIdbirth( int idbirth ) {
        this.idbirth = idbirth;
    }

    @Column( name = "IDTYPE", nullable = false )
    public int getIdtype() {
        return this.idtype;
    }

    public void setIdtype( int idtype ) {
        this.idtype = idtype;
    }

    @Column( name = "WHO", nullable = false, length = 128 )
    public String getWho() {
        return this.who;
    }

    public void setWho( String who ) {
        this.who = who;
    }

    @Column( name = "WITH", nullable = false, length = 128 )
    public String getWith() {
        return this.with;
    }

    public void setWith( String with ) {
        this.with = with;
    }

    @Column( name = "ACT", nullable = false, length = 128 )
    public String getAct() {
        return this.act;
    }

    public void setAct( String act ) {
        this.act = act;
    }

    @Column( name = "COURT", nullable = false, length = 128 )
    public String getCourt() {
        return this.court;
    }

    public void setCourt( String court ) {
        this.court = court;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "DATE", length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "DAYGEORGIAN", nullable = false )
    public int getDaygeorgian() {
        return this.daygeorgian;
    }

    public void setDaygeorgian( int daygeorgian ) {
        this.daygeorgian = daygeorgian;
    }

    @Column( name = "MONTHGEORGIAN", nullable = false )
    public int getMonthgeorgian() {
        return this.monthgeorgian;
    }

    public void setMonthgeorgian( int monthgeorgian ) {
        this.monthgeorgian = monthgeorgian;
    }

    @Column( name = "YEARGEORGIAN", nullable = false )
    public int getYeargeorgian() {
        return this.yeargeorgian;
    }

    public void setYeargeorgian( int yeargeorgian ) {
        this.yeargeorgian = yeargeorgian;
    }

    @Column( name = "DAYHIJRI", nullable = false )
    public int getDayhijri() {
        return this.dayhijri;
    }

    public void setDayhijri( int dayhijri ) {
        this.dayhijri = dayhijri;
    }

    @Column( name = "MONTHHIJRI", nullable = false )
    public int getMonthhijri() {
        return this.monthhijri;
    }

    public void setMonthhijri( int monthhijri ) {
        this.monthhijri = monthhijri;
    }

    @Column( name = "YEARHIJRI", nullable = false )
    public int getYearhijri() {
        return this.yearhijri;
    }

    public void setYearhijri( int yearhijri ) {
        this.yearhijri = yearhijri;
    }

    @Column( name = "DAYGEORGIANEDITION", nullable = false )
    public int getDaygeorgianedition() {
        return this.daygeorgianedition;
    }

    public void setDaygeorgianedition( int daygeorgianedition ) {
        this.daygeorgianedition = daygeorgianedition;
    }

    @Column( name = "MONTHGEORGIANEDITION", nullable = false )
    public int getMonthgeorgianedition() {
        return this.monthgeorgianedition;
    }

    public void setMonthgeorgianedition( int monthgeorgianedition ) {
        this.monthgeorgianedition = monthgeorgianedition;
    }

    @Column( name = "YEARGEORGIANEDITION", nullable = false )
    public int getYeargeorgianedition() {
        return this.yeargeorgianedition;
    }

    public void setYeargeorgianedition( int yeargeorgianedition ) {
        this.yeargeorgianedition = yeargeorgianedition;
    }

    @Column( name = "DAYHIJRIEDITION", nullable = false )
    public int getDayhijriedition() {
        return this.dayhijriedition;
    }

    public void setDayhijriedition( int dayhijriedition ) {
        this.dayhijriedition = dayhijriedition;
    }

    @Column( name = "MONTHHIJRIEDITION", nullable = false )
    public int getMonthhijriedition() {
        return this.monthhijriedition;
    }

    public void setMonthhijriedition( int monthhijriedition ) {
        this.monthhijriedition = monthhijriedition;
    }

    @Column( name = "YEARHIJRIEDITION", nullable = false )
    public int getYearhijriedition() {
        return this.yearhijriedition;
    }

    public void setYearhijriedition( int yearhijriedition ) {
        this.yearhijriedition = yearhijriedition;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @Column( name = "WHOFR", length = 128 )
    public String getWhofr() {
        return this.whofr;
    }

    public void setWhofr( String whofr ) {
        this.whofr = whofr;
    }

    @Column( name = "WITHFR", length = 128 )
    public String getWithfr() {
        return this.withfr;
    }

    public void setWithfr( String withfr ) {
        this.withfr = withfr;
    }

    @Column( name = "COURTFR", length = 128 )
    public String getCourtfr() {
        return this.courtfr;
    }

    public void setCourtfr( String courtfr ) {
        this.courtfr = courtfr;
    }

    @Column( name = "MENTIONOFFICERAR", length = 128 )
    public String getMentionofficerar() {
        return this.mentionofficerar;
    }

    public void setMentionofficerar( String mentionofficerar ) {
        this.mentionofficerar = mentionofficerar;
    }

    @Column( name = "MENTIONOFFICERFR", length = 128 )
    public String getMentionofficerfr() {
        return this.mentionofficerfr;
    }

    public void setMentionofficerfr( String mentionofficerfr ) {
        this.mentionofficerfr = mentionofficerfr;
    }

}
