package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ChthibiUser generated by hbm2java
 */
@Entity
@Table( name = "chthibi_user", catalog = "vitalstatistics", uniqueConstraints = @UniqueConstraint( columnNames = "LOGIN" ) )
public class ChthibiUser implements java.io.Serializable {

    private Integer            id;
    private String             firstnamefrench;
    private String             firstnamearabic;
    private String             lastnamefrench;
    private String             lastnamearabic;
    private String             login;
    private String             password;
    private Date               date;
    private int                iddistrict;
    private int                idannex;
    private String             address;
    private String             email;
    private String             phone;
    private int                idprofile;
    private Set<ChthibiPrints> chthibiPrintses = new HashSet<ChthibiPrints>( 0 );
    private Set<ChthibiBirth>  chthibiBirths   = new HashSet<ChthibiBirth>( 0 );

    public ChthibiUser() {
    }

    public ChthibiUser( String firstnamefrench, String firstnamearabic, String lastnamefrench, String lastnamearabic,
            String login, String password, int iddistrict, int idannex, String address, String email, String phone,
            int idprofile ) {
        this.firstnamefrench = firstnamefrench;
        this.firstnamearabic = firstnamearabic;
        this.lastnamefrench = lastnamefrench;
        this.lastnamearabic = lastnamearabic;
        this.login = login;
        this.password = password;
        this.iddistrict = iddistrict;
        this.idannex = idannex;
        this.address = address;
        this.email = email;
        this.phone = phone;
        this.idprofile = idprofile;
    }

    public ChthibiUser( String firstnamefrench, String firstnamearabic, String lastnamefrench, String lastnamearabic,
            String login, String password, Date date, int iddistrict, int idannex, String address, String email,
            String phone, int idprofile, Set<ChthibiPrints> chthibiPrintses, Set<ChthibiBirth> chthibiBirths ) {
        this.firstnamefrench = firstnamefrench;
        this.firstnamearabic = firstnamearabic;
        this.lastnamefrench = lastnamefrench;
        this.lastnamearabic = lastnamearabic;
        this.login = login;
        this.password = password;
        this.date = date;
        this.iddistrict = iddistrict;
        this.idannex = idannex;
        this.address = address;
        this.email = email;
        this.phone = phone;
        this.idprofile = idprofile;
        this.chthibiPrintses = chthibiPrintses;
        this.chthibiBirths = chthibiBirths;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "FIRSTNAMEFRENCH", nullable = false, length = 64 )
    public String getFirstnamefrench() {
        return this.firstnamefrench;
    }

    public void setFirstnamefrench( String firstnamefrench ) {
        this.firstnamefrench = firstnamefrench;
    }

    @Column( name = "FIRSTNAMEARABIC", nullable = false, length = 64 )
    public String getFirstnamearabic() {
        return this.firstnamearabic;
    }

    public void setFirstnamearabic( String firstnamearabic ) {
        this.firstnamearabic = firstnamearabic;
    }

    @Column( name = "LASTNAMEFRENCH", nullable = false, length = 64 )
    public String getLastnamefrench() {
        return this.lastnamefrench;
    }

    public void setLastnamefrench( String lastnamefrench ) {
        this.lastnamefrench = lastnamefrench;
    }

    @Column( name = "LASTNAMEARABIC", nullable = false, length = 64 )
    public String getLastnamearabic() {
        return this.lastnamearabic;
    }

    public void setLastnamearabic( String lastnamearabic ) {
        this.lastnamearabic = lastnamearabic;
    }

    @Column( name = "LOGIN", unique = true, nullable = false, length = 64 )
    public String getLogin() {
        return this.login;
    }

    public void setLogin( String login ) {
        this.login = login;
    }

    @Column( name = "PASSWORD", nullable = false )
    public String getPassword() {
        return this.password;
    }

    public void setPassword( String password ) {
        this.password = password;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "DATE", length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "IDDISTRICT", nullable = false )
    public int getIddistrict() {
        return this.iddistrict;
    }

    public void setIddistrict( int iddistrict ) {
        this.iddistrict = iddistrict;
    }

    @Column( name = "IDANNEX", nullable = false )
    public int getIdannex() {
        return this.idannex;
    }

    public void setIdannex( int idannex ) {
        this.idannex = idannex;
    }

    @Column( name = "ADDRESS", nullable = false )
    public String getAddress() {
        return this.address;
    }

    public void setAddress( String address ) {
        this.address = address;
    }

    @Column( name = "EMAIL", nullable = false, length = 128 )
    public String getEmail() {
        return this.email;
    }

    public void setEmail( String email ) {
        this.email = email;
    }

    @Column( name = "PHONE", nullable = false, length = 64 )
    public String getPhone() {
        return this.phone;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }

    @Column( name = "IDPROFILE", nullable = false )
    public int getIdprofile() {
        return this.idprofile;
    }

    public void setIdprofile( int idprofile ) {
        this.idprofile = idprofile;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "chthibiUser" )
    public Set<ChthibiPrints> getChthibiPrintses() {
        return this.chthibiPrintses;
    }

    public void setChthibiPrintses( Set<ChthibiPrints> chthibiPrintses ) {
        this.chthibiPrintses = chthibiPrintses;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "chthibiUser" )
    public Set<ChthibiBirth> getChthibiBirths() {
        return this.chthibiBirths;
    }

    public void setChthibiBirths( Set<ChthibiBirth> chthibiBirths ) {
        this.chthibiBirths = chthibiBirths;
    }

}
