package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChthibiDeathIrevisionunderrule generated by hbm2java
 */
@Entity
@Table( name = "chthibi_death_irevisionunderrule", catalog = "vitalstatistics" )
public class ChthibiDeathIrevisionunderrule implements java.io.Serializable {

    private Integer id;
    private int     iddeath;
    private int     idtype;
    private int     field;
    private String  newfr;
    private String  oldfr;
    private String  act;
    private String  court;
    private int     year;
    private int     number;
    private String  newar;
    private String  oldar;
    private Date    date;
    private int     daygeorgian;
    private int     monthgeorgian;
    private int     yeargeorgian;
    private int     dayhijri;
    private int     monthhijri;
    private int     yearhijri;
    private int     daygeorgianedition;
    private int     monthgeorgianedition;
    private int     yeargeorgianedition;
    private int     dayhijriedition;
    private int     monthhijriedition;
    private int     yearhijriedition;
    private int     iduser;
    private int     valid;
    private Integer newdaygeorgian;
    private Integer newmonthgeorgian;
    private Integer newyeargeorgian;
    private Integer newdayhijri;
    private Integer newmonthhijri;
    private Integer newyearhijri;
    private Integer olddayhijri;
    private Integer oldmonthhijri;
    private Integer oldyearhijri;
    private Integer olddaygeorgian;
    private Integer oldmonthgeorgian;
    private Integer oldyeargeorgian;
    private String  courtfr;
    private String  mentionofficerar;
    private String  mentionofficerfr;

    public ChthibiDeathIrevisionunderrule() {
    }

    public ChthibiDeathIrevisionunderrule( int iddeath, int idtype, int field, String court, int year, int number,
            int daygeorgian, int monthgeorgian, int yeargeorgian, int dayhijri, int monthhijri, int yearhijri,
            int daygeorgianedition, int monthgeorgianedition, int yeargeorgianedition, int dayhijriedition,
            int monthhijriedition, int yearhijriedition, int iduser, int valid ) {
        this.iddeath = iddeath;
        this.idtype = idtype;
        this.field = field;
        this.court = court;
        this.year = year;
        this.number = number;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.daygeorgianedition = daygeorgianedition;
        this.monthgeorgianedition = monthgeorgianedition;
        this.yeargeorgianedition = yeargeorgianedition;
        this.dayhijriedition = dayhijriedition;
        this.monthhijriedition = monthhijriedition;
        this.yearhijriedition = yearhijriedition;
        this.iduser = iduser;
        this.valid = valid;
    }

    public ChthibiDeathIrevisionunderrule( int iddeath, int idtype, int field, String newfr, String oldfr, String act,
            String court, int year, int number, String newar, String oldar, Date date, int daygeorgian,
            int monthgeorgian, int yeargeorgian, int dayhijri, int monthhijri, int yearhijri, int daygeorgianedition,
            int monthgeorgianedition, int yeargeorgianedition, int dayhijriedition, int monthhijriedition,
            int yearhijriedition, int iduser, int valid, Integer newdaygeorgian, Integer newmonthgeorgian,
            Integer newyeargeorgian, Integer newdayhijri, Integer newmonthhijri, Integer newyearhijri,
            Integer olddayhijri, Integer oldmonthhijri, Integer oldyearhijri, Integer olddaygeorgian,
            Integer oldmonthgeorgian, Integer oldyeargeorgian, String courtfr, String mentionofficerar,
            String mentionofficerfr ) {
        this.iddeath = iddeath;
        this.idtype = idtype;
        this.field = field;
        this.newfr = newfr;
        this.oldfr = oldfr;
        this.act = act;
        this.court = court;
        this.year = year;
        this.number = number;
        this.newar = newar;
        this.oldar = oldar;
        this.date = date;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.daygeorgianedition = daygeorgianedition;
        this.monthgeorgianedition = monthgeorgianedition;
        this.yeargeorgianedition = yeargeorgianedition;
        this.dayhijriedition = dayhijriedition;
        this.monthhijriedition = monthhijriedition;
        this.yearhijriedition = yearhijriedition;
        this.iduser = iduser;
        this.valid = valid;
        this.newdaygeorgian = newdaygeorgian;
        this.newmonthgeorgian = newmonthgeorgian;
        this.newyeargeorgian = newyeargeorgian;
        this.newdayhijri = newdayhijri;
        this.newmonthhijri = newmonthhijri;
        this.newyearhijri = newyearhijri;
        this.olddayhijri = olddayhijri;
        this.oldmonthhijri = oldmonthhijri;
        this.oldyearhijri = oldyearhijri;
        this.olddaygeorgian = olddaygeorgian;
        this.oldmonthgeorgian = oldmonthgeorgian;
        this.oldyeargeorgian = oldyeargeorgian;
        this.courtfr = courtfr;
        this.mentionofficerar = mentionofficerar;
        this.mentionofficerfr = mentionofficerfr;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "IDDEATH", nullable = false )
    public int getIddeath() {
        return this.iddeath;
    }

    public void setIddeath( int iddeath ) {
        this.iddeath = iddeath;
    }

    @Column( name = "IDTYPE", nullable = false )
    public int getIdtype() {
        return this.idtype;
    }

    public void setIdtype( int idtype ) {
        this.idtype = idtype;
    }

    @Column( name = "FIELD", nullable = false )
    public int getField() {
        return this.field;
    }

    public void setField( int field ) {
        this.field = field;
    }

    @Column( name = "NEWFR", length = 128 )
    public String getNewfr() {
        return this.newfr;
    }

    public void setNewfr( String newfr ) {
        this.newfr = newfr;
    }

    @Column( name = "OLDFR", length = 128 )
    public String getOldfr() {
        return this.oldfr;
    }

    public void setOldfr( String oldfr ) {
        this.oldfr = oldfr;
    }

    @Column( name = "ACT", length = 128 )
    public String getAct() {
        return this.act;
    }

    public void setAct( String act ) {
        this.act = act;
    }

    @Column( name = "COURT", nullable = false, length = 128 )
    public String getCourt() {
        return this.court;
    }

    public void setCourt( String court ) {
        this.court = court;
    }

    @Column( name = "YEAR", nullable = false )
    public int getYear() {
        return this.year;
    }

    public void setYear( int year ) {
        this.year = year;
    }

    @Column( name = "NUMBER", nullable = false )
    public int getNumber() {
        return this.number;
    }

    public void setNumber( int number ) {
        this.number = number;
    }

    @Column( name = "NEWAR", length = 128 )
    public String getNewar() {
        return this.newar;
    }

    public void setNewar( String newar ) {
        this.newar = newar;
    }

    @Column( name = "OLDAR", length = 128 )
    public String getOldar() {
        return this.oldar;
    }

    public void setOldar( String oldar ) {
        this.oldar = oldar;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "DATE", length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "DAYGEORGIAN", nullable = false )
    public int getDaygeorgian() {
        return this.daygeorgian;
    }

    public void setDaygeorgian( int daygeorgian ) {
        this.daygeorgian = daygeorgian;
    }

    @Column( name = "MONTHGEORGIAN", nullable = false )
    public int getMonthgeorgian() {
        return this.monthgeorgian;
    }

    public void setMonthgeorgian( int monthgeorgian ) {
        this.monthgeorgian = monthgeorgian;
    }

    @Column( name = "YEARGEORGIAN", nullable = false )
    public int getYeargeorgian() {
        return this.yeargeorgian;
    }

    public void setYeargeorgian( int yeargeorgian ) {
        this.yeargeorgian = yeargeorgian;
    }

    @Column( name = "DAYHIJRI", nullable = false )
    public int getDayhijri() {
        return this.dayhijri;
    }

    public void setDayhijri( int dayhijri ) {
        this.dayhijri = dayhijri;
    }

    @Column( name = "MONTHHIJRI", nullable = false )
    public int getMonthhijri() {
        return this.monthhijri;
    }

    public void setMonthhijri( int monthhijri ) {
        this.monthhijri = monthhijri;
    }

    @Column( name = "YEARHIJRI", nullable = false )
    public int getYearhijri() {
        return this.yearhijri;
    }

    public void setYearhijri( int yearhijri ) {
        this.yearhijri = yearhijri;
    }

    @Column( name = "DAYGEORGIANEDITION", nullable = false )
    public int getDaygeorgianedition() {
        return this.daygeorgianedition;
    }

    public void setDaygeorgianedition( int daygeorgianedition ) {
        this.daygeorgianedition = daygeorgianedition;
    }

    @Column( name = "MONTHGEORGIANEDITION", nullable = false )
    public int getMonthgeorgianedition() {
        return this.monthgeorgianedition;
    }

    public void setMonthgeorgianedition( int monthgeorgianedition ) {
        this.monthgeorgianedition = monthgeorgianedition;
    }

    @Column( name = "YEARGEORGIANEDITION", nullable = false )
    public int getYeargeorgianedition() {
        return this.yeargeorgianedition;
    }

    public void setYeargeorgianedition( int yeargeorgianedition ) {
        this.yeargeorgianedition = yeargeorgianedition;
    }

    @Column( name = "DAYHIJRIEDITION", nullable = false )
    public int getDayhijriedition() {
        return this.dayhijriedition;
    }

    public void setDayhijriedition( int dayhijriedition ) {
        this.dayhijriedition = dayhijriedition;
    }

    @Column( name = "MONTHHIJRIEDITION", nullable = false )
    public int getMonthhijriedition() {
        return this.monthhijriedition;
    }

    public void setMonthhijriedition( int monthhijriedition ) {
        this.monthhijriedition = monthhijriedition;
    }

    @Column( name = "YEARHIJRIEDITION", nullable = false )
    public int getYearhijriedition() {
        return this.yearhijriedition;
    }

    public void setYearhijriedition( int yearhijriedition ) {
        this.yearhijriedition = yearhijriedition;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @Column( name = "NEWDAYGEORGIAN" )
    public Integer getNewdaygeorgian() {
        return this.newdaygeorgian;
    }

    public void setNewdaygeorgian( Integer newdaygeorgian ) {
        this.newdaygeorgian = newdaygeorgian;
    }

    @Column( name = "NEWMONTHGEORGIAN" )
    public Integer getNewmonthgeorgian() {
        return this.newmonthgeorgian;
    }

    public void setNewmonthgeorgian( Integer newmonthgeorgian ) {
        this.newmonthgeorgian = newmonthgeorgian;
    }

    @Column( name = "NEWYEARGEORGIAN" )
    public Integer getNewyeargeorgian() {
        return this.newyeargeorgian;
    }

    public void setNewyeargeorgian( Integer newyeargeorgian ) {
        this.newyeargeorgian = newyeargeorgian;
    }

    @Column( name = "NEWDAYHIJRI" )
    public Integer getNewdayhijri() {
        return this.newdayhijri;
    }

    public void setNewdayhijri( Integer newdayhijri ) {
        this.newdayhijri = newdayhijri;
    }

    @Column( name = "NEWMONTHHIJRI" )
    public Integer getNewmonthhijri() {
        return this.newmonthhijri;
    }

    public void setNewmonthhijri( Integer newmonthhijri ) {
        this.newmonthhijri = newmonthhijri;
    }

    @Column( name = "NEWYEARHIJRI" )
    public Integer getNewyearhijri() {
        return this.newyearhijri;
    }

    public void setNewyearhijri( Integer newyearhijri ) {
        this.newyearhijri = newyearhijri;
    }

    @Column( name = "OLDDAYHIJRI" )
    public Integer getOlddayhijri() {
        return this.olddayhijri;
    }

    public void setOlddayhijri( Integer olddayhijri ) {
        this.olddayhijri = olddayhijri;
    }

    @Column( name = "OLDMONTHHIJRI" )
    public Integer getOldmonthhijri() {
        return this.oldmonthhijri;
    }

    public void setOldmonthhijri( Integer oldmonthhijri ) {
        this.oldmonthhijri = oldmonthhijri;
    }

    @Column( name = "OLDYEARHIJRI" )
    public Integer getOldyearhijri() {
        return this.oldyearhijri;
    }

    public void setOldyearhijri( Integer oldyearhijri ) {
        this.oldyearhijri = oldyearhijri;
    }

    @Column( name = "OLDDAYGEORGIAN" )
    public Integer getOlddaygeorgian() {
        return this.olddaygeorgian;
    }

    public void setOlddaygeorgian( Integer olddaygeorgian ) {
        this.olddaygeorgian = olddaygeorgian;
    }

    @Column( name = "OLDMONTHGEORGIAN" )
    public Integer getOldmonthgeorgian() {
        return this.oldmonthgeorgian;
    }

    public void setOldmonthgeorgian( Integer oldmonthgeorgian ) {
        this.oldmonthgeorgian = oldmonthgeorgian;
    }

    @Column( name = "OLDYEARGEORGIAN" )
    public Integer getOldyeargeorgian() {
        return this.oldyeargeorgian;
    }

    public void setOldyeargeorgian( Integer oldyeargeorgian ) {
        this.oldyeargeorgian = oldyeargeorgian;
    }

    @Column( name = "COURTFR", length = 128 )
    public String getCourtfr() {
        return this.courtfr;
    }

    public void setCourtfr( String courtfr ) {
        this.courtfr = courtfr;
    }

    @Column( name = "MENTIONOFFICERAR", length = 128 )
    public String getMentionofficerar() {
        return this.mentionofficerar;
    }

    public void setMentionofficerar( String mentionofficerar ) {
        this.mentionofficerar = mentionofficerar;
    }

    @Column( name = "MENTIONOFFICERFR", length = 128 )
    public String getMentionofficerfr() {
        return this.mentionofficerfr;
    }

    public void setMentionofficerfr( String mentionofficerfr ) {
        this.mentionofficerfr = mentionofficerfr;
    }

}
