package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ChthibiRegister generated by hbm2java
 */
@Entity
@Table( name = "chthibi_register", catalog = "vitalstatistics", uniqueConstraints = @UniqueConstraint( columnNames = {
        "IDTYPE", "IDDISTRICT", "IDANNEX", "YEAR", "NUMBER" } ) )
public class ChthibiRegister implements java.io.Serializable {

    private Integer           id;
    private Integer           idtype;
    private Integer           iddistrict;
    private Integer           idannex;
    private Integer           year;
    private Integer           number;
    private Integer           pagescount;
    private String            editorfrench;
    private String            editorarabic;
    private Date              date;
    private int               daygeorgian;
    private int               monthgeorgian;
    private int               yeargeorgian;
    private int               dayhijri;
    private int               monthhijri;
    private int               yearhijri;
    private int               iduser;
    private int               valid;
    private Set<ChthibiBirth> chthibiBirths = new HashSet<ChthibiBirth>( 0 );

    public ChthibiRegister() {
    }

    public ChthibiRegister( int daygeorgian, int monthgeorgian, int yeargeorgian, int dayhijri, int monthhijri,
            int yearhijri, int iduser, int valid ) {
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.iduser = iduser;
        this.valid = valid;
    }

    public ChthibiRegister( Integer idtype, Integer iddistrict, Integer idannex, Integer year, Integer number,
            Integer pagescount, String editorfrench, String editorarabic, Date date, int daygeorgian, int monthgeorgian,
            int yeargeorgian, int dayhijri, int monthhijri, int yearhijri, int iduser, int valid,
            Set<ChthibiBirth> chthibiBirths ) {
        this.idtype = idtype;
        this.iddistrict = iddistrict;
        this.idannex = idannex;
        this.year = year;
        this.number = number;
        this.pagescount = pagescount;
        this.editorfrench = editorfrench;
        this.editorarabic = editorarabic;
        this.date = date;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.iduser = iduser;
        this.valid = valid;
        this.chthibiBirths = chthibiBirths;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "IDTYPE" )
    public Integer getIdtype() {
        return this.idtype;
    }

    public void setIdtype( Integer idtype ) {
        this.idtype = idtype;
    }

    @Column( name = "IDDISTRICT" )
    public Integer getIddistrict() {
        return this.iddistrict;
    }

    public void setIddistrict( Integer iddistrict ) {
        this.iddistrict = iddistrict;
    }

    @Column( name = "IDANNEX" )
    public Integer getIdannex() {
        return this.idannex;
    }

    public void setIdannex( Integer idannex ) {
        this.idannex = idannex;
    }

    @Column( name = "YEAR" )
    public Integer getYear() {
        return this.year;
    }

    public void setYear( Integer year ) {
        this.year = year;
    }

    @Column( name = "NUMBER" )
    public Integer getNumber() {
        return this.number;
    }

    public void setNumber( Integer number ) {
        this.number = number;
    }

    @Column( name = "PAGESCOUNT" )
    public Integer getPagescount() {
        return this.pagescount;
    }

    public void setPagescount( Integer pagescount ) {
        this.pagescount = pagescount;
    }

    @Column( name = "EDITORFRENCH", length = 64 )
    public String getEditorfrench() {
        return this.editorfrench;
    }

    public void setEditorfrench( String editorfrench ) {
        this.editorfrench = editorfrench;
    }

    @Column( name = "EDITORARABIC", length = 64 )
    public String getEditorarabic() {
        return this.editorarabic;
    }

    public void setEditorarabic( String editorarabic ) {
        this.editorarabic = editorarabic;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "DATE", length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "DAYGEORGIAN", nullable = false )
    public int getDaygeorgian() {
        return this.daygeorgian;
    }

    public void setDaygeorgian( int daygeorgian ) {
        this.daygeorgian = daygeorgian;
    }

    @Column( name = "MONTHGEORGIAN", nullable = false )
    public int getMonthgeorgian() {
        return this.monthgeorgian;
    }

    public void setMonthgeorgian( int monthgeorgian ) {
        this.monthgeorgian = monthgeorgian;
    }

    @Column( name = "YEARGEORGIAN", nullable = false )
    public int getYeargeorgian() {
        return this.yeargeorgian;
    }

    public void setYeargeorgian( int yeargeorgian ) {
        this.yeargeorgian = yeargeorgian;
    }

    @Column( name = "DAYHIJRI", nullable = false )
    public int getDayhijri() {
        return this.dayhijri;
    }

    public void setDayhijri( int dayhijri ) {
        this.dayhijri = dayhijri;
    }

    @Column( name = "MONTHHIJRI", nullable = false )
    public int getMonthhijri() {
        return this.monthhijri;
    }

    public void setMonthhijri( int monthhijri ) {
        this.monthhijri = monthhijri;
    }

    @Column( name = "YEARHIJRI", nullable = false )
    public int getYearhijri() {
        return this.yearhijri;
    }

    public void setYearhijri( int yearhijri ) {
        this.yearhijri = yearhijri;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "chthibiRegister" )
    public Set<ChthibiBirth> getChthibiBirths() {
        return this.chthibiBirths;
    }

    public void setChthibiBirths( Set<ChthibiBirth> chthibiBirths ) {
        this.chthibiBirths = chthibiBirths;
    }

    @Override
    public String toString() {
        return "ChthibiRegister [id=" + id + ", idtype=" + idtype + ", iddistrict=" + iddistrict + ", idannex="
                + idannex + ", year=" + year + ", number=" + number + ", pagescount=" + pagescount + ", editorfrench="
                + editorfrench + ", editorarabic=" + editorarabic + ", date=" + date + ", daygeorgian=" + daygeorgian
                + ", monthgeorgian=" + monthgeorgian + ", yeargeorgian=" + yeargeorgian + ", dayhijri=" + dayhijri
                + ", monthhijri=" + monthhijri + ", yearhijri=" + yearhijri + ", iduser=" + iduser + ", valid=" + valid
                + ", chthibiBirths=" + chthibiBirths + "]";
    }

}
