package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChthibiBirthHistory generated by hbm2java
 */
@Entity
@Table( name = "chthibi_birth_history", catalog = "vitalstatistics" )
public class ChthibiBirthHistory implements java.io.Serializable {

    private Integer id;
    private int     number;
    private int     idbirth;
    private int     iddistrict;
    private int     idannex;
    private int     idregister;
    private String  firstnamefrench;
    private String  firstnamearabic;
    private String  lastnamefrench;
    private String  lastnamearabic;
    private String  localfrench;
    private String  localarabic;
    private int     daygeorgian;
    private int     monthgeorgian;
    private int     yeargeorgian;
    private int     dayhijri;
    private int     monthhijri;
    private int     yearhijri;
    private Integer hour;
    private Integer minute;
    private int     sex;
    private Integer twin;
    private String  fatherfirstnamefrench;
    private String  fatherfirstnamearabic;
    private String  fathernationalityfrench;
    private String  fathernationalityarabic;
    private String  fatherjobfrench;
    private String  fatherjobarabic;
    private String  fatherlocalfrench;
    private String  fatherlocalarabic;
    private int     fatherdaygeorgian;
    private int     fathermonthgeorgian;
    private int     fatheryeargeorgian;
    private int     fatherdayhijri;
    private int     fathermonthhijri;
    private int     fatheryearhijri;
    private Integer fatherdeath;
    private String  fatheradressfrench;
    private String  fatheradressarabic;
    private String  motherfirstnamefrench;
    private String  motherfirstnamearabic;
    private String  mothernationalityfrench;
    private String  mothernationalityarabic;
    private String  motherjobfrench;
    private String  motherjobarabic;
    private String  motherlocalfrench;
    private String  motherlocalarabic;
    private int     motherdaygeorgian;
    private int     mothermonthgeorgian;
    private int     motheryeargeorgian;
    private int     motherdayhijri;
    private int     mothermonthhijri;
    private int     motheryearhijri;
    private Integer motherdeath;
    private String  motheradressfrench;
    private String  motheradressarabic;
    private String  actundersignedfrench;
    private String  actundersignedarabic;
    private int     actdaygeorgian;
    private int     actmonthgeorgian;
    private int     actyeargeorgian;
    private int     actdayhijri;
    private int     actmonthhijri;
    private int     actyearhijri;
    private String  actjobfrench;
    private String  actjobarabic;
    private String  declarantnumber;
    private String  declarantfirstnamefrench;
    private String  declarantfirstnamearabic;
    private String  declarantrelationshipfrench;
    private String  declarantrelationshiparabic;
    private Integer declarantage;
    private String  declarantjobfrench;
    private String  declarantjobarabic;
    private String  declarantadressfrench;
    private String  declarantadressarabic;
    private String  judgementnumber;
    private String  judgementfilenumber;
    private String  judgementcourtfrench;
    private String  judgementcourtarabic;
    private Integer judgementyear;
    private int     judgementdaygeorgian;
    private int     judgementmonthgeorgian;
    private int     judgementyeargeorgian;
    private int     judgementdayhijri;
    private int     judgementmonthhijri;
    private int     judgementyearhijri;
    private Integer statementtype;
    private Date    date;
    private int     iduser;
    private int     valid;
    private Date    historydate;
    private Integer reghour;
    private Integer regminute;
    private String  ordernumber;
    private String  permissionnumber;
    private String  declarantnationalityarabic;
    private String  declarantnationalityfrench;
    private Integer rank;
    private String  fathereducationlevel;
    private String  mothereducationlevel;
    private String  residencecityarabic;
    private String  residencecityfrench;
    private String  nationalityarabic;
    private String  nationalityfrench;
    private int     istranscripted;
    private String  transcriptionorigine;
    private Integer transcriptiondaygeorgian;
    private Integer transcriptionmonthgeorgian;
    private Integer transcriptionyeargeorgian;
    private Integer transcriptiondayhijri;
    private Integer transcriptionmonthhijri;
    private Integer transcriptionyearhijri;
    private String  birthcityarabic;
    private String  birthcityfrench;
    private String  foldernumber;
    private Integer transcdemandedaygeorgian;
    private Integer transcdemandemonthgeorgian;
    private Integer transcdemandeyeargeorgian;
    private Integer transcdemandedayhijri;
    private Integer transcdemandemonthhijri;
    private Integer transcdemandeyearhijri;
    private String  transcactundersignedarabic;
    private String  transcactundersignedfrench;
    private String  transcactjobarabic;
    private String  transcactjobfrench;
    private Integer transcactdaygeorgian;
    private Integer transcactmonthgeorgian;
    private Integer transcactyeargeorgian;
    private Integer transcactdayhijri;
    private Integer transcactmonthhijri;
    private Integer transcactyearhijri;
    private String  transcactoriginearabic;
    private String  transcactoriginefrench;
    private String  transcdemandewhoarabic;
    private String  transcdemandewhofrench;
    private Integer transcoriginenumber;
    private int     isabondoned;
    private String  firstnamemarginar;
    private String  firstnamemarginfr;
    private String  lastnamemarginar;
    private String  lastnamemarginfr;
    private int     isproblem;
    private String  comment;

    public ChthibiBirthHistory() {
    }

    public ChthibiBirthHistory( int number, int idbirth, int iddistrict, int idannex, int idregister, int daygeorgian,
            int monthgeorgian, int yeargeorgian, int dayhijri, int monthhijri, int yearhijri, int sex,
            int fatherdaygeorgian, int fathermonthgeorgian, int fatheryeargeorgian, int fatherdayhijri,
            int fathermonthhijri, int fatheryearhijri, int motherdaygeorgian, int mothermonthgeorgian,
            int motheryeargeorgian, int motherdayhijri, int mothermonthhijri, int motheryearhijri, int actdaygeorgian,
            int actmonthgeorgian, int actyeargeorgian, int actdayhijri, int actmonthhijri, int actyearhijri,
            int judgementdaygeorgian, int judgementmonthgeorgian, int judgementyeargeorgian, int judgementdayhijri,
            int judgementmonthhijri, int judgementyearhijri, int iduser, int valid, int istranscripted, int isabondoned,
            int isproblem ) {
        this.number = number;
        this.idbirth = idbirth;
        this.iddistrict = iddistrict;
        this.idannex = idannex;
        this.idregister = idregister;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.sex = sex;
        this.fatherdaygeorgian = fatherdaygeorgian;
        this.fathermonthgeorgian = fathermonthgeorgian;
        this.fatheryeargeorgian = fatheryeargeorgian;
        this.fatherdayhijri = fatherdayhijri;
        this.fathermonthhijri = fathermonthhijri;
        this.fatheryearhijri = fatheryearhijri;
        this.motherdaygeorgian = motherdaygeorgian;
        this.mothermonthgeorgian = mothermonthgeorgian;
        this.motheryeargeorgian = motheryeargeorgian;
        this.motherdayhijri = motherdayhijri;
        this.mothermonthhijri = mothermonthhijri;
        this.motheryearhijri = motheryearhijri;
        this.actdaygeorgian = actdaygeorgian;
        this.actmonthgeorgian = actmonthgeorgian;
        this.actyeargeorgian = actyeargeorgian;
        this.actdayhijri = actdayhijri;
        this.actmonthhijri = actmonthhijri;
        this.actyearhijri = actyearhijri;
        this.judgementdaygeorgian = judgementdaygeorgian;
        this.judgementmonthgeorgian = judgementmonthgeorgian;
        this.judgementyeargeorgian = judgementyeargeorgian;
        this.judgementdayhijri = judgementdayhijri;
        this.judgementmonthhijri = judgementmonthhijri;
        this.judgementyearhijri = judgementyearhijri;
        this.iduser = iduser;
        this.valid = valid;
        this.istranscripted = istranscripted;
        this.isabondoned = isabondoned;
        this.isproblem = isproblem;
    }

    public ChthibiBirthHistory( int number, int idbirth, int iddistrict, int idannex, int idregister,
            String firstnamefrench, String firstnamearabic, String lastnamefrench, String lastnamearabic,
            String localfrench, String localarabic, int daygeorgian, int monthgeorgian, int yeargeorgian, int dayhijri,
            int monthhijri, int yearhijri, Integer hour, Integer minute, int sex, Integer twin,
            String fatherfirstnamefrench, String fatherfirstnamearabic, String fathernationalityfrench,
            String fathernationalityarabic, String fatherjobfrench, String fatherjobarabic, String fatherlocalfrench,
            String fatherlocalarabic, int fatherdaygeorgian, int fathermonthgeorgian, int fatheryeargeorgian,
            int fatherdayhijri, int fathermonthhijri, int fatheryearhijri, Integer fatherdeath,
            String fatheradressfrench, String fatheradressarabic, String motherfirstnamefrench,
            String motherfirstnamearabic, String mothernationalityfrench, String mothernationalityarabic,
            String motherjobfrench, String motherjobarabic, String motherlocalfrench, String motherlocalarabic,
            int motherdaygeorgian, int mothermonthgeorgian, int motheryeargeorgian, int motherdayhijri,
            int mothermonthhijri, int motheryearhijri, Integer motherdeath, String motheradressfrench,
            String motheradressarabic, String actundersignedfrench, String actundersignedarabic, int actdaygeorgian,
            int actmonthgeorgian, int actyeargeorgian, int actdayhijri, int actmonthhijri, int actyearhijri,
            String actjobfrench, String actjobarabic, String declarantnumber, String declarantfirstnamefrench,
            String declarantfirstnamearabic, String declarantrelationshipfrench, String declarantrelationshiparabic,
            Integer declarantage, String declarantjobfrench, String declarantjobarabic, String declarantadressfrench,
            String declarantadressarabic, String judgementnumber, String judgementfilenumber,
            String judgementcourtfrench, String judgementcourtarabic, Integer judgementyear, int judgementdaygeorgian,
            int judgementmonthgeorgian, int judgementyeargeorgian, int judgementdayhijri, int judgementmonthhijri,
            int judgementyearhijri, Integer statementtype, Date date, int iduser, int valid, Date historydate,
            Integer reghour, Integer regminute, String ordernumber, String permissionnumber,
            String declarantnationalityarabic, String declarantnationalityfrench, Integer rank,
            String fathereducationlevel, String mothereducationlevel, String residencecityarabic,
            String residencecityfrench, String nationalityarabic, String nationalityfrench, int istranscripted,
            String transcriptionorigine, Integer transcriptiondaygeorgian, Integer transcriptionmonthgeorgian,
            Integer transcriptionyeargeorgian, Integer transcriptiondayhijri, Integer transcriptionmonthhijri,
            Integer transcriptionyearhijri, String birthcityarabic, String birthcityfrench, String foldernumber,
            Integer transcdemandedaygeorgian, Integer transcdemandemonthgeorgian, Integer transcdemandeyeargeorgian,
            Integer transcdemandedayhijri, Integer transcdemandemonthhijri, Integer transcdemandeyearhijri,
            String transcactundersignedarabic, String transcactundersignedfrench, String transcactjobarabic,
            String transcactjobfrench, Integer transcactdaygeorgian, Integer transcactmonthgeorgian,
            Integer transcactyeargeorgian, Integer transcactdayhijri, Integer transcactmonthhijri,
            Integer transcactyearhijri, String transcactoriginearabic, String transcactoriginefrench,
            String transcdemandewhoarabic, String transcdemandewhofrench, Integer transcoriginenumber, int isabondoned,
            String firstnamemarginar, String firstnamemarginfr, String lastnamemarginar, String lastnamemarginfr,
            int isproblem, String comment ) {
        this.number = number;
        this.idbirth = idbirth;
        this.iddistrict = iddistrict;
        this.idannex = idannex;
        this.idregister = idregister;
        this.firstnamefrench = firstnamefrench;
        this.firstnamearabic = firstnamearabic;
        this.lastnamefrench = lastnamefrench;
        this.lastnamearabic = lastnamearabic;
        this.localfrench = localfrench;
        this.localarabic = localarabic;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.hour = hour;
        this.minute = minute;
        this.sex = sex;
        this.twin = twin;
        this.fatherfirstnamefrench = fatherfirstnamefrench;
        this.fatherfirstnamearabic = fatherfirstnamearabic;
        this.fathernationalityfrench = fathernationalityfrench;
        this.fathernationalityarabic = fathernationalityarabic;
        this.fatherjobfrench = fatherjobfrench;
        this.fatherjobarabic = fatherjobarabic;
        this.fatherlocalfrench = fatherlocalfrench;
        this.fatherlocalarabic = fatherlocalarabic;
        this.fatherdaygeorgian = fatherdaygeorgian;
        this.fathermonthgeorgian = fathermonthgeorgian;
        this.fatheryeargeorgian = fatheryeargeorgian;
        this.fatherdayhijri = fatherdayhijri;
        this.fathermonthhijri = fathermonthhijri;
        this.fatheryearhijri = fatheryearhijri;
        this.fatherdeath = fatherdeath;
        this.fatheradressfrench = fatheradressfrench;
        this.fatheradressarabic = fatheradressarabic;
        this.motherfirstnamefrench = motherfirstnamefrench;
        this.motherfirstnamearabic = motherfirstnamearabic;
        this.mothernationalityfrench = mothernationalityfrench;
        this.mothernationalityarabic = mothernationalityarabic;
        this.motherjobfrench = motherjobfrench;
        this.motherjobarabic = motherjobarabic;
        this.motherlocalfrench = motherlocalfrench;
        this.motherlocalarabic = motherlocalarabic;
        this.motherdaygeorgian = motherdaygeorgian;
        this.mothermonthgeorgian = mothermonthgeorgian;
        this.motheryeargeorgian = motheryeargeorgian;
        this.motherdayhijri = motherdayhijri;
        this.mothermonthhijri = mothermonthhijri;
        this.motheryearhijri = motheryearhijri;
        this.motherdeath = motherdeath;
        this.motheradressfrench = motheradressfrench;
        this.motheradressarabic = motheradressarabic;
        this.actundersignedfrench = actundersignedfrench;
        this.actundersignedarabic = actundersignedarabic;
        this.actdaygeorgian = actdaygeorgian;
        this.actmonthgeorgian = actmonthgeorgian;
        this.actyeargeorgian = actyeargeorgian;
        this.actdayhijri = actdayhijri;
        this.actmonthhijri = actmonthhijri;
        this.actyearhijri = actyearhijri;
        this.actjobfrench = actjobfrench;
        this.actjobarabic = actjobarabic;
        this.declarantnumber = declarantnumber;
        this.declarantfirstnamefrench = declarantfirstnamefrench;
        this.declarantfirstnamearabic = declarantfirstnamearabic;
        this.declarantrelationshipfrench = declarantrelationshipfrench;
        this.declarantrelationshiparabic = declarantrelationshiparabic;
        this.declarantage = declarantage;
        this.declarantjobfrench = declarantjobfrench;
        this.declarantjobarabic = declarantjobarabic;
        this.declarantadressfrench = declarantadressfrench;
        this.declarantadressarabic = declarantadressarabic;
        this.judgementnumber = judgementnumber;
        this.judgementfilenumber = judgementfilenumber;
        this.judgementcourtfrench = judgementcourtfrench;
        this.judgementcourtarabic = judgementcourtarabic;
        this.judgementyear = judgementyear;
        this.judgementdaygeorgian = judgementdaygeorgian;
        this.judgementmonthgeorgian = judgementmonthgeorgian;
        this.judgementyeargeorgian = judgementyeargeorgian;
        this.judgementdayhijri = judgementdayhijri;
        this.judgementmonthhijri = judgementmonthhijri;
        this.judgementyearhijri = judgementyearhijri;
        this.statementtype = statementtype;
        this.date = date;
        this.iduser = iduser;
        this.valid = valid;
        this.historydate = historydate;
        this.reghour = reghour;
        this.regminute = regminute;
        this.ordernumber = ordernumber;
        this.permissionnumber = permissionnumber;
        this.declarantnationalityarabic = declarantnationalityarabic;
        this.declarantnationalityfrench = declarantnationalityfrench;
        this.rank = rank;
        this.fathereducationlevel = fathereducationlevel;
        this.mothereducationlevel = mothereducationlevel;
        this.residencecityarabic = residencecityarabic;
        this.residencecityfrench = residencecityfrench;
        this.nationalityarabic = nationalityarabic;
        this.nationalityfrench = nationalityfrench;
        this.istranscripted = istranscripted;
        this.transcriptionorigine = transcriptionorigine;
        this.transcriptiondaygeorgian = transcriptiondaygeorgian;
        this.transcriptionmonthgeorgian = transcriptionmonthgeorgian;
        this.transcriptionyeargeorgian = transcriptionyeargeorgian;
        this.transcriptiondayhijri = transcriptiondayhijri;
        this.transcriptionmonthhijri = transcriptionmonthhijri;
        this.transcriptionyearhijri = transcriptionyearhijri;
        this.birthcityarabic = birthcityarabic;
        this.birthcityfrench = birthcityfrench;
        this.foldernumber = foldernumber;
        this.transcdemandedaygeorgian = transcdemandedaygeorgian;
        this.transcdemandemonthgeorgian = transcdemandemonthgeorgian;
        this.transcdemandeyeargeorgian = transcdemandeyeargeorgian;
        this.transcdemandedayhijri = transcdemandedayhijri;
        this.transcdemandemonthhijri = transcdemandemonthhijri;
        this.transcdemandeyearhijri = transcdemandeyearhijri;
        this.transcactundersignedarabic = transcactundersignedarabic;
        this.transcactundersignedfrench = transcactundersignedfrench;
        this.transcactjobarabic = transcactjobarabic;
        this.transcactjobfrench = transcactjobfrench;
        this.transcactdaygeorgian = transcactdaygeorgian;
        this.transcactmonthgeorgian = transcactmonthgeorgian;
        this.transcactyeargeorgian = transcactyeargeorgian;
        this.transcactdayhijri = transcactdayhijri;
        this.transcactmonthhijri = transcactmonthhijri;
        this.transcactyearhijri = transcactyearhijri;
        this.transcactoriginearabic = transcactoriginearabic;
        this.transcactoriginefrench = transcactoriginefrench;
        this.transcdemandewhoarabic = transcdemandewhoarabic;
        this.transcdemandewhofrench = transcdemandewhofrench;
        this.transcoriginenumber = transcoriginenumber;
        this.isabondoned = isabondoned;
        this.firstnamemarginar = firstnamemarginar;
        this.firstnamemarginfr = firstnamemarginfr;
        this.lastnamemarginar = lastnamemarginar;
        this.lastnamemarginfr = lastnamemarginfr;
        this.isproblem = isproblem;
        this.comment = comment;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "NUMBER", nullable = false )
    public int getNumber() {
        return this.number;
    }

    public void setNumber( int number ) {
        this.number = number;
    }

    @Column( name = "IDBIRTH", nullable = false )
    public int getIdbirth() {
        return this.idbirth;
    }

    public void setIdbirth( int idbirth ) {
        this.idbirth = idbirth;
    }

    @Column( name = "IDDISTRICT", nullable = false )
    public int getIddistrict() {
        return this.iddistrict;
    }

    public void setIddistrict( int iddistrict ) {
        this.iddistrict = iddistrict;
    }

    @Column( name = "IDANNEX", nullable = false )
    public int getIdannex() {
        return this.idannex;
    }

    public void setIdannex( int idannex ) {
        this.idannex = idannex;
    }

    @Column( name = "IDREGISTER", nullable = false )
    public int getIdregister() {
        return this.idregister;
    }

    public void setIdregister( int idregister ) {
        this.idregister = idregister;
    }

    @Column( name = "FIRSTNAMEFRENCH", length = 128 )
    public String getFirstnamefrench() {
        return this.firstnamefrench;
    }

    public void setFirstnamefrench( String firstnamefrench ) {
        this.firstnamefrench = firstnamefrench;
    }

    @Column( name = "FIRSTNAMEARABIC", length = 128 )
    public String getFirstnamearabic() {
        return this.firstnamearabic;
    }

    public void setFirstnamearabic( String firstnamearabic ) {
        this.firstnamearabic = firstnamearabic;
    }

    @Column( name = "LASTNAMEFRENCH", length = 128 )
    public String getLastnamefrench() {
        return this.lastnamefrench;
    }

    public void setLastnamefrench( String lastnamefrench ) {
        this.lastnamefrench = lastnamefrench;
    }

    @Column( name = "LASTNAMEARABIC", length = 128 )
    public String getLastnamearabic() {
        return this.lastnamearabic;
    }

    public void setLastnamearabic( String lastnamearabic ) {
        this.lastnamearabic = lastnamearabic;
    }

    @Column( name = "LOCALFRENCH", length = 128 )
    public String getLocalfrench() {
        return this.localfrench;
    }

    public void setLocalfrench( String localfrench ) {
        this.localfrench = localfrench;
    }

    @Column( name = "LOCALARABIC", length = 128 )
    public String getLocalarabic() {
        return this.localarabic;
    }

    public void setLocalarabic( String localarabic ) {
        this.localarabic = localarabic;
    }

    @Column( name = "DAYGEORGIAN", nullable = false )
    public int getDaygeorgian() {
        return this.daygeorgian;
    }

    public void setDaygeorgian( int daygeorgian ) {
        this.daygeorgian = daygeorgian;
    }

    @Column( name = "MONTHGEORGIAN", nullable = false )
    public int getMonthgeorgian() {
        return this.monthgeorgian;
    }

    public void setMonthgeorgian( int monthgeorgian ) {
        this.monthgeorgian = monthgeorgian;
    }

    @Column( name = "YEARGEORGIAN", nullable = false )
    public int getYeargeorgian() {
        return this.yeargeorgian;
    }

    public void setYeargeorgian( int yeargeorgian ) {
        this.yeargeorgian = yeargeorgian;
    }

    @Column( name = "DAYHIJRI", nullable = false )
    public int getDayhijri() {
        return this.dayhijri;
    }

    public void setDayhijri( int dayhijri ) {
        this.dayhijri = dayhijri;
    }

    @Column( name = "MONTHHIJRI", nullable = false )
    public int getMonthhijri() {
        return this.monthhijri;
    }

    public void setMonthhijri( int monthhijri ) {
        this.monthhijri = monthhijri;
    }

    @Column( name = "YEARHIJRI", nullable = false )
    public int getYearhijri() {
        return this.yearhijri;
    }

    public void setYearhijri( int yearhijri ) {
        this.yearhijri = yearhijri;
    }

    @Column( name = "HOUR" )
    public Integer getHour() {
        return this.hour;
    }

    public void setHour( Integer hour ) {
        this.hour = hour;
    }

    @Column( name = "MINUTE" )
    public Integer getMinute() {
        return this.minute;
    }

    public void setMinute( Integer minute ) {
        this.minute = minute;
    }

    @Column( name = "SEX", nullable = false )
    public int getSex() {
        return this.sex;
    }

    public void setSex( int sex ) {
        this.sex = sex;
    }

    @Column( name = "TWIN" )
    public Integer getTwin() {
        return this.twin;
    }

    public void setTwin( Integer twin ) {
        this.twin = twin;
    }

    @Column( name = "FATHERFIRSTNAMEFRENCH", length = 128 )
    public String getFatherfirstnamefrench() {
        return this.fatherfirstnamefrench;
    }

    public void setFatherfirstnamefrench( String fatherfirstnamefrench ) {
        this.fatherfirstnamefrench = fatherfirstnamefrench;
    }

    @Column( name = "FATHERFIRSTNAMEARABIC", length = 128 )
    public String getFatherfirstnamearabic() {
        return this.fatherfirstnamearabic;
    }

    public void setFatherfirstnamearabic( String fatherfirstnamearabic ) {
        this.fatherfirstnamearabic = fatherfirstnamearabic;
    }

    @Column( name = "FATHERNATIONALITYFRENCH", length = 128 )
    public String getFathernationalityfrench() {
        return this.fathernationalityfrench;
    }

    public void setFathernationalityfrench( String fathernationalityfrench ) {
        this.fathernationalityfrench = fathernationalityfrench;
    }

    @Column( name = "FATHERNATIONALITYARABIC", length = 128 )
    public String getFathernationalityarabic() {
        return this.fathernationalityarabic;
    }

    public void setFathernationalityarabic( String fathernationalityarabic ) {
        this.fathernationalityarabic = fathernationalityarabic;
    }

    @Column( name = "FATHERJOBFRENCH", length = 128 )
    public String getFatherjobfrench() {
        return this.fatherjobfrench;
    }

    public void setFatherjobfrench( String fatherjobfrench ) {
        this.fatherjobfrench = fatherjobfrench;
    }

    @Column( name = "FATHERJOBARABIC", length = 128 )
    public String getFatherjobarabic() {
        return this.fatherjobarabic;
    }

    public void setFatherjobarabic( String fatherjobarabic ) {
        this.fatherjobarabic = fatherjobarabic;
    }

    @Column( name = "FATHERLOCALFRENCH", length = 128 )
    public String getFatherlocalfrench() {
        return this.fatherlocalfrench;
    }

    public void setFatherlocalfrench( String fatherlocalfrench ) {
        this.fatherlocalfrench = fatherlocalfrench;
    }

    @Column( name = "FATHERLOCALARABIC", length = 128 )
    public String getFatherlocalarabic() {
        return this.fatherlocalarabic;
    }

    public void setFatherlocalarabic( String fatherlocalarabic ) {
        this.fatherlocalarabic = fatherlocalarabic;
    }

    @Column( name = "FATHERDAYGEORGIAN", nullable = false )
    public int getFatherdaygeorgian() {
        return this.fatherdaygeorgian;
    }

    public void setFatherdaygeorgian( int fatherdaygeorgian ) {
        this.fatherdaygeorgian = fatherdaygeorgian;
    }

    @Column( name = "FATHERMONTHGEORGIAN", nullable = false )
    public int getFathermonthgeorgian() {
        return this.fathermonthgeorgian;
    }

    public void setFathermonthgeorgian( int fathermonthgeorgian ) {
        this.fathermonthgeorgian = fathermonthgeorgian;
    }

    @Column( name = "FATHERYEARGEORGIAN", nullable = false )
    public int getFatheryeargeorgian() {
        return this.fatheryeargeorgian;
    }

    public void setFatheryeargeorgian( int fatheryeargeorgian ) {
        this.fatheryeargeorgian = fatheryeargeorgian;
    }

    @Column( name = "FATHERDAYHIJRI", nullable = false )
    public int getFatherdayhijri() {
        return this.fatherdayhijri;
    }

    public void setFatherdayhijri( int fatherdayhijri ) {
        this.fatherdayhijri = fatherdayhijri;
    }

    @Column( name = "FATHERMONTHHIJRI", nullable = false )
    public int getFathermonthhijri() {
        return this.fathermonthhijri;
    }

    public void setFathermonthhijri( int fathermonthhijri ) {
        this.fathermonthhijri = fathermonthhijri;
    }

    @Column( name = "FATHERYEARHIJRI", nullable = false )
    public int getFatheryearhijri() {
        return this.fatheryearhijri;
    }

    public void setFatheryearhijri( int fatheryearhijri ) {
        this.fatheryearhijri = fatheryearhijri;
    }

    @Column( name = "FATHERDEATH" )
    public Integer getFatherdeath() {
        return this.fatherdeath;
    }

    public void setFatherdeath( Integer fatherdeath ) {
        this.fatherdeath = fatherdeath;
    }

    @Column( name = "FATHERADRESSFRENCH", length = 128 )
    public String getFatheradressfrench() {
        return this.fatheradressfrench;
    }

    public void setFatheradressfrench( String fatheradressfrench ) {
        this.fatheradressfrench = fatheradressfrench;
    }

    @Column( name = "FATHERADRESSARABIC", length = 128 )
    public String getFatheradressarabic() {
        return this.fatheradressarabic;
    }

    public void setFatheradressarabic( String fatheradressarabic ) {
        this.fatheradressarabic = fatheradressarabic;
    }

    @Column( name = "MOTHERFIRSTNAMEFRENCH", length = 128 )
    public String getMotherfirstnamefrench() {
        return this.motherfirstnamefrench;
    }

    public void setMotherfirstnamefrench( String motherfirstnamefrench ) {
        this.motherfirstnamefrench = motherfirstnamefrench;
    }

    @Column( name = "MOTHERFIRSTNAMEARABIC", length = 128 )
    public String getMotherfirstnamearabic() {
        return this.motherfirstnamearabic;
    }

    public void setMotherfirstnamearabic( String motherfirstnamearabic ) {
        this.motherfirstnamearabic = motherfirstnamearabic;
    }

    @Column( name = "MOTHERNATIONALITYFRENCH", length = 128 )
    public String getMothernationalityfrench() {
        return this.mothernationalityfrench;
    }

    public void setMothernationalityfrench( String mothernationalityfrench ) {
        this.mothernationalityfrench = mothernationalityfrench;
    }

    @Column( name = "MOTHERNATIONALITYARABIC", length = 128 )
    public String getMothernationalityarabic() {
        return this.mothernationalityarabic;
    }

    public void setMothernationalityarabic( String mothernationalityarabic ) {
        this.mothernationalityarabic = mothernationalityarabic;
    }

    @Column( name = "MOTHERJOBFRENCH", length = 128 )
    public String getMotherjobfrench() {
        return this.motherjobfrench;
    }

    public void setMotherjobfrench( String motherjobfrench ) {
        this.motherjobfrench = motherjobfrench;
    }

    @Column( name = "MOTHERJOBARABIC", length = 128 )
    public String getMotherjobarabic() {
        return this.motherjobarabic;
    }

    public void setMotherjobarabic( String motherjobarabic ) {
        this.motherjobarabic = motherjobarabic;
    }

    @Column( name = "MOTHERLOCALFRENCH", length = 128 )
    public String getMotherlocalfrench() {
        return this.motherlocalfrench;
    }

    public void setMotherlocalfrench( String motherlocalfrench ) {
        this.motherlocalfrench = motherlocalfrench;
    }

    @Column( name = "MOTHERLOCALARABIC", length = 128 )
    public String getMotherlocalarabic() {
        return this.motherlocalarabic;
    }

    public void setMotherlocalarabic( String motherlocalarabic ) {
        this.motherlocalarabic = motherlocalarabic;
    }

    @Column( name = "MOTHERDAYGEORGIAN", nullable = false )
    public int getMotherdaygeorgian() {
        return this.motherdaygeorgian;
    }

    public void setMotherdaygeorgian( int motherdaygeorgian ) {
        this.motherdaygeorgian = motherdaygeorgian;
    }

    @Column( name = "MOTHERMONTHGEORGIAN", nullable = false )
    public int getMothermonthgeorgian() {
        return this.mothermonthgeorgian;
    }

    public void setMothermonthgeorgian( int mothermonthgeorgian ) {
        this.mothermonthgeorgian = mothermonthgeorgian;
    }

    @Column( name = "MOTHERYEARGEORGIAN", nullable = false )
    public int getMotheryeargeorgian() {
        return this.motheryeargeorgian;
    }

    public void setMotheryeargeorgian( int motheryeargeorgian ) {
        this.motheryeargeorgian = motheryeargeorgian;
    }

    @Column( name = "MOTHERDAYHIJRI", nullable = false )
    public int getMotherdayhijri() {
        return this.motherdayhijri;
    }

    public void setMotherdayhijri( int motherdayhijri ) {
        this.motherdayhijri = motherdayhijri;
    }

    @Column( name = "MOTHERMONTHHIJRI", nullable = false )
    public int getMothermonthhijri() {
        return this.mothermonthhijri;
    }

    public void setMothermonthhijri( int mothermonthhijri ) {
        this.mothermonthhijri = mothermonthhijri;
    }

    @Column( name = "MOTHERYEARHIJRI", nullable = false )
    public int getMotheryearhijri() {
        return this.motheryearhijri;
    }

    public void setMotheryearhijri( int motheryearhijri ) {
        this.motheryearhijri = motheryearhijri;
    }

    @Column( name = "MOTHERDEATH" )
    public Integer getMotherdeath() {
        return this.motherdeath;
    }

    public void setMotherdeath( Integer motherdeath ) {
        this.motherdeath = motherdeath;
    }

    @Column( name = "MOTHERADRESSFRENCH", length = 128 )
    public String getMotheradressfrench() {
        return this.motheradressfrench;
    }

    public void setMotheradressfrench( String motheradressfrench ) {
        this.motheradressfrench = motheradressfrench;
    }

    @Column( name = "MOTHERADRESSARABIC", length = 128 )
    public String getMotheradressarabic() {
        return this.motheradressarabic;
    }

    public void setMotheradressarabic( String motheradressarabic ) {
        this.motheradressarabic = motheradressarabic;
    }

    @Column( name = "ACTUNDERSIGNEDFRENCH", length = 128 )
    public String getActundersignedfrench() {
        return this.actundersignedfrench;
    }

    public void setActundersignedfrench( String actundersignedfrench ) {
        this.actundersignedfrench = actundersignedfrench;
    }

    @Column( name = "ACTUNDERSIGNEDARABIC", length = 128 )
    public String getActundersignedarabic() {
        return this.actundersignedarabic;
    }

    public void setActundersignedarabic( String actundersignedarabic ) {
        this.actundersignedarabic = actundersignedarabic;
    }

    @Column( name = "ACTDAYGEORGIAN", nullable = false )
    public int getActdaygeorgian() {
        return this.actdaygeorgian;
    }

    public void setActdaygeorgian( int actdaygeorgian ) {
        this.actdaygeorgian = actdaygeorgian;
    }

    @Column( name = "ACTMONTHGEORGIAN", nullable = false )
    public int getActmonthgeorgian() {
        return this.actmonthgeorgian;
    }

    public void setActmonthgeorgian( int actmonthgeorgian ) {
        this.actmonthgeorgian = actmonthgeorgian;
    }

    @Column( name = "ACTYEARGEORGIAN", nullable = false )
    public int getActyeargeorgian() {
        return this.actyeargeorgian;
    }

    public void setActyeargeorgian( int actyeargeorgian ) {
        this.actyeargeorgian = actyeargeorgian;
    }

    @Column( name = "ACTDAYHIJRI", nullable = false )
    public int getActdayhijri() {
        return this.actdayhijri;
    }

    public void setActdayhijri( int actdayhijri ) {
        this.actdayhijri = actdayhijri;
    }

    @Column( name = "ACTMONTHHIJRI", nullable = false )
    public int getActmonthhijri() {
        return this.actmonthhijri;
    }

    public void setActmonthhijri( int actmonthhijri ) {
        this.actmonthhijri = actmonthhijri;
    }

    @Column( name = "ACTYEARHIJRI", nullable = false )
    public int getActyearhijri() {
        return this.actyearhijri;
    }

    public void setActyearhijri( int actyearhijri ) {
        this.actyearhijri = actyearhijri;
    }

    @Column( name = "ACTJOBFRENCH", length = 128 )
    public String getActjobfrench() {
        return this.actjobfrench;
    }

    public void setActjobfrench( String actjobfrench ) {
        this.actjobfrench = actjobfrench;
    }

    @Column( name = "ACTJOBARABIC", length = 128 )
    public String getActjobarabic() {
        return this.actjobarabic;
    }

    public void setActjobarabic( String actjobarabic ) {
        this.actjobarabic = actjobarabic;
    }

    @Column( name = "DECLARANTNUMBER", length = 128 )
    public String getDeclarantnumber() {
        return this.declarantnumber;
    }

    public void setDeclarantnumber( String declarantnumber ) {
        this.declarantnumber = declarantnumber;
    }

    @Column( name = "DECLARANTFIRSTNAMEFRENCH", length = 128 )
    public String getDeclarantfirstnamefrench() {
        return this.declarantfirstnamefrench;
    }

    public void setDeclarantfirstnamefrench( String declarantfirstnamefrench ) {
        this.declarantfirstnamefrench = declarantfirstnamefrench;
    }

    @Column( name = "DECLARANTFIRSTNAMEARABIC", length = 128 )
    public String getDeclarantfirstnamearabic() {
        return this.declarantfirstnamearabic;
    }

    public void setDeclarantfirstnamearabic( String declarantfirstnamearabic ) {
        this.declarantfirstnamearabic = declarantfirstnamearabic;
    }

    @Column( name = "DECLARANTRELATIONSHIPFRENCH", length = 128 )
    public String getDeclarantrelationshipfrench() {
        return this.declarantrelationshipfrench;
    }

    public void setDeclarantrelationshipfrench( String declarantrelationshipfrench ) {
        this.declarantrelationshipfrench = declarantrelationshipfrench;
    }

    @Column( name = "DECLARANTRELATIONSHIPARABIC", length = 128 )
    public String getDeclarantrelationshiparabic() {
        return this.declarantrelationshiparabic;
    }

    public void setDeclarantrelationshiparabic( String declarantrelationshiparabic ) {
        this.declarantrelationshiparabic = declarantrelationshiparabic;
    }

    @Column( name = "DECLARANTAGE" )
    public Integer getDeclarantage() {
        return this.declarantage;
    }

    public void setDeclarantage( Integer declarantage ) {
        this.declarantage = declarantage;
    }

    @Column( name = "DECLARANTJOBFRENCH", length = 128 )
    public String getDeclarantjobfrench() {
        return this.declarantjobfrench;
    }

    public void setDeclarantjobfrench( String declarantjobfrench ) {
        this.declarantjobfrench = declarantjobfrench;
    }

    @Column( name = "DECLARANTJOBARABIC", length = 128 )
    public String getDeclarantjobarabic() {
        return this.declarantjobarabic;
    }

    public void setDeclarantjobarabic( String declarantjobarabic ) {
        this.declarantjobarabic = declarantjobarabic;
    }

    @Column( name = "DECLARANTADRESSFRENCH", length = 128 )
    public String getDeclarantadressfrench() {
        return this.declarantadressfrench;
    }

    public void setDeclarantadressfrench( String declarantadressfrench ) {
        this.declarantadressfrench = declarantadressfrench;
    }

    @Column( name = "DECLARANTADRESSARABIC", length = 128 )
    public String getDeclarantadressarabic() {
        return this.declarantadressarabic;
    }

    public void setDeclarantadressarabic( String declarantadressarabic ) {
        this.declarantadressarabic = declarantadressarabic;
    }

    @Column( name = "JUDGEMENTNUMBER", length = 128 )
    public String getJudgementnumber() {
        return this.judgementnumber;
    }

    public void setJudgementnumber( String judgementnumber ) {
        this.judgementnumber = judgementnumber;
    }

    @Column( name = "JUDGEMENTFILENUMBER", length = 128 )
    public String getJudgementfilenumber() {
        return this.judgementfilenumber;
    }

    public void setJudgementfilenumber( String judgementfilenumber ) {
        this.judgementfilenumber = judgementfilenumber;
    }

    @Column( name = "JUDGEMENTCOURTFRENCH", length = 128 )
    public String getJudgementcourtfrench() {
        return this.judgementcourtfrench;
    }

    public void setJudgementcourtfrench( String judgementcourtfrench ) {
        this.judgementcourtfrench = judgementcourtfrench;
    }

    @Column( name = "JUDGEMENTCOURTARABIC", length = 128 )
    public String getJudgementcourtarabic() {
        return this.judgementcourtarabic;
    }

    public void setJudgementcourtarabic( String judgementcourtarabic ) {
        this.judgementcourtarabic = judgementcourtarabic;
    }

    @Column( name = "JUDGEMENTYEAR" )
    public Integer getJudgementyear() {
        return this.judgementyear;
    }

    public void setJudgementyear( Integer judgementyear ) {
        this.judgementyear = judgementyear;
    }

    @Column( name = "JUDGEMENTDAYGEORGIAN", nullable = false )
    public int getJudgementdaygeorgian() {
        return this.judgementdaygeorgian;
    }

    public void setJudgementdaygeorgian( int judgementdaygeorgian ) {
        this.judgementdaygeorgian = judgementdaygeorgian;
    }

    @Column( name = "JUDGEMENTMONTHGEORGIAN", nullable = false )
    public int getJudgementmonthgeorgian() {
        return this.judgementmonthgeorgian;
    }

    public void setJudgementmonthgeorgian( int judgementmonthgeorgian ) {
        this.judgementmonthgeorgian = judgementmonthgeorgian;
    }

    @Column( name = "JUDGEMENTYEARGEORGIAN", nullable = false )
    public int getJudgementyeargeorgian() {
        return this.judgementyeargeorgian;
    }

    public void setJudgementyeargeorgian( int judgementyeargeorgian ) {
        this.judgementyeargeorgian = judgementyeargeorgian;
    }

    @Column( name = "JUDGEMENTDAYHIJRI", nullable = false )
    public int getJudgementdayhijri() {
        return this.judgementdayhijri;
    }

    public void setJudgementdayhijri( int judgementdayhijri ) {
        this.judgementdayhijri = judgementdayhijri;
    }

    @Column( name = "JUDGEMENTMONTHHIJRI", nullable = false )
    public int getJudgementmonthhijri() {
        return this.judgementmonthhijri;
    }

    public void setJudgementmonthhijri( int judgementmonthhijri ) {
        this.judgementmonthhijri = judgementmonthhijri;
    }

    @Column( name = "JUDGEMENTYEARHIJRI", nullable = false )
    public int getJudgementyearhijri() {
        return this.judgementyearhijri;
    }

    public void setJudgementyearhijri( int judgementyearhijri ) {
        this.judgementyearhijri = judgementyearhijri;
    }

    @Column( name = "STATEMENTTYPE" )
    public Integer getStatementtype() {
        return this.statementtype;
    }

    public void setStatementtype( Integer statementtype ) {
        this.statementtype = statementtype;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "DATE", length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "HISTORYDATE", length = 19 )
    public Date getHistorydate() {
        return this.historydate;
    }

    public void setHistorydate( Date historydate ) {
        this.historydate = historydate;
    }

    @Column( name = "REGHOUR" )
    public Integer getReghour() {
        return this.reghour;
    }

    public void setReghour( Integer reghour ) {
        this.reghour = reghour;
    }

    @Column( name = "REGMINUTE" )
    public Integer getRegminute() {
        return this.regminute;
    }

    public void setRegminute( Integer regminute ) {
        this.regminute = regminute;
    }

    @Column( name = "ORDERNUMBER", length = 128 )
    public String getOrdernumber() {
        return this.ordernumber;
    }

    public void setOrdernumber( String ordernumber ) {
        this.ordernumber = ordernumber;
    }

    @Column( name = "PERMISSIONNUMBER", length = 128 )
    public String getPermissionnumber() {
        return this.permissionnumber;
    }

    public void setPermissionnumber( String permissionnumber ) {
        this.permissionnumber = permissionnumber;
    }

    @Column( name = "DECLARANTNATIONALITYARABIC", length = 128 )
    public String getDeclarantnationalityarabic() {
        return this.declarantnationalityarabic;
    }

    public void setDeclarantnationalityarabic( String declarantnationalityarabic ) {
        this.declarantnationalityarabic = declarantnationalityarabic;
    }

    @Column( name = "DECLARANTNATIONALITYFRENCH", length = 128 )
    public String getDeclarantnationalityfrench() {
        return this.declarantnationalityfrench;
    }

    public void setDeclarantnationalityfrench( String declarantnationalityfrench ) {
        this.declarantnationalityfrench = declarantnationalityfrench;
    }

    @Column( name = "RANK" )
    public Integer getRank() {
        return this.rank;
    }

    public void setRank( Integer rank ) {
        this.rank = rank;
    }

    @Column( name = "FATHEREDUCATIONLEVEL", length = 128 )
    public String getFathereducationlevel() {
        return this.fathereducationlevel;
    }

    public void setFathereducationlevel( String fathereducationlevel ) {
        this.fathereducationlevel = fathereducationlevel;
    }

    @Column( name = "MOTHEREDUCATIONLEVEL", length = 128 )
    public String getMothereducationlevel() {
        return this.mothereducationlevel;
    }

    public void setMothereducationlevel( String mothereducationlevel ) {
        this.mothereducationlevel = mothereducationlevel;
    }

    @Column( name = "RESIDENCECITYARABIC", length = 128 )
    public String getResidencecityarabic() {
        return this.residencecityarabic;
    }

    public void setResidencecityarabic( String residencecityarabic ) {
        this.residencecityarabic = residencecityarabic;
    }

    @Column( name = "RESIDENCECITYFRENCH", length = 128 )
    public String getResidencecityfrench() {
        return this.residencecityfrench;
    }

    public void setResidencecityfrench( String residencecityfrench ) {
        this.residencecityfrench = residencecityfrench;
    }

    @Column( name = "NATIONALITYARABIC", length = 128 )
    public String getNationalityarabic() {
        return this.nationalityarabic;
    }

    public void setNationalityarabic( String nationalityarabic ) {
        this.nationalityarabic = nationalityarabic;
    }

    @Column( name = "NATIONALITYFRENCH", length = 128 )
    public String getNationalityfrench() {
        return this.nationalityfrench;
    }

    public void setNationalityfrench( String nationalityfrench ) {
        this.nationalityfrench = nationalityfrench;
    }

    @Column( name = "ISTRANSCRIPTED", nullable = false )
    public int getIstranscripted() {
        return this.istranscripted;
    }

    public void setIstranscripted( int istranscripted ) {
        this.istranscripted = istranscripted;
    }

    @Column( name = "TRANSCRIPTIONORIGINE", length = 128 )
    public String getTranscriptionorigine() {
        return this.transcriptionorigine;
    }

    public void setTranscriptionorigine( String transcriptionorigine ) {
        this.transcriptionorigine = transcriptionorigine;
    }

    @Column( name = "TRANSCRIPTIONDAYGEORGIAN" )
    public Integer getTranscriptiondaygeorgian() {
        return this.transcriptiondaygeorgian;
    }

    public void setTranscriptiondaygeorgian( Integer transcriptiondaygeorgian ) {
        this.transcriptiondaygeorgian = transcriptiondaygeorgian;
    }

    @Column( name = "TRANSCRIPTIONMONTHGEORGIAN" )
    public Integer getTranscriptionmonthgeorgian() {
        return this.transcriptionmonthgeorgian;
    }

    public void setTranscriptionmonthgeorgian( Integer transcriptionmonthgeorgian ) {
        this.transcriptionmonthgeorgian = transcriptionmonthgeorgian;
    }

    @Column( name = "TRANSCRIPTIONYEARGEORGIAN" )
    public Integer getTranscriptionyeargeorgian() {
        return this.transcriptionyeargeorgian;
    }

    public void setTranscriptionyeargeorgian( Integer transcriptionyeargeorgian ) {
        this.transcriptionyeargeorgian = transcriptionyeargeorgian;
    }

    @Column( name = "TRANSCRIPTIONDAYHIJRI" )
    public Integer getTranscriptiondayhijri() {
        return this.transcriptiondayhijri;
    }

    public void setTranscriptiondayhijri( Integer transcriptiondayhijri ) {
        this.transcriptiondayhijri = transcriptiondayhijri;
    }

    @Column( name = "TRANSCRIPTIONMONTHHIJRI" )
    public Integer getTranscriptionmonthhijri() {
        return this.transcriptionmonthhijri;
    }

    public void setTranscriptionmonthhijri( Integer transcriptionmonthhijri ) {
        this.transcriptionmonthhijri = transcriptionmonthhijri;
    }

    @Column( name = "TRANSCRIPTIONYEARHIJRI" )
    public Integer getTranscriptionyearhijri() {
        return this.transcriptionyearhijri;
    }

    public void setTranscriptionyearhijri( Integer transcriptionyearhijri ) {
        this.transcriptionyearhijri = transcriptionyearhijri;
    }

    @Column( name = "BIRTHCITYARABIC", length = 128 )
    public String getBirthcityarabic() {
        return this.birthcityarabic;
    }

    public void setBirthcityarabic( String birthcityarabic ) {
        this.birthcityarabic = birthcityarabic;
    }

    @Column( name = "BIRTHCITYFRENCH", length = 128 )
    public String getBirthcityfrench() {
        return this.birthcityfrench;
    }

    public void setBirthcityfrench( String birthcityfrench ) {
        this.birthcityfrench = birthcityfrench;
    }

    @Column( name = "FOLDERNUMBER", length = 128 )
    public String getFoldernumber() {
        return this.foldernumber;
    }

    public void setFoldernumber( String foldernumber ) {
        this.foldernumber = foldernumber;
    }

    @Column( name = "TRANSCDEMANDEDAYGEORGIAN" )
    public Integer getTranscdemandedaygeorgian() {
        return this.transcdemandedaygeorgian;
    }

    public void setTranscdemandedaygeorgian( Integer transcdemandedaygeorgian ) {
        this.transcdemandedaygeorgian = transcdemandedaygeorgian;
    }

    @Column( name = "TRANSCDEMANDEMONTHGEORGIAN" )
    public Integer getTranscdemandemonthgeorgian() {
        return this.transcdemandemonthgeorgian;
    }

    public void setTranscdemandemonthgeorgian( Integer transcdemandemonthgeorgian ) {
        this.transcdemandemonthgeorgian = transcdemandemonthgeorgian;
    }

    @Column( name = "TRANSCDEMANDEYEARGEORGIAN" )
    public Integer getTranscdemandeyeargeorgian() {
        return this.transcdemandeyeargeorgian;
    }

    public void setTranscdemandeyeargeorgian( Integer transcdemandeyeargeorgian ) {
        this.transcdemandeyeargeorgian = transcdemandeyeargeorgian;
    }

    @Column( name = "TRANSCDEMANDEDAYHIJRI" )
    public Integer getTranscdemandedayhijri() {
        return this.transcdemandedayhijri;
    }

    public void setTranscdemandedayhijri( Integer transcdemandedayhijri ) {
        this.transcdemandedayhijri = transcdemandedayhijri;
    }

    @Column( name = "TRANSCDEMANDEMONTHHIJRI" )
    public Integer getTranscdemandemonthhijri() {
        return this.transcdemandemonthhijri;
    }

    public void setTranscdemandemonthhijri( Integer transcdemandemonthhijri ) {
        this.transcdemandemonthhijri = transcdemandemonthhijri;
    }

    @Column( name = "TRANSCDEMANDEYEARHIJRI" )
    public Integer getTranscdemandeyearhijri() {
        return this.transcdemandeyearhijri;
    }

    public void setTranscdemandeyearhijri( Integer transcdemandeyearhijri ) {
        this.transcdemandeyearhijri = transcdemandeyearhijri;
    }

    @Column( name = "TRANSCACTUNDERSIGNEDARABIC", length = 128 )
    public String getTranscactundersignedarabic() {
        return this.transcactundersignedarabic;
    }

    public void setTranscactundersignedarabic( String transcactundersignedarabic ) {
        this.transcactundersignedarabic = transcactundersignedarabic;
    }

    @Column( name = "TRANSCACTUNDERSIGNEDFRENCH", length = 128 )
    public String getTranscactundersignedfrench() {
        return this.transcactundersignedfrench;
    }

    public void setTranscactundersignedfrench( String transcactundersignedfrench ) {
        this.transcactundersignedfrench = transcactundersignedfrench;
    }

    @Column( name = "TRANSCACTJOBARABIC", length = 128 )
    public String getTranscactjobarabic() {
        return this.transcactjobarabic;
    }

    public void setTranscactjobarabic( String transcactjobarabic ) {
        this.transcactjobarabic = transcactjobarabic;
    }

    @Column( name = "TRANSCACTJOBFRENCH", length = 128 )
    public String getTranscactjobfrench() {
        return this.transcactjobfrench;
    }

    public void setTranscactjobfrench( String transcactjobfrench ) {
        this.transcactjobfrench = transcactjobfrench;
    }

    @Column( name = "TRANSCACTDAYGEORGIAN" )
    public Integer getTranscactdaygeorgian() {
        return this.transcactdaygeorgian;
    }

    public void setTranscactdaygeorgian( Integer transcactdaygeorgian ) {
        this.transcactdaygeorgian = transcactdaygeorgian;
    }

    @Column( name = "TRANSCACTMONTHGEORGIAN" )
    public Integer getTranscactmonthgeorgian() {
        return this.transcactmonthgeorgian;
    }

    public void setTranscactmonthgeorgian( Integer transcactmonthgeorgian ) {
        this.transcactmonthgeorgian = transcactmonthgeorgian;
    }

    @Column( name = "TRANSCACTYEARGEORGIAN" )
    public Integer getTranscactyeargeorgian() {
        return this.transcactyeargeorgian;
    }

    public void setTranscactyeargeorgian( Integer transcactyeargeorgian ) {
        this.transcactyeargeorgian = transcactyeargeorgian;
    }

    @Column( name = "TRANSCACTDAYHIJRI" )
    public Integer getTranscactdayhijri() {
        return this.transcactdayhijri;
    }

    public void setTranscactdayhijri( Integer transcactdayhijri ) {
        this.transcactdayhijri = transcactdayhijri;
    }

    @Column( name = "TRANSCACTMONTHHIJRI" )
    public Integer getTranscactmonthhijri() {
        return this.transcactmonthhijri;
    }

    public void setTranscactmonthhijri( Integer transcactmonthhijri ) {
        this.transcactmonthhijri = transcactmonthhijri;
    }

    @Column( name = "TRANSCACTYEARHIJRI" )
    public Integer getTranscactyearhijri() {
        return this.transcactyearhijri;
    }

    public void setTranscactyearhijri( Integer transcactyearhijri ) {
        this.transcactyearhijri = transcactyearhijri;
    }

    @Column( name = "TRANSCACTORIGINEARABIC", length = 128 )
    public String getTranscactoriginearabic() {
        return this.transcactoriginearabic;
    }

    public void setTranscactoriginearabic( String transcactoriginearabic ) {
        this.transcactoriginearabic = transcactoriginearabic;
    }

    @Column( name = "TRANSCACTORIGINEFRENCH", length = 128 )
    public String getTranscactoriginefrench() {
        return this.transcactoriginefrench;
    }

    public void setTranscactoriginefrench( String transcactoriginefrench ) {
        this.transcactoriginefrench = transcactoriginefrench;
    }

    @Column( name = "TRANSCDEMANDEWHOARABIC", length = 128 )
    public String getTranscdemandewhoarabic() {
        return this.transcdemandewhoarabic;
    }

    public void setTranscdemandewhoarabic( String transcdemandewhoarabic ) {
        this.transcdemandewhoarabic = transcdemandewhoarabic;
    }

    @Column( name = "TRANSCDEMANDEWHOFRENCH", length = 128 )
    public String getTranscdemandewhofrench() {
        return this.transcdemandewhofrench;
    }

    public void setTranscdemandewhofrench( String transcdemandewhofrench ) {
        this.transcdemandewhofrench = transcdemandewhofrench;
    }

    @Column( name = "TRANSCORIGINENUMBER" )
    public Integer getTranscoriginenumber() {
        return this.transcoriginenumber;
    }

    public void setTranscoriginenumber( Integer transcoriginenumber ) {
        this.transcoriginenumber = transcoriginenumber;
    }

    @Column( name = "ISABONDONED", nullable = false )
    public int getIsabondoned() {
        return this.isabondoned;
    }

    public void setIsabondoned( int isabondoned ) {
        this.isabondoned = isabondoned;
    }

    @Column( name = "FIRSTNAMEMARGINAR", length = 128 )
    public String getFirstnamemarginar() {
        return this.firstnamemarginar;
    }

    public void setFirstnamemarginar( String firstnamemarginar ) {
        this.firstnamemarginar = firstnamemarginar;
    }

    @Column( name = "FIRSTNAMEMARGINFR", length = 128 )
    public String getFirstnamemarginfr() {
        return this.firstnamemarginfr;
    }

    public void setFirstnamemarginfr( String firstnamemarginfr ) {
        this.firstnamemarginfr = firstnamemarginfr;
    }

    @Column( name = "LASTNAMEMARGINAR", length = 128 )
    public String getLastnamemarginar() {
        return this.lastnamemarginar;
    }

    public void setLastnamemarginar( String lastnamemarginar ) {
        this.lastnamemarginar = lastnamemarginar;
    }

    @Column( name = "LASTNAMEMARGINFR", length = 128 )
    public String getLastnamemarginfr() {
        return this.lastnamemarginfr;
    }

    public void setLastnamemarginfr( String lastnamemarginfr ) {
        this.lastnamemarginfr = lastnamemarginfr;
    }

    @Column( name = "ISPROBLEM", nullable = false )
    public int getIsproblem() {
        return this.isproblem;
    }

    public void setIsproblem( int isproblem ) {
        this.isproblem = isproblem;
    }

    @Column( name = "COMMENT", length = 65535 )
    public String getComment() {
        return this.comment;
    }

    public void setComment( String comment ) {
        this.comment = comment;
    }

}
