package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChthibiBirthResident generated by hbm2java
 */
@Entity
@Table( name = "chthibi_birth_resident", catalog = "vitalstatistics" )
public class ChthibiBirthResident implements java.io.Serializable {

    private Integer id;
    private int     number;
    private int     year;
    private String  district;
    private String  annex;
    private int     iddistrict;
    private int     idannex;
    private int     idregister;
    private String  firstnamefrench;
    private String  firstnamearabic;
    private String  lastnamefrench;
    private String  lastnamearabic;
    private String  localfrench;
    private String  localarabic;
    private int     daygeorgian;
    private int     monthgeorgian;
    private int     yeargeorgian;
    private int     dayhijri;
    private int     monthhijri;
    private int     yearhijri;
    private String  fatherfirstnamefrench;
    private String  fatherfirstnamearabic;
    private String  fathernationalityfrench;
    private String  fathernationalityarabic;
    private String  motherfirstnamefrench;
    private String  motherfirstnamearabic;
    private String  mothernationalityfrench;
    private String  mothernationalityarabic;
    private int     actdelivreddaygeorgian;
    private int     actdelivredmonthgeorgian;
    private int     actdelivredyeargeorgian;
    private int     actdelivreddayhijri;
    private int     actdelivredmonthhijri;
    private int     actdelivredyearhijri;
    private String  actundersignedfrench;
    private String  actundersignedarabic;
    private int     actdaygeorgian;
    private int     actmonthgeorgian;
    private int     actyeargeorgian;
    private int     actdayhijri;
    private int     actmonthhijri;
    private int     actyearhijri;
    private Date    date;
    private int     iduser;
    private int     valid;
    private Integer sex;
    private Integer birthactnumber;
    private Integer civilstatusnumber;
    private String  birthcommune;
    private String  residentadress;
    private String  residentadressfrench;
    private String  birthcommunefrench;
    private String  personne2;
    private String  personne2french;
    private String  adresse2;
    private String  adresse2french;

    public ChthibiBirthResident() {
    }

    public ChthibiBirthResident( int number, int year, int iddistrict, int idannex, int idregister, int daygeorgian,
            int monthgeorgian, int yeargeorgian, int dayhijri, int monthhijri, int yearhijri,
            int actdelivreddaygeorgian, int actdelivredmonthgeorgian, int actdelivredyeargeorgian,
            int actdelivreddayhijri, int actdelivredmonthhijri, int actdelivredyearhijri, int actdaygeorgian,
            int actmonthgeorgian, int actyeargeorgian, int actdayhijri, int actmonthhijri, int actyearhijri, int iduser,
            int valid ) {
        this.number = number;
        this.year = year;
        this.iddistrict = iddistrict;
        this.idannex = idannex;
        this.idregister = idregister;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.actdelivreddaygeorgian = actdelivreddaygeorgian;
        this.actdelivredmonthgeorgian = actdelivredmonthgeorgian;
        this.actdelivredyeargeorgian = actdelivredyeargeorgian;
        this.actdelivreddayhijri = actdelivreddayhijri;
        this.actdelivredmonthhijri = actdelivredmonthhijri;
        this.actdelivredyearhijri = actdelivredyearhijri;
        this.actdaygeorgian = actdaygeorgian;
        this.actmonthgeorgian = actmonthgeorgian;
        this.actyeargeorgian = actyeargeorgian;
        this.actdayhijri = actdayhijri;
        this.actmonthhijri = actmonthhijri;
        this.actyearhijri = actyearhijri;
        this.iduser = iduser;
        this.valid = valid;
    }

    public ChthibiBirthResident( int number, int year, String district, String annex, int iddistrict, int idannex,
            int idregister, String firstnamefrench, String firstnamearabic, String lastnamefrench,
            String lastnamearabic, String localfrench, String localarabic, int daygeorgian, int monthgeorgian,
            int yeargeorgian, int dayhijri, int monthhijri, int yearhijri, String fatherfirstnamefrench,
            String fatherfirstnamearabic, String fathernationalityfrench, String fathernationalityarabic,
            String motherfirstnamefrench, String motherfirstnamearabic, String mothernationalityfrench,
            String mothernationalityarabic, int actdelivreddaygeorgian, int actdelivredmonthgeorgian,
            int actdelivredyeargeorgian, int actdelivreddayhijri, int actdelivredmonthhijri, int actdelivredyearhijri,
            String actundersignedfrench, String actundersignedarabic, int actdaygeorgian, int actmonthgeorgian,
            int actyeargeorgian, int actdayhijri, int actmonthhijri, int actyearhijri, Date date, int iduser, int valid,
            Integer sex, Integer birthactnumber, Integer civilstatusnumber, String birthcommune, String residentadress,
            String residentadressfrench, String birthcommunefrench, String personne2, String personne2french,
            String adresse2, String adresse2french ) {
        this.number = number;
        this.year = year;
        this.district = district;
        this.annex = annex;
        this.iddistrict = iddistrict;
        this.idannex = idannex;
        this.idregister = idregister;
        this.firstnamefrench = firstnamefrench;
        this.firstnamearabic = firstnamearabic;
        this.lastnamefrench = lastnamefrench;
        this.lastnamearabic = lastnamearabic;
        this.localfrench = localfrench;
        this.localarabic = localarabic;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.dayhijri = dayhijri;
        this.monthhijri = monthhijri;
        this.yearhijri = yearhijri;
        this.fatherfirstnamefrench = fatherfirstnamefrench;
        this.fatherfirstnamearabic = fatherfirstnamearabic;
        this.fathernationalityfrench = fathernationalityfrench;
        this.fathernationalityarabic = fathernationalityarabic;
        this.motherfirstnamefrench = motherfirstnamefrench;
        this.motherfirstnamearabic = motherfirstnamearabic;
        this.mothernationalityfrench = mothernationalityfrench;
        this.mothernationalityarabic = mothernationalityarabic;
        this.actdelivreddaygeorgian = actdelivreddaygeorgian;
        this.actdelivredmonthgeorgian = actdelivredmonthgeorgian;
        this.actdelivredyeargeorgian = actdelivredyeargeorgian;
        this.actdelivreddayhijri = actdelivreddayhijri;
        this.actdelivredmonthhijri = actdelivredmonthhijri;
        this.actdelivredyearhijri = actdelivredyearhijri;
        this.actundersignedfrench = actundersignedfrench;
        this.actundersignedarabic = actundersignedarabic;
        this.actdaygeorgian = actdaygeorgian;
        this.actmonthgeorgian = actmonthgeorgian;
        this.actyeargeorgian = actyeargeorgian;
        this.actdayhijri = actdayhijri;
        this.actmonthhijri = actmonthhijri;
        this.actyearhijri = actyearhijri;
        this.date = date;
        this.iduser = iduser;
        this.valid = valid;
        this.sex = sex;
        this.birthactnumber = birthactnumber;
        this.civilstatusnumber = civilstatusnumber;
        this.birthcommune = birthcommune;
        this.residentadress = residentadress;
        this.residentadressfrench = residentadressfrench;
        this.birthcommunefrench = birthcommunefrench;
        this.personne2 = personne2;
        this.personne2french = personne2french;
        this.adresse2 = adresse2;
        this.adresse2french = adresse2french;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "NUMBER", nullable = false )
    public int getNumber() {
        return this.number;
    }

    public void setNumber( int number ) {
        this.number = number;
    }

    @Column( name = "YEAR", nullable = false )
    public int getYear() {
        return this.year;
    }

    public void setYear( int year ) {
        this.year = year;
    }

    @Column( name = "DISTRICT", length = 128 )
    public String getDistrict() {
        return this.district;
    }

    public void setDistrict( String district ) {
        this.district = district;
    }

    @Column( name = "ANNEX", length = 128 )
    public String getAnnex() {
        return this.annex;
    }

    public void setAnnex( String annex ) {
        this.annex = annex;
    }

    @Column( name = "IDDISTRICT", nullable = false )
    public int getIddistrict() {
        return this.iddistrict;
    }

    public void setIddistrict( int iddistrict ) {
        this.iddistrict = iddistrict;
    }

    @Column( name = "IDANNEX", nullable = false )
    public int getIdannex() {
        return this.idannex;
    }

    public void setIdannex( int idannex ) {
        this.idannex = idannex;
    }

    @Column( name = "IDREGISTER", nullable = false )
    public int getIdregister() {
        return this.idregister;
    }

    public void setIdregister( int idregister ) {
        this.idregister = idregister;
    }

    @Column( name = "FIRSTNAMEFRENCH", length = 128 )
    public String getFirstnamefrench() {
        return this.firstnamefrench;
    }

    public void setFirstnamefrench( String firstnamefrench ) {
        this.firstnamefrench = firstnamefrench;
    }

    @Column( name = "FIRSTNAMEARABIC", length = 128 )
    public String getFirstnamearabic() {
        return this.firstnamearabic;
    }

    public void setFirstnamearabic( String firstnamearabic ) {
        this.firstnamearabic = firstnamearabic;
    }

    @Column( name = "LASTNAMEFRENCH", length = 128 )
    public String getLastnamefrench() {
        return this.lastnamefrench;
    }

    public void setLastnamefrench( String lastnamefrench ) {
        this.lastnamefrench = lastnamefrench;
    }

    @Column( name = "LASTNAMEARABIC", length = 128 )
    public String getLastnamearabic() {
        return this.lastnamearabic;
    }

    public void setLastnamearabic( String lastnamearabic ) {
        this.lastnamearabic = lastnamearabic;
    }

    @Column( name = "LOCALFRENCH", length = 128 )
    public String getLocalfrench() {
        return this.localfrench;
    }

    public void setLocalfrench( String localfrench ) {
        this.localfrench = localfrench;
    }

    @Column( name = "LOCALARABIC", length = 128 )
    public String getLocalarabic() {
        return this.localarabic;
    }

    public void setLocalarabic( String localarabic ) {
        this.localarabic = localarabic;
    }

    @Column( name = "DAYGEORGIAN", nullable = false )
    public int getDaygeorgian() {
        return this.daygeorgian;
    }

    public void setDaygeorgian( int daygeorgian ) {
        this.daygeorgian = daygeorgian;
    }

    @Column( name = "MONTHGEORGIAN", nullable = false )
    public int getMonthgeorgian() {
        return this.monthgeorgian;
    }

    public void setMonthgeorgian( int monthgeorgian ) {
        this.monthgeorgian = monthgeorgian;
    }

    @Column( name = "YEARGEORGIAN", nullable = false )
    public int getYeargeorgian() {
        return this.yeargeorgian;
    }

    public void setYeargeorgian( int yeargeorgian ) {
        this.yeargeorgian = yeargeorgian;
    }

    @Column( name = "DAYHIJRI", nullable = false )
    public int getDayhijri() {
        return this.dayhijri;
    }

    public void setDayhijri( int dayhijri ) {
        this.dayhijri = dayhijri;
    }

    @Column( name = "MONTHHIJRI", nullable = false )
    public int getMonthhijri() {
        return this.monthhijri;
    }

    public void setMonthhijri( int monthhijri ) {
        this.monthhijri = monthhijri;
    }

    @Column( name = "YEARHIJRI", nullable = false )
    public int getYearhijri() {
        return this.yearhijri;
    }

    public void setYearhijri( int yearhijri ) {
        this.yearhijri = yearhijri;
    }

    @Column( name = "FATHERFIRSTNAMEFRENCH", length = 128 )
    public String getFatherfirstnamefrench() {
        return this.fatherfirstnamefrench;
    }

    public void setFatherfirstnamefrench( String fatherfirstnamefrench ) {
        this.fatherfirstnamefrench = fatherfirstnamefrench;
    }

    @Column( name = "FATHERFIRSTNAMEARABIC", length = 128 )
    public String getFatherfirstnamearabic() {
        return this.fatherfirstnamearabic;
    }

    public void setFatherfirstnamearabic( String fatherfirstnamearabic ) {
        this.fatherfirstnamearabic = fatherfirstnamearabic;
    }

    @Column( name = "FATHERNATIONALITYFRENCH", length = 128 )
    public String getFathernationalityfrench() {
        return this.fathernationalityfrench;
    }

    public void setFathernationalityfrench( String fathernationalityfrench ) {
        this.fathernationalityfrench = fathernationalityfrench;
    }

    @Column( name = "FATHERNATIONALITYARABIC", length = 128 )
    public String getFathernationalityarabic() {
        return this.fathernationalityarabic;
    }

    public void setFathernationalityarabic( String fathernationalityarabic ) {
        this.fathernationalityarabic = fathernationalityarabic;
    }

    @Column( name = "MOTHERFIRSTNAMEFRENCH", length = 128 )
    public String getMotherfirstnamefrench() {
        return this.motherfirstnamefrench;
    }

    public void setMotherfirstnamefrench( String motherfirstnamefrench ) {
        this.motherfirstnamefrench = motherfirstnamefrench;
    }

    @Column( name = "MOTHERFIRSTNAMEARABIC", length = 128 )
    public String getMotherfirstnamearabic() {
        return this.motherfirstnamearabic;
    }

    public void setMotherfirstnamearabic( String motherfirstnamearabic ) {
        this.motherfirstnamearabic = motherfirstnamearabic;
    }

    @Column( name = "MOTHERNATIONALITYFRENCH", length = 128 )
    public String getMothernationalityfrench() {
        return this.mothernationalityfrench;
    }

    public void setMothernationalityfrench( String mothernationalityfrench ) {
        this.mothernationalityfrench = mothernationalityfrench;
    }

    @Column( name = "MOTHERNATIONALITYARABIC", length = 128 )
    public String getMothernationalityarabic() {
        return this.mothernationalityarabic;
    }

    public void setMothernationalityarabic( String mothernationalityarabic ) {
        this.mothernationalityarabic = mothernationalityarabic;
    }

    @Column( name = "ACTDELIVREDDAYGEORGIAN", nullable = false )
    public int getActdelivreddaygeorgian() {
        return this.actdelivreddaygeorgian;
    }

    public void setActdelivreddaygeorgian( int actdelivreddaygeorgian ) {
        this.actdelivreddaygeorgian = actdelivreddaygeorgian;
    }

    @Column( name = "ACTDELIVREDMONTHGEORGIAN", nullable = false )
    public int getActdelivredmonthgeorgian() {
        return this.actdelivredmonthgeorgian;
    }

    public void setActdelivredmonthgeorgian( int actdelivredmonthgeorgian ) {
        this.actdelivredmonthgeorgian = actdelivredmonthgeorgian;
    }

    @Column( name = "ACTDELIVREDYEARGEORGIAN", nullable = false )
    public int getActdelivredyeargeorgian() {
        return this.actdelivredyeargeorgian;
    }

    public void setActdelivredyeargeorgian( int actdelivredyeargeorgian ) {
        this.actdelivredyeargeorgian = actdelivredyeargeorgian;
    }

    @Column( name = "ACTDELIVREDDAYHIJRI", nullable = false )
    public int getActdelivreddayhijri() {
        return this.actdelivreddayhijri;
    }

    public void setActdelivreddayhijri( int actdelivreddayhijri ) {
        this.actdelivreddayhijri = actdelivreddayhijri;
    }

    @Column( name = "ACTDELIVREDMONTHHIJRI", nullable = false )
    public int getActdelivredmonthhijri() {
        return this.actdelivredmonthhijri;
    }

    public void setActdelivredmonthhijri( int actdelivredmonthhijri ) {
        this.actdelivredmonthhijri = actdelivredmonthhijri;
    }

    @Column( name = "ACTDELIVREDYEARHIJRI", nullable = false )
    public int getActdelivredyearhijri() {
        return this.actdelivredyearhijri;
    }

    public void setActdelivredyearhijri( int actdelivredyearhijri ) {
        this.actdelivredyearhijri = actdelivredyearhijri;
    }

    @Column( name = "ACTUNDERSIGNEDFRENCH", length = 128 )
    public String getActundersignedfrench() {
        return this.actundersignedfrench;
    }

    public void setActundersignedfrench( String actundersignedfrench ) {
        this.actundersignedfrench = actundersignedfrench;
    }

    @Column( name = "ACTUNDERSIGNEDARABIC", length = 128 )
    public String getActundersignedarabic() {
        return this.actundersignedarabic;
    }

    public void setActundersignedarabic( String actundersignedarabic ) {
        this.actundersignedarabic = actundersignedarabic;
    }

    @Column( name = "ACTDAYGEORGIAN", nullable = false )
    public int getActdaygeorgian() {
        return this.actdaygeorgian;
    }

    public void setActdaygeorgian( int actdaygeorgian ) {
        this.actdaygeorgian = actdaygeorgian;
    }

    @Column( name = "ACTMONTHGEORGIAN", nullable = false )
    public int getActmonthgeorgian() {
        return this.actmonthgeorgian;
    }

    public void setActmonthgeorgian( int actmonthgeorgian ) {
        this.actmonthgeorgian = actmonthgeorgian;
    }

    @Column( name = "ACTYEARGEORGIAN", nullable = false )
    public int getActyeargeorgian() {
        return this.actyeargeorgian;
    }

    public void setActyeargeorgian( int actyeargeorgian ) {
        this.actyeargeorgian = actyeargeorgian;
    }

    @Column( name = "ACTDAYHIJRI", nullable = false )
    public int getActdayhijri() {
        return this.actdayhijri;
    }

    public void setActdayhijri( int actdayhijri ) {
        this.actdayhijri = actdayhijri;
    }

    @Column( name = "ACTMONTHHIJRI", nullable = false )
    public int getActmonthhijri() {
        return this.actmonthhijri;
    }

    public void setActmonthhijri( int actmonthhijri ) {
        this.actmonthhijri = actmonthhijri;
    }

    @Column( name = "ACTYEARHIJRI", nullable = false )
    public int getActyearhijri() {
        return this.actyearhijri;
    }

    public void setActyearhijri( int actyearhijri ) {
        this.actyearhijri = actyearhijri;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "DATE", length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @Column( name = "SEX" )
    public Integer getSex() {
        return this.sex;
    }

    public void setSex( Integer sex ) {
        this.sex = sex;
    }

    @Column( name = "BIRTHACTNUMBER" )
    public Integer getBirthactnumber() {
        return this.birthactnumber;
    }

    public void setBirthactnumber( Integer birthactnumber ) {
        this.birthactnumber = birthactnumber;
    }

    @Column( name = "CIVILSTATUSNUMBER" )
    public Integer getCivilstatusnumber() {
        return this.civilstatusnumber;
    }

    public void setCivilstatusnumber( Integer civilstatusnumber ) {
        this.civilstatusnumber = civilstatusnumber;
    }

    @Column( name = "BIRTHCOMMUNE", length = 128 )
    public String getBirthcommune() {
        return this.birthcommune;
    }

    public void setBirthcommune( String birthcommune ) {
        this.birthcommune = birthcommune;
    }

    @Column( name = "RESIDENTADRESS", length = 128 )
    public String getResidentadress() {
        return this.residentadress;
    }

    public void setResidentadress( String residentadress ) {
        this.residentadress = residentadress;
    }

    @Column( name = "RESIDENTADRESSFRENCH", length = 254 )
    public String getResidentadressfrench() {
        return this.residentadressfrench;
    }

    public void setResidentadressfrench( String residentadressfrench ) {
        this.residentadressfrench = residentadressfrench;
    }

    @Column( name = "BIRTHCOMMUNEFRENCH", length = 254 )
    public String getBirthcommunefrench() {
        return this.birthcommunefrench;
    }

    public void setBirthcommunefrench( String birthcommunefrench ) {
        this.birthcommunefrench = birthcommunefrench;
    }

    @Column( name = "PERSONNE2", length = 254 )
    public String getPersonne2() {
        return this.personne2;
    }

    public void setPersonne2( String personne2 ) {
        this.personne2 = personne2;
    }

    @Column( name = "PERSONNE2FRENCH", length = 254 )
    public String getPersonne2french() {
        return this.personne2french;
    }

    public void setPersonne2french( String personne2french ) {
        this.personne2french = personne2french;
    }

    @Column( name = "ADRESSE2", length = 254 )
    public String getAdresse2() {
        return this.adresse2;
    }

    public void setAdresse2( String adresse2 ) {
        this.adresse2 = adresse2;
    }

    @Column( name = "ADRESSE2FRENCH", length = 254 )
    public String getAdresse2french() {
        return this.adresse2french;
    }

    public void setAdresse2french( String adresse2french ) {
        this.adresse2french = adresse2french;
    }

}
