package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChthibiPrints generated by hbm2java
 */
@Entity
@Table( name = "chthibi_prints", catalog = "vitalstatistics" )
public class ChthibiPrints implements java.io.Serializable {

    private Integer         id;
    private ChthibiDocument chthibiDocument;
    private ChthibiUser     chthibiUser;
    private Date            date;
    private int             copies;

    public ChthibiPrints() {
    }

    public ChthibiPrints( ChthibiDocument chthibiDocument, ChthibiUser chthibiUser, Date date, int copies ) {
        this.chthibiDocument = chthibiDocument;
        this.chthibiUser = chthibiUser;
        this.date = date;
        this.copies = copies;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDDOCUMENT", nullable = false )
    public ChthibiDocument getChthibiDocument() {
        return this.chthibiDocument;
    }

    public void setChthibiDocument( ChthibiDocument chthibiDocument ) {
        this.chthibiDocument = chthibiDocument;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDUSER", nullable = false )
    public ChthibiUser getChthibiUser() {
        return this.chthibiUser;
    }

    public void setChthibiUser( ChthibiUser chthibiUser ) {
        this.chthibiUser = chthibiUser;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "DATE", nullable = false, length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "COPIES", nullable = false )
    public int getCopies() {
        return this.copies;
    }

    public void setCopies( int copies ) {
        this.copies = copies;
    }

}
