package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChthibiDocument generated by hbm2java
 */
@Entity
@Table( name = "chthibi_document", catalog = "vitalstatistics" )
public class ChthibiDocument implements java.io.Serializable {

    private Integer                     id;
    private ChthibiRegistertype         chthibiRegistertype;
    private String                      labelfr;
    private String                      labelarabic;
    private int                         flag;
    private Set<ChthibiDocumentRequest> chthibiDocumentRequests = new HashSet<ChthibiDocumentRequest>( 0 );
    private Set<ChthibiPrints>          chthibiPrintses         = new HashSet<ChthibiPrints>( 0 );

    public ChthibiDocument() {
    }

    public ChthibiDocument( ChthibiRegistertype chthibiRegistertype, int flag ) {
        this.chthibiRegistertype = chthibiRegistertype;
        this.flag = flag;
    }

    public ChthibiDocument( ChthibiRegistertype chthibiRegistertype, String labelfr, String labelarabic, int flag,
            Set<ChthibiDocumentRequest> chthibiDocumentRequests, Set<ChthibiPrints> chthibiPrintses ) {
        this.chthibiRegistertype = chthibiRegistertype;
        this.labelfr = labelfr;
        this.labelarabic = labelarabic;
        this.flag = flag;
        this.chthibiDocumentRequests = chthibiDocumentRequests;
        this.chthibiPrintses = chthibiPrintses;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @ManyToOne( fetch = FetchType.LAZY )
    @JoinColumn( name = "IDREGISTERTYPE", nullable = false )
    public ChthibiRegistertype getChthibiRegistertype() {
        return this.chthibiRegistertype;
    }

    public void setChthibiRegistertype( ChthibiRegistertype chthibiRegistertype ) {
        this.chthibiRegistertype = chthibiRegistertype;
    }

    @Column( name = "LABELFR", length = 64 )
    public String getLabelfr() {
        return this.labelfr;
    }

    public void setLabelfr( String labelfr ) {
        this.labelfr = labelfr;
    }

    @Column( name = "LABELARABIC", length = 64 )
    public String getLabelarabic() {
        return this.labelarabic;
    }

    public void setLabelarabic( String labelarabic ) {
        this.labelarabic = labelarabic;
    }

    @Column( name = "FLAG", nullable = false )
    public int getFlag() {
        return this.flag;
    }

    public void setFlag( int flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "chthibiDocument" )
    public Set<ChthibiDocumentRequest> getChthibiDocumentRequests() {
        return this.chthibiDocumentRequests;
    }

    public void setChthibiDocumentRequests( Set<ChthibiDocumentRequest> chthibiDocumentRequests ) {
        this.chthibiDocumentRequests = chthibiDocumentRequests;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "chthibiDocument" )
    public Set<ChthibiPrints> getChthibiPrintses() {
        return this.chthibiPrintses;
    }

    public void setChthibiPrintses( Set<ChthibiPrints> chthibiPrintses ) {
        this.chthibiPrintses = chthibiPrintses;
    }

}
