package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChthibiIaddwife generated by hbm2java
 */
@Entity
@Table( name = "chthibi_iaddwife", catalog = "vitalstatistics" )
public class ChthibiIaddwife implements java.io.Serializable {

    private Integer id;
    private String  actarabic;
    private String  actfrench;
    private int     wifeorder;
    private String  wifenamearabic;
    private String  wifenamefrench;
    private int     editdaygeorgian;
    private int     editmonthgeorgian;
    private int     edityeargeorgian;
    private int     editdayhijri;
    private int     editmonthhijri;
    private int     edityearhijri;
    private String  mentionofficerarabic;
    private String  mentionofficerfrench;
    private int     idtype;
    private int     iddeath;
    private int     iduser;
    private int     valid;

    public ChthibiIaddwife() {
    }

    public ChthibiIaddwife( String actarabic, String actfrench, int wifeorder, String wifenamearabic,
            String wifenamefrench, int editdaygeorgian, int editmonthgeorgian, int edityeargeorgian, int editdayhijri,
            int editmonthhijri, int edityearhijri, String mentionofficerarabic, String mentionofficerfrench, int idtype,
            int iddeath, int iduser, int valid ) {
        this.actarabic = actarabic;
        this.actfrench = actfrench;
        this.wifeorder = wifeorder;
        this.wifenamearabic = wifenamearabic;
        this.wifenamefrench = wifenamefrench;
        this.editdaygeorgian = editdaygeorgian;
        this.editmonthgeorgian = editmonthgeorgian;
        this.edityeargeorgian = edityeargeorgian;
        this.editdayhijri = editdayhijri;
        this.editmonthhijri = editmonthhijri;
        this.edityearhijri = edityearhijri;
        this.mentionofficerarabic = mentionofficerarabic;
        this.mentionofficerfrench = mentionofficerfrench;
        this.idtype = idtype;
        this.iddeath = iddeath;
        this.iduser = iduser;
        this.valid = valid;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "ACTARABIC", nullable = false, length = 256 )
    public String getActarabic() {
        return this.actarabic;
    }

    public void setActarabic( String actarabic ) {
        this.actarabic = actarabic;
    }

    @Column( name = "ACTFRENCH", nullable = false, length = 256 )
    public String getActfrench() {
        return this.actfrench;
    }

    public void setActfrench( String actfrench ) {
        this.actfrench = actfrench;
    }

    @Column( name = "WIFEORDER", nullable = false )
    public int getWifeorder() {
        return this.wifeorder;
    }

    public void setWifeorder( int wifeorder ) {
        this.wifeorder = wifeorder;
    }

    @Column( name = "WIFENAMEARABIC", nullable = false, length = 256 )
    public String getWifenamearabic() {
        return this.wifenamearabic;
    }

    public void setWifenamearabic( String wifenamearabic ) {
        this.wifenamearabic = wifenamearabic;
    }

    @Column( name = "WIFENAMEFRENCH", nullable = false, length = 256 )
    public String getWifenamefrench() {
        return this.wifenamefrench;
    }

    public void setWifenamefrench( String wifenamefrench ) {
        this.wifenamefrench = wifenamefrench;
    }

    @Column( name = "EDITDAYGEORGIAN", nullable = false )
    public int getEditdaygeorgian() {
        return this.editdaygeorgian;
    }

    public void setEditdaygeorgian( int editdaygeorgian ) {
        this.editdaygeorgian = editdaygeorgian;
    }

    @Column( name = "EDITMONTHGEORGIAN", nullable = false )
    public int getEditmonthgeorgian() {
        return this.editmonthgeorgian;
    }

    public void setEditmonthgeorgian( int editmonthgeorgian ) {
        this.editmonthgeorgian = editmonthgeorgian;
    }

    @Column( name = "EDITYEARGEORGIAN", nullable = false )
    public int getEdityeargeorgian() {
        return this.edityeargeorgian;
    }

    public void setEdityeargeorgian( int edityeargeorgian ) {
        this.edityeargeorgian = edityeargeorgian;
    }

    @Column( name = "EDITDAYHIJRI", nullable = false )
    public int getEditdayhijri() {
        return this.editdayhijri;
    }

    public void setEditdayhijri( int editdayhijri ) {
        this.editdayhijri = editdayhijri;
    }

    @Column( name = "EDITMONTHHIJRI", nullable = false )
    public int getEditmonthhijri() {
        return this.editmonthhijri;
    }

    public void setEditmonthhijri( int editmonthhijri ) {
        this.editmonthhijri = editmonthhijri;
    }

    @Column( name = "EDITYEARHIJRI", nullable = false )
    public int getEdityearhijri() {
        return this.edityearhijri;
    }

    public void setEdityearhijri( int edityearhijri ) {
        this.edityearhijri = edityearhijri;
    }

    @Column( name = "MENTIONOFFICERARABIC", nullable = false, length = 256 )
    public String getMentionofficerarabic() {
        return this.mentionofficerarabic;
    }

    public void setMentionofficerarabic( String mentionofficerarabic ) {
        this.mentionofficerarabic = mentionofficerarabic;
    }

    @Column( name = "MENTIONOFFICERFRENCH", nullable = false, length = 256 )
    public String getMentionofficerfrench() {
        return this.mentionofficerfrench;
    }

    public void setMentionofficerfrench( String mentionofficerfrench ) {
        this.mentionofficerfrench = mentionofficerfrench;
    }

    @Column( name = "IDTYPE", nullable = false )
    public int getIdtype() {
        return this.idtype;
    }

    public void setIdtype( int idtype ) {
        this.idtype = idtype;
    }

    @Column( name = "IDDEATH", nullable = false )
    public int getIddeath() {
        return this.iddeath;
    }

    public void setIddeath( int iddeath ) {
        this.iddeath = iddeath;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

}
