package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChthibiIbirthRevision generated by hbm2java
 */
@Entity
@Table( name = "chthibi_ibirth_revision", catalog = "vitalstatistics" )
public class ChthibiIbirthRevision implements java.io.Serializable {

    private Integer id;
    private int     idbirth;
    private int     idtype;
    private int     field;
    private String  line;
    private String  newfr;
    private String  oldfr;
    private String  newar;
    private String  oldar;
    private String  new_;
    private String  old;
    private int     newdaygeorgian;
    private int     newmonthgeorgian;
    private int     newyeargeorgian;
    private int     newdayhijri;
    private int     newmonthhijri;
    private int     newyearhijri;
    private int     olddaygeorgian;
    private int     oldmonthgeorgian;
    private int     oldyeargeorgian;
    private int     olddayhijri;
    private int     oldmonthhijri;
    private int     oldyearhijri;
    private Date    date;
    private int     iduser;
    private int     valid;
    private String  mentionofficerar;
    private String  mentionofficerfr;

    public ChthibiIbirthRevision() {
    }

    public ChthibiIbirthRevision( int idbirth, int idtype, int field, String line, String newfr, String oldfr,
            String newar, String oldar, String new_, String old, int newdaygeorgian, int newmonthgeorgian,
            int newyeargeorgian, int newdayhijri, int newmonthhijri, int newyearhijri, int olddaygeorgian,
            int oldmonthgeorgian, int oldyeargeorgian, int olddayhijri, int oldmonthhijri, int oldyearhijri, int iduser,
            int valid ) {
        this.idbirth = idbirth;
        this.idtype = idtype;
        this.field = field;
        this.line = line;
        this.newfr = newfr;
        this.oldfr = oldfr;
        this.newar = newar;
        this.oldar = oldar;
        this.new_ = new_;
        this.old = old;
        this.newdaygeorgian = newdaygeorgian;
        this.newmonthgeorgian = newmonthgeorgian;
        this.newyeargeorgian = newyeargeorgian;
        this.newdayhijri = newdayhijri;
        this.newmonthhijri = newmonthhijri;
        this.newyearhijri = newyearhijri;
        this.olddaygeorgian = olddaygeorgian;
        this.oldmonthgeorgian = oldmonthgeorgian;
        this.oldyeargeorgian = oldyeargeorgian;
        this.olddayhijri = olddayhijri;
        this.oldmonthhijri = oldmonthhijri;
        this.oldyearhijri = oldyearhijri;
        this.iduser = iduser;
        this.valid = valid;
    }

    public ChthibiIbirthRevision( int idbirth, int idtype, int field, String line, String newfr, String oldfr,
            String newar, String oldar, String new_, String old, int newdaygeorgian, int newmonthgeorgian,
            int newyeargeorgian, int newdayhijri, int newmonthhijri, int newyearhijri, int olddaygeorgian,
            int oldmonthgeorgian, int oldyeargeorgian, int olddayhijri, int oldmonthhijri, int oldyearhijri, Date date,
            int iduser, int valid, String mentionofficerar, String mentionofficerfr ) {
        this.idbirth = idbirth;
        this.idtype = idtype;
        this.field = field;
        this.line = line;
        this.newfr = newfr;
        this.oldfr = oldfr;
        this.newar = newar;
        this.oldar = oldar;
        this.new_ = new_;
        this.old = old;
        this.newdaygeorgian = newdaygeorgian;
        this.newmonthgeorgian = newmonthgeorgian;
        this.newyeargeorgian = newyeargeorgian;
        this.newdayhijri = newdayhijri;
        this.newmonthhijri = newmonthhijri;
        this.newyearhijri = newyearhijri;
        this.olddaygeorgian = olddaygeorgian;
        this.oldmonthgeorgian = oldmonthgeorgian;
        this.oldyeargeorgian = oldyeargeorgian;
        this.olddayhijri = olddayhijri;
        this.oldmonthhijri = oldmonthhijri;
        this.oldyearhijri = oldyearhijri;
        this.date = date;
        this.iduser = iduser;
        this.valid = valid;
        this.mentionofficerar = mentionofficerar;
        this.mentionofficerfr = mentionofficerfr;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "IDBIRTH", nullable = false )
    public int getIdbirth() {
        return this.idbirth;
    }

    public void setIdbirth( int idbirth ) {
        this.idbirth = idbirth;
    }

    @Column( name = "IDTYPE", nullable = false )
    public int getIdtype() {
        return this.idtype;
    }

    public void setIdtype( int idtype ) {
        this.idtype = idtype;
    }

    @Column( name = "FIELD", nullable = false )
    public int getField() {
        return this.field;
    }

    public void setField( int field ) {
        this.field = field;
    }

    @Column( name = "LINE", nullable = false, length = 46 )
    public String getLine() {
        return this.line;
    }

    public void setLine( String line ) {
        this.line = line;
    }

    @Column( name = "NEWFR", nullable = false, length = 128 )
    public String getNewfr() {
        return this.newfr;
    }

    public void setNewfr( String newfr ) {
        this.newfr = newfr;
    }

    @Column( name = "OLDFR", nullable = false, length = 128 )
    public String getOldfr() {
        return this.oldfr;
    }

    public void setOldfr( String oldfr ) {
        this.oldfr = oldfr;
    }

    @Column( name = "NEWAR", nullable = false, length = 128 )
    public String getNewar() {
        return this.newar;
    }

    public void setNewar( String newar ) {
        this.newar = newar;
    }

    @Column( name = "OLDAR", nullable = false, length = 128 )
    public String getOldar() {
        return this.oldar;
    }

    public void setOldar( String oldar ) {
        this.oldar = oldar;
    }

    @Column( name = "NEW", nullable = false, length = 128 )
    public String getNew_() {
        return this.new_;
    }

    public void setNew_( String new_ ) {
        this.new_ = new_;
    }

    @Column( name = "OLD", nullable = false, length = 128 )
    public String getOld() {
        return this.old;
    }

    public void setOld( String old ) {
        this.old = old;
    }

    @Column( name = "NEWDAYGEORGIAN", nullable = false )
    public int getNewdaygeorgian() {
        return this.newdaygeorgian;
    }

    public void setNewdaygeorgian( int newdaygeorgian ) {
        this.newdaygeorgian = newdaygeorgian;
    }

    @Column( name = "NEWMONTHGEORGIAN", nullable = false )
    public int getNewmonthgeorgian() {
        return this.newmonthgeorgian;
    }

    public void setNewmonthgeorgian( int newmonthgeorgian ) {
        this.newmonthgeorgian = newmonthgeorgian;
    }

    @Column( name = "NEWYEARGEORGIAN", nullable = false )
    public int getNewyeargeorgian() {
        return this.newyeargeorgian;
    }

    public void setNewyeargeorgian( int newyeargeorgian ) {
        this.newyeargeorgian = newyeargeorgian;
    }

    @Column( name = "NEWDAYHIJRI", nullable = false )
    public int getNewdayhijri() {
        return this.newdayhijri;
    }

    public void setNewdayhijri( int newdayhijri ) {
        this.newdayhijri = newdayhijri;
    }

    @Column( name = "NEWMONTHHIJRI", nullable = false )
    public int getNewmonthhijri() {
        return this.newmonthhijri;
    }

    public void setNewmonthhijri( int newmonthhijri ) {
        this.newmonthhijri = newmonthhijri;
    }

    @Column( name = "NEWYEARHIJRI", nullable = false )
    public int getNewyearhijri() {
        return this.newyearhijri;
    }

    public void setNewyearhijri( int newyearhijri ) {
        this.newyearhijri = newyearhijri;
    }

    @Column( name = "OLDDAYGEORGIAN", nullable = false )
    public int getOlddaygeorgian() {
        return this.olddaygeorgian;
    }

    public void setOlddaygeorgian( int olddaygeorgian ) {
        this.olddaygeorgian = olddaygeorgian;
    }

    @Column( name = "OLDMONTHGEORGIAN", nullable = false )
    public int getOldmonthgeorgian() {
        return this.oldmonthgeorgian;
    }

    public void setOldmonthgeorgian( int oldmonthgeorgian ) {
        this.oldmonthgeorgian = oldmonthgeorgian;
    }

    @Column( name = "OLDYEARGEORGIAN", nullable = false )
    public int getOldyeargeorgian() {
        return this.oldyeargeorgian;
    }

    public void setOldyeargeorgian( int oldyeargeorgian ) {
        this.oldyeargeorgian = oldyeargeorgian;
    }

    @Column( name = "OLDDAYHIJRI", nullable = false )
    public int getOlddayhijri() {
        return this.olddayhijri;
    }

    public void setOlddayhijri( int olddayhijri ) {
        this.olddayhijri = olddayhijri;
    }

    @Column( name = "OLDMONTHHIJRI", nullable = false )
    public int getOldmonthhijri() {
        return this.oldmonthhijri;
    }

    public void setOldmonthhijri( int oldmonthhijri ) {
        this.oldmonthhijri = oldmonthhijri;
    }

    @Column( name = "OLDYEARHIJRI", nullable = false )
    public int getOldyearhijri() {
        return this.oldyearhijri;
    }

    public void setOldyearhijri( int oldyearhijri ) {
        this.oldyearhijri = oldyearhijri;
    }

    @Temporal( TemporalType.TIMESTAMP )
    @Column( name = "DATE", length = 19 )
    public Date getDate() {
        return this.date;
    }

    public void setDate( Date date ) {
        this.date = date;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @Column( name = "MENTIONOFFICERAR", length = 128 )
    public String getMentionofficerar() {
        return this.mentionofficerar;
    }

    public void setMentionofficerar( String mentionofficerar ) {
        this.mentionofficerar = mentionofficerar;
    }

    @Column( name = "MENTIONOFFICERFR", length = 128 )
    public String getMentionofficerfr() {
        return this.mentionofficerfr;
    }

    public void setMentionofficerfr( String mentionofficerfr ) {
        this.mentionofficerfr = mentionofficerfr;
    }

}
