package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChthibiIchosen generated by hbm2java
 */
@Entity
@Table( name = "chthibi_ichosen", catalog = "vitalstatistics" )
public class ChthibiIchosen implements java.io.Serializable {

    private Integer id;
    private int     idbirth;
    private int     idtype;
    private int     field;
    private String  fathername;
    private String  mothername;
    private String  familyname;
    private int     daygeorgianedition;
    private int     monthgeorgianedition;
    private int     yeargeorgianedition;
    private int     dayhijriedition;
    private int     monthhijriedition;
    private int     yearhijriedition;
    private int     iduser;
    private int     valid;
    private String  fathernamefr;
    private String  mothernamefr;
    private String  familynamefr;
    private String  mentionofficerar;
    private String  mentionofficerfr;

    public ChthibiIchosen() {
    }

    public ChthibiIchosen( int idbirth, int idtype, int field, int daygeorgianedition, int monthgeorgianedition,
            int yeargeorgianedition, int dayhijriedition, int monthhijriedition, int yearhijriedition, int iduser,
            int valid ) {
        this.idbirth = idbirth;
        this.idtype = idtype;
        this.field = field;
        this.daygeorgianedition = daygeorgianedition;
        this.monthgeorgianedition = monthgeorgianedition;
        this.yeargeorgianedition = yeargeorgianedition;
        this.dayhijriedition = dayhijriedition;
        this.monthhijriedition = monthhijriedition;
        this.yearhijriedition = yearhijriedition;
        this.iduser = iduser;
        this.valid = valid;
    }

    public ChthibiIchosen( int idbirth, int idtype, int field, String fathername, String mothername, String familyname,
            int daygeorgianedition, int monthgeorgianedition, int yeargeorgianedition, int dayhijriedition,
            int monthhijriedition, int yearhijriedition, int iduser, int valid, String fathernamefr,
            String mothernamefr, String familynamefr, String mentionofficerar, String mentionofficerfr ) {
        this.idbirth = idbirth;
        this.idtype = idtype;
        this.field = field;
        this.fathername = fathername;
        this.mothername = mothername;
        this.familyname = familyname;
        this.daygeorgianedition = daygeorgianedition;
        this.monthgeorgianedition = monthgeorgianedition;
        this.yeargeorgianedition = yeargeorgianedition;
        this.dayhijriedition = dayhijriedition;
        this.monthhijriedition = monthhijriedition;
        this.yearhijriedition = yearhijriedition;
        this.iduser = iduser;
        this.valid = valid;
        this.fathernamefr = fathernamefr;
        this.mothernamefr = mothernamefr;
        this.familynamefr = familynamefr;
        this.mentionofficerar = mentionofficerar;
        this.mentionofficerfr = mentionofficerfr;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "IDBIRTH", nullable = false )
    public int getIdbirth() {
        return this.idbirth;
    }

    public void setIdbirth( int idbirth ) {
        this.idbirth = idbirth;
    }

    @Column( name = "IDTYPE", nullable = false )
    public int getIdtype() {
        return this.idtype;
    }

    public void setIdtype( int idtype ) {
        this.idtype = idtype;
    }

    @Column( name = "FIELD", nullable = false )
    public int getField() {
        return this.field;
    }

    public void setField( int field ) {
        this.field = field;
    }

    @Column( name = "FATHERNAME", length = 128 )
    public String getFathername() {
        return this.fathername;
    }

    public void setFathername( String fathername ) {
        this.fathername = fathername;
    }

    @Column( name = "MOTHERNAME", length = 128 )
    public String getMothername() {
        return this.mothername;
    }

    public void setMothername( String mothername ) {
        this.mothername = mothername;
    }

    @Column( name = "FAMILYNAME", length = 128 )
    public String getFamilyname() {
        return this.familyname;
    }

    public void setFamilyname( String familyname ) {
        this.familyname = familyname;
    }

    @Column( name = "DAYGEORGIANEDITION", nullable = false )
    public int getDaygeorgianedition() {
        return this.daygeorgianedition;
    }

    public void setDaygeorgianedition( int daygeorgianedition ) {
        this.daygeorgianedition = daygeorgianedition;
    }

    @Column( name = "MONTHGEORGIANEDITION", nullable = false )
    public int getMonthgeorgianedition() {
        return this.monthgeorgianedition;
    }

    public void setMonthgeorgianedition( int monthgeorgianedition ) {
        this.monthgeorgianedition = monthgeorgianedition;
    }

    @Column( name = "YEARGEORGIANEDITION", nullable = false )
    public int getYeargeorgianedition() {
        return this.yeargeorgianedition;
    }

    public void setYeargeorgianedition( int yeargeorgianedition ) {
        this.yeargeorgianedition = yeargeorgianedition;
    }

    @Column( name = "DAYHIJRIEDITION", nullable = false )
    public int getDayhijriedition() {
        return this.dayhijriedition;
    }

    public void setDayhijriedition( int dayhijriedition ) {
        this.dayhijriedition = dayhijriedition;
    }

    @Column( name = "MONTHHIJRIEDITION", nullable = false )
    public int getMonthhijriedition() {
        return this.monthhijriedition;
    }

    public void setMonthhijriedition( int monthhijriedition ) {
        this.monthhijriedition = monthhijriedition;
    }

    @Column( name = "YEARHIJRIEDITION", nullable = false )
    public int getYearhijriedition() {
        return this.yearhijriedition;
    }

    public void setYearhijriedition( int yearhijriedition ) {
        this.yearhijriedition = yearhijriedition;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @Column( name = "FATHERNAMEFR", length = 128 )
    public String getFathernamefr() {
        return this.fathernamefr;
    }

    public void setFathernamefr( String fathernamefr ) {
        this.fathernamefr = fathernamefr;
    }

    @Column( name = "MOTHERNAMEFR", length = 128 )
    public String getMothernamefr() {
        return this.mothernamefr;
    }

    public void setMothernamefr( String mothernamefr ) {
        this.mothernamefr = mothernamefr;
    }

    @Column( name = "FAMILYNAMEFR", length = 128 )
    public String getFamilynamefr() {
        return this.familynamefr;
    }

    public void setFamilynamefr( String familynamefr ) {
        this.familynamefr = familynamefr;
    }

    @Column( name = "MENTIONOFFICERAR", length = 128 )
    public String getMentionofficerar() {
        return this.mentionofficerar;
    }

    public void setMentionofficerar( String mentionofficerar ) {
        this.mentionofficerar = mentionofficerar;
    }

    @Column( name = "MENTIONOFFICERFR", length = 128 )
    public String getMentionofficerfr() {
        return this.mentionofficerfr;
    }

    public void setMentionofficerfr( String mentionofficerfr ) {
        this.mentionofficerfr = mentionofficerfr;
    }

}
