package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChthibiIprovelastname generated by hbm2java
 */
@Entity
@Table( name = "chthibi_iprovelastname", catalog = "vitalstatistics" )
public class ChthibiIprovelastname implements java.io.Serializable {

    private Integer id;
    private String  lastnamearabic;
    private String  lastnamefrench;
    private String  originearabic;
    private String  originefrench;
    private String  mentionofficerar;
    private String  mentionofficerfr;
    private int     idtype;
    private int     iduser;
    private int     idbirth;
    private int     valid;
    private int     editdaygeorgian;
    private int     editmonthgeorgian;
    private int     edityeargeorgian;
    private int     editdayhijri;
    private int     editmonthhijri;
    private int     edityearhijri;

    public ChthibiIprovelastname() {
    }

    public ChthibiIprovelastname( String lastnamearabic, String lastnamefrench, int idtype, int iduser, int idbirth,
            int valid, int editdaygeorgian, int editmonthgeorgian, int edityeargeorgian, int editdayhijri,
            int editmonthhijri, int edityearhijri ) {
        this.lastnamearabic = lastnamearabic;
        this.lastnamefrench = lastnamefrench;
        this.idtype = idtype;
        this.iduser = iduser;
        this.idbirth = idbirth;
        this.valid = valid;
        this.editdaygeorgian = editdaygeorgian;
        this.editmonthgeorgian = editmonthgeorgian;
        this.edityeargeorgian = edityeargeorgian;
        this.editdayhijri = editdayhijri;
        this.editmonthhijri = editmonthhijri;
        this.edityearhijri = edityearhijri;
    }

    public ChthibiIprovelastname( String lastnamearabic, String lastnamefrench, String originearabic,
            String originefrench, String mentionofficerar, String mentionofficerfr, int idtype, int iduser, int idbirth,
            int valid, int editdaygeorgian, int editmonthgeorgian, int edityeargeorgian, int editdayhijri,
            int editmonthhijri, int edityearhijri ) {
        this.lastnamearabic = lastnamearabic;
        this.lastnamefrench = lastnamefrench;
        this.originearabic = originearabic;
        this.originefrench = originefrench;
        this.mentionofficerar = mentionofficerar;
        this.mentionofficerfr = mentionofficerfr;
        this.idtype = idtype;
        this.iduser = iduser;
        this.idbirth = idbirth;
        this.valid = valid;
        this.editdaygeorgian = editdaygeorgian;
        this.editmonthgeorgian = editmonthgeorgian;
        this.edityeargeorgian = edityeargeorgian;
        this.editdayhijri = editdayhijri;
        this.editmonthhijri = editmonthhijri;
        this.edityearhijri = edityearhijri;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "LASTNAMEARABIC", nullable = false, length = 256 )
    public String getLastnamearabic() {
        return this.lastnamearabic;
    }

    public void setLastnamearabic( String lastnamearabic ) {
        this.lastnamearabic = lastnamearabic;
    }

    @Column( name = "LASTNAMEFRENCH", nullable = false, length = 256 )
    public String getLastnamefrench() {
        return this.lastnamefrench;
    }

    public void setLastnamefrench( String lastnamefrench ) {
        this.lastnamefrench = lastnamefrench;
    }

    @Column( name = "ORIGINEARABIC", length = 65535 )
    public String getOriginearabic() {
        return this.originearabic;
    }

    public void setOriginearabic( String originearabic ) {
        this.originearabic = originearabic;
    }

    @Column( name = "ORIGINEFRENCH", length = 65535 )
    public String getOriginefrench() {
        return this.originefrench;
    }

    public void setOriginefrench( String originefrench ) {
        this.originefrench = originefrench;
    }

    @Column( name = "MENTIONOFFICERAR", length = 128 )
    public String getMentionofficerar() {
        return this.mentionofficerar;
    }

    public void setMentionofficerar( String mentionofficerar ) {
        this.mentionofficerar = mentionofficerar;
    }

    @Column( name = "MENTIONOFFICERFR", length = 128 )
    public String getMentionofficerfr() {
        return this.mentionofficerfr;
    }

    public void setMentionofficerfr( String mentionofficerfr ) {
        this.mentionofficerfr = mentionofficerfr;
    }

    @Column( name = "IDTYPE", nullable = false )
    public int getIdtype() {
        return this.idtype;
    }

    public void setIdtype( int idtype ) {
        this.idtype = idtype;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "IDBIRTH", nullable = false )
    public int getIdbirth() {
        return this.idbirth;
    }

    public void setIdbirth( int idbirth ) {
        this.idbirth = idbirth;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @Column( name = "EDITDAYGEORGIAN", nullable = false )
    public int getEditdaygeorgian() {
        return this.editdaygeorgian;
    }

    public void setEditdaygeorgian( int editdaygeorgian ) {
        this.editdaygeorgian = editdaygeorgian;
    }

    @Column( name = "EDITMONTHGEORGIAN", nullable = false )
    public int getEditmonthgeorgian() {
        return this.editmonthgeorgian;
    }

    public void setEditmonthgeorgian( int editmonthgeorgian ) {
        this.editmonthgeorgian = editmonthgeorgian;
    }

    @Column( name = "EDITYEARGEORGIAN", nullable = false )
    public int getEdityeargeorgian() {
        return this.edityeargeorgian;
    }

    public void setEdityeargeorgian( int edityeargeorgian ) {
        this.edityeargeorgian = edityeargeorgian;
    }

    @Column( name = "EDITDAYHIJRI", nullable = false )
    public int getEditdayhijri() {
        return this.editdayhijri;
    }

    public void setEditdayhijri( int editdayhijri ) {
        this.editdayhijri = editdayhijri;
    }

    @Column( name = "EDITMONTHHIJRI", nullable = false )
    public int getEditmonthhijri() {
        return this.editmonthhijri;
    }

    public void setEditmonthhijri( int editmonthhijri ) {
        this.editmonthhijri = editmonthhijri;
    }

    @Column( name = "EDITYEARHIJRI", nullable = false )
    public int getEdityearhijri() {
        return this.edityearhijri;
    }

    public void setEdityearhijri( int edityearhijri ) {
        this.edityearhijri = edityearhijri;
    }

}
