package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChthibiIndicationtype generated by hbm2java
 */
@Entity
@Table( name = "chthibi_indicationtype", catalog = "vitalstatistics" )
public class ChthibiIndicationtype implements java.io.Serializable {

    private Integer id;
    private String  labelfrench;
    private String  labelarabic;
    private int     flag;
    private String  content;
    private String  contentfr;

    public ChthibiIndicationtype() {
    }

    public ChthibiIndicationtype( int flag, String content ) {
        this.flag = flag;
        this.content = content;
    }

    public ChthibiIndicationtype( String labelfrench, String labelarabic, int flag, String content, String contentfr ) {
        this.labelfrench = labelfrench;
        this.labelarabic = labelarabic;
        this.flag = flag;
        this.content = content;
        this.contentfr = contentfr;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "LABELFRENCH" )
    public String getLabelfrench() {
        return this.labelfrench;
    }

    public void setLabelfrench( String labelfrench ) {
        this.labelfrench = labelfrench;
    }

    @Column( name = "LABELARABIC" )
    public String getLabelarabic() {
        return this.labelarabic;
    }

    public void setLabelarabic( String labelarabic ) {
        this.labelarabic = labelarabic;
    }

    @Column( name = "FLAG", nullable = false )
    public int getFlag() {
        return this.flag;
    }

    public void setFlag( int flag ) {
        this.flag = flag;
    }

    @Column( name = "CONTENT", nullable = false, length = 65535 )
    public String getContent() {
        return this.content;
    }

    public void setContent( String content ) {
        this.content = content;
    }

    @Column( name = "CONTENTFR", length = 65535 )
    public String getContentfr() {
        return this.contentfr;
    }

    public void setContentfr( String contentfr ) {
        this.contentfr = contentfr;
    }

}
