package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChthibiDistrict generated by hbm2java
 */
@Entity
@Table( name = "chthibi_district", catalog = "vitalstatistics" )
public class ChthibiDistrict implements java.io.Serializable {

    private Integer                     id;
    private String                      labelfrench;
    private String                      labelarabic;
    private int                         flag;
    private Set<ChthibiBirth>           chthibiBirths           = new HashSet<ChthibiBirth>( 0 );
    private Set<ChthibiDocumentRequest> chthibiDocumentRequests = new HashSet<ChthibiDocumentRequest>( 0 );

    public ChthibiDistrict() {
    }

    public ChthibiDistrict( int flag ) {
        this.flag = flag;
    }

    public ChthibiDistrict( String labelfrench, String labelarabic, int flag, Set<ChthibiBirth> chthibiBirths,
            Set<ChthibiDocumentRequest> chthibiDocumentRequests ) {
        this.labelfrench = labelfrench;
        this.labelarabic = labelarabic;
        this.flag = flag;
        this.chthibiBirths = chthibiBirths;
        this.chthibiDocumentRequests = chthibiDocumentRequests;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "LABELFRENCH", length = 64 )
    public String getLabelfrench() {
        return this.labelfrench;
    }

    public void setLabelfrench( String labelfrench ) {
        this.labelfrench = labelfrench;
    }

    @Column( name = "LABELARABIC", length = 64 )
    public String getLabelarabic() {
        return this.labelarabic;
    }

    public void setLabelarabic( String labelarabic ) {
        this.labelarabic = labelarabic;
    }

    @Column( name = "FLAG", nullable = false )
    public int getFlag() {
        return this.flag;
    }

    public void setFlag( int flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "chthibiDistrict" )
    public Set<ChthibiBirth> getChthibiBirths() {
        return this.chthibiBirths;
    }

    public void setChthibiBirths( Set<ChthibiBirth> chthibiBirths ) {
        this.chthibiBirths = chthibiBirths;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "chthibiDistrict" )
    public Set<ChthibiDocumentRequest> getChthibiDocumentRequests() {
        return this.chthibiDocumentRequests;
    }

    public void setChthibiDocumentRequests( Set<ChthibiDocumentRequest> chthibiDocumentRequests ) {
        this.chthibiDocumentRequests = chthibiDocumentRequests;
    }

}
