package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChthibiRegistertype generated by hbm2java
 */
@Entity
@Table( name = "chthibi_registertype", catalog = "vitalstatistics" )
public class ChthibiRegistertype implements java.io.Serializable {

    private Integer              id;
    private String               labelfrench;
    private String               labelarabic;
    private int                  flag;
    private Set<ChthibiDocument> chthibiDocuments = new HashSet<ChthibiDocument>( 0 );

    public ChthibiRegistertype() {
    }

    public ChthibiRegistertype( int flag ) {
        this.flag = flag;
    }

    public ChthibiRegistertype( String labelfrench, String labelarabic, int flag,
            Set<ChthibiDocument> chthibiDocuments ) {
        this.labelfrench = labelfrench;
        this.labelarabic = labelarabic;
        this.flag = flag;
        this.chthibiDocuments = chthibiDocuments;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "LABELFRENCH", length = 128 )
    public String getLabelfrench() {
        return this.labelfrench;
    }

    public void setLabelfrench( String labelfrench ) {
        this.labelfrench = labelfrench;
    }

    @Column( name = "LABELARABIC", length = 128 )
    public String getLabelarabic() {
        return this.labelarabic;
    }

    public void setLabelarabic( String labelarabic ) {
        this.labelarabic = labelarabic;
    }

    @Column( name = "FLAG", nullable = false )
    public int getFlag() {
        return this.flag;
    }

    public void setFlag( int flag ) {
        this.flag = flag;
    }

    @OneToMany( fetch = FetchType.LAZY, mappedBy = "chthibiRegistertype" )
    public Set<ChthibiDocument> getChthibiDocuments() {
        return this.chthibiDocuments;
    }

    public void setChthibiDocuments( Set<ChthibiDocument> chthibiDocuments ) {
        this.chthibiDocuments = chthibiDocuments;
    }

}
