package cg.ncn.entities.vital;
// Generated 9 juil. 2019 13:24:07 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChthibiIentername generated by hbm2java
 */
@Entity
@Table( name = "chthibi_ientername", catalog = "vitalstatistics" )
public class ChthibiIentername implements java.io.Serializable {

    private Integer id;
    private String  namearabic;
    private String  namefrench;
    private String  originearabic;
    private String  originefrench;
    private String  mentionofficerar;
    private String  mentionofficerfr;
    private int     idtype;
    private int     iduser;
    private int     idbirth;
    private int     valid;
    private int     daygeorgian;
    private int     monthgeorgian;
    private int     yeargeorgian;
    private int     editdaygeorgian;
    private int     editmonthgeorgian;
    private int     edityeargeorgian;
    private int     editdayhijri;
    private int     editmonthhijri;
    private int     edityearhijri;
    private String  eventarabic;
    private String  eventfrench;

    public ChthibiIentername() {
    }

    public ChthibiIentername( String namearabic, String namefrench, int idtype, int iduser, int idbirth, int valid,
            int daygeorgian, int monthgeorgian, int yeargeorgian, int editdaygeorgian, int editmonthgeorgian,
            int edityeargeorgian, int editdayhijri, int editmonthhijri, int edityearhijri, String eventarabic,
            String eventfrench ) {
        this.namearabic = namearabic;
        this.namefrench = namefrench;
        this.idtype = idtype;
        this.iduser = iduser;
        this.idbirth = idbirth;
        this.valid = valid;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.editdaygeorgian = editdaygeorgian;
        this.editmonthgeorgian = editmonthgeorgian;
        this.edityeargeorgian = edityeargeorgian;
        this.editdayhijri = editdayhijri;
        this.editmonthhijri = editmonthhijri;
        this.edityearhijri = edityearhijri;
        this.eventarabic = eventarabic;
        this.eventfrench = eventfrench;
    }

    public ChthibiIentername( String namearabic, String namefrench, String originearabic, String originefrench,
            String mentionofficerar, String mentionofficerfr, int idtype, int iduser, int idbirth, int valid,
            int daygeorgian, int monthgeorgian, int yeargeorgian, int editdaygeorgian, int editmonthgeorgian,
            int edityeargeorgian, int editdayhijri, int editmonthhijri, int edityearhijri, String eventarabic,
            String eventfrench ) {
        this.namearabic = namearabic;
        this.namefrench = namefrench;
        this.originearabic = originearabic;
        this.originefrench = originefrench;
        this.mentionofficerar = mentionofficerar;
        this.mentionofficerfr = mentionofficerfr;
        this.idtype = idtype;
        this.iduser = iduser;
        this.idbirth = idbirth;
        this.valid = valid;
        this.daygeorgian = daygeorgian;
        this.monthgeorgian = monthgeorgian;
        this.yeargeorgian = yeargeorgian;
        this.editdaygeorgian = editdaygeorgian;
        this.editmonthgeorgian = editmonthgeorgian;
        this.edityeargeorgian = edityeargeorgian;
        this.editdayhijri = editdayhijri;
        this.editmonthhijri = editmonthhijri;
        this.edityearhijri = edityearhijri;
        this.eventarabic = eventarabic;
        this.eventfrench = eventfrench;
    }

    @Id
    @GeneratedValue( strategy = IDENTITY )

    @Column( name = "ID", unique = true, nullable = false )
    public Integer getId() {
        return this.id;
    }

    public void setId( Integer id ) {
        this.id = id;
    }

    @Column( name = "NAMEARABIC", nullable = false, length = 256 )
    public String getNamearabic() {
        return this.namearabic;
    }

    public void setNamearabic( String namearabic ) {
        this.namearabic = namearabic;
    }

    @Column( name = "NAMEFRENCH", nullable = false, length = 256 )
    public String getNamefrench() {
        return this.namefrench;
    }

    public void setNamefrench( String namefrench ) {
        this.namefrench = namefrench;
    }

    @Column( name = "ORIGINEARABIC", length = 65535 )
    public String getOriginearabic() {
        return this.originearabic;
    }

    public void setOriginearabic( String originearabic ) {
        this.originearabic = originearabic;
    }

    @Column( name = "ORIGINEFRENCH", length = 65535 )
    public String getOriginefrench() {
        return this.originefrench;
    }

    public void setOriginefrench( String originefrench ) {
        this.originefrench = originefrench;
    }

    @Column( name = "MENTIONOFFICERAR", length = 128 )
    public String getMentionofficerar() {
        return this.mentionofficerar;
    }

    public void setMentionofficerar( String mentionofficerar ) {
        this.mentionofficerar = mentionofficerar;
    }

    @Column( name = "MENTIONOFFICERFR", length = 128 )
    public String getMentionofficerfr() {
        return this.mentionofficerfr;
    }

    public void setMentionofficerfr( String mentionofficerfr ) {
        this.mentionofficerfr = mentionofficerfr;
    }

    @Column( name = "IDTYPE", nullable = false )
    public int getIdtype() {
        return this.idtype;
    }

    public void setIdtype( int idtype ) {
        this.idtype = idtype;
    }

    @Column( name = "IDUSER", nullable = false )
    public int getIduser() {
        return this.iduser;
    }

    public void setIduser( int iduser ) {
        this.iduser = iduser;
    }

    @Column( name = "IDBIRTH", nullable = false )
    public int getIdbirth() {
        return this.idbirth;
    }

    public void setIdbirth( int idbirth ) {
        this.idbirth = idbirth;
    }

    @Column( name = "VALID", nullable = false )
    public int getValid() {
        return this.valid;
    }

    public void setValid( int valid ) {
        this.valid = valid;
    }

    @Column( name = "DAYGEORGIAN", nullable = false )
    public int getDaygeorgian() {
        return this.daygeorgian;
    }

    public void setDaygeorgian( int daygeorgian ) {
        this.daygeorgian = daygeorgian;
    }

    @Column( name = "MONTHGEORGIAN", nullable = false )
    public int getMonthgeorgian() {
        return this.monthgeorgian;
    }

    public void setMonthgeorgian( int monthgeorgian ) {
        this.monthgeorgian = monthgeorgian;
    }

    @Column( name = "YEARGEORGIAN", nullable = false )
    public int getYeargeorgian() {
        return this.yeargeorgian;
    }

    public void setYeargeorgian( int yeargeorgian ) {
        this.yeargeorgian = yeargeorgian;
    }

    @Column( name = "EDITDAYGEORGIAN", nullable = false )
    public int getEditdaygeorgian() {
        return this.editdaygeorgian;
    }

    public void setEditdaygeorgian( int editdaygeorgian ) {
        this.editdaygeorgian = editdaygeorgian;
    }

    @Column( name = "EDITMONTHGEORGIAN", nullable = false )
    public int getEditmonthgeorgian() {
        return this.editmonthgeorgian;
    }

    public void setEditmonthgeorgian( int editmonthgeorgian ) {
        this.editmonthgeorgian = editmonthgeorgian;
    }

    @Column( name = "EDITYEARGEORGIAN", nullable = false )
    public int getEdityeargeorgian() {
        return this.edityeargeorgian;
    }

    public void setEdityeargeorgian( int edityeargeorgian ) {
        this.edityeargeorgian = edityeargeorgian;
    }

    @Column( name = "EDITDAYHIJRI", nullable = false )
    public int getEditdayhijri() {
        return this.editdayhijri;
    }

    public void setEditdayhijri( int editdayhijri ) {
        this.editdayhijri = editdayhijri;
    }

    @Column( name = "EDITMONTHHIJRI", nullable = false )
    public int getEditmonthhijri() {
        return this.editmonthhijri;
    }

    public void setEditmonthhijri( int editmonthhijri ) {
        this.editmonthhijri = editmonthhijri;
    }

    @Column( name = "EDITYEARHIJRI", nullable = false )
    public int getEdityearhijri() {
        return this.edityearhijri;
    }

    public void setEdityearhijri( int edityearhijri ) {
        this.edityearhijri = edityearhijri;
    }

    @Column( name = "EVENTARABIC", nullable = false, length = 512 )
    public String getEventarabic() {
        return this.eventarabic;
    }

    public void setEventarabic( String eventarabic ) {
        this.eventarabic = eventarabic;
    }

    @Column( name = "EVENTFRENCH", nullable = false, length = 512 )
    public String getEventfrench() {
        return this.eventfrench;
    }

    public void setEventfrench( String eventfrench ) {
        this.eventfrench = eventfrench;
    }

}
